database:
  host: "postgres"
  port: 5432
  username: "admin"
  password: "admin"
  name: "hr"
  ssl_mode: "disable"

server:
  grpc_addr: ":50051"

auth:
  grpc_addr: "auth:50050"

multiagent:
  grpc_addr: "multiagent:50055"
