// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/artem13815/hr/analysis/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewAnalysisStorage creates a new instance of AnalysisStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalysisStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalysisStorage {
	mock := &AnalysisStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AnalysisStorage is an autogenerated mock type for the AnalysisStorage type
type AnalysisStorage struct {
	mock.Mock
}

type AnalysisStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *AnalysisStorage) EXPECT() *AnalysisStorage_Expecter {
	return &AnalysisStorage_Expecter{mock: &_m.Mock}
}

// GetAnalysis provides a mock function for the type AnalysisStorage
func (_mock *AnalysisStorage) GetAnalysis(ctx context.Context, analysisID string, requestUserID uint64, isAdmin bool) (*domain.Analysis, error) {
	ret := _mock.Called(ctx, analysisID, requestUserID, isAdmin)

	if len(ret) == 0 {
		panic("no return value specified for GetAnalysis")
	}

	var r0 *domain.Analysis
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, bool) (*domain.Analysis, error)); ok {
		return returnFunc(ctx, analysisID, requestUserID, isAdmin)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64, bool) *domain.Analysis); ok {
		r0 = returnFunc(ctx, analysisID, requestUserID, isAdmin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Analysis)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint64, bool) error); ok {
		r1 = returnFunc(ctx, analysisID, requestUserID, isAdmin)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AnalysisStorage_GetAnalysis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnalysis'
type AnalysisStorage_GetAnalysis_Call struct {
	*mock.Call
}

// GetAnalysis is a helper method to define mock.On call
//   - ctx context.Context
//   - analysisID string
//   - requestUserID uint64
//   - isAdmin bool
func (_e *AnalysisStorage_Expecter) GetAnalysis(ctx interface{}, analysisID interface{}, requestUserID interface{}, isAdmin interface{}) *AnalysisStorage_GetAnalysis_Call {
	return &AnalysisStorage_GetAnalysis_Call{Call: _e.mock.On("GetAnalysis", ctx, analysisID, requestUserID, isAdmin)}
}

func (_c *AnalysisStorage_GetAnalysis_Call) Run(run func(ctx context.Context, analysisID string, requestUserID uint64, isAdmin bool)) *AnalysisStorage_GetAnalysis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AnalysisStorage_GetAnalysis_Call) Return(analysis *domain.Analysis, err error) *AnalysisStorage_GetAnalysis_Call {
	_c.Call.Return(analysis, err)
	return _c
}

func (_c *AnalysisStorage_GetAnalysis_Call) RunAndReturn(run func(ctx context.Context, analysisID string, requestUserID uint64, isAdmin bool) (*domain.Analysis, error)) *AnalysisStorage_GetAnalysis_Call {
	_c.Call.Return(run)
	return _c
}

// ListCandidatesByVacancy provides a mock function for the type AnalysisStorage
func (_mock *AnalysisStorage) ListCandidatesByVacancy(ctx context.Context, in domain.ListCandidatesByVacancyInput) (*domain.ListCandidatesByVacancyResult, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for ListCandidatesByVacancy")
	}

	var r0 *domain.ListCandidatesByVacancyResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListCandidatesByVacancyInput) (*domain.ListCandidatesByVacancyResult, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListCandidatesByVacancyInput) *domain.ListCandidatesByVacancyResult); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ListCandidatesByVacancyResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ListCandidatesByVacancyInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AnalysisStorage_ListCandidatesByVacancy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCandidatesByVacancy'
type AnalysisStorage_ListCandidatesByVacancy_Call struct {
	*mock.Call
}

// ListCandidatesByVacancy is a helper method to define mock.On call
//   - ctx context.Context
//   - in domain.ListCandidatesByVacancyInput
func (_e *AnalysisStorage_Expecter) ListCandidatesByVacancy(ctx interface{}, in interface{}) *AnalysisStorage_ListCandidatesByVacancy_Call {
	return &AnalysisStorage_ListCandidatesByVacancy_Call{Call: _e.mock.On("ListCandidatesByVacancy", ctx, in)}
}

func (_c *AnalysisStorage_ListCandidatesByVacancy_Call) Run(run func(ctx context.Context, in domain.ListCandidatesByVacancyInput)) *AnalysisStorage_ListCandidatesByVacancy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ListCandidatesByVacancyInput
		if args[1] != nil {
			arg1 = args[1].(domain.ListCandidatesByVacancyInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AnalysisStorage_ListCandidatesByVacancy_Call) Return(listCandidatesByVacancyResult *domain.ListCandidatesByVacancyResult, err error) *AnalysisStorage_ListCandidatesByVacancy_Call {
	_c.Call.Return(listCandidatesByVacancyResult, err)
	return _c
}

func (_c *AnalysisStorage_ListCandidatesByVacancy_Call) RunAndReturn(run func(ctx context.Context, in domain.ListCandidatesByVacancyInput) (*domain.ListCandidatesByVacancyResult, error)) *AnalysisStorage_ListCandidatesByVacancy_Call {
	_c.Call.Return(run)
	return _c
}

// StartAnalysis provides a mock function for the type AnalysisStorage
func (_mock *AnalysisStorage) StartAnalysis(ctx context.Context, in domain.StartAnalysisInput) (*domain.StartAnalysisResult, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for StartAnalysis")
	}

	var r0 *domain.StartAnalysisResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.StartAnalysisInput) (*domain.StartAnalysisResult, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.StartAnalysisInput) *domain.StartAnalysisResult); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StartAnalysisResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.StartAnalysisInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AnalysisStorage_StartAnalysis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartAnalysis'
type AnalysisStorage_StartAnalysis_Call struct {
	*mock.Call
}

// StartAnalysis is a helper method to define mock.On call
//   - ctx context.Context
//   - in domain.StartAnalysisInput
func (_e *AnalysisStorage_Expecter) StartAnalysis(ctx interface{}, in interface{}) *AnalysisStorage_StartAnalysis_Call {
	return &AnalysisStorage_StartAnalysis_Call{Call: _e.mock.On("StartAnalysis", ctx, in)}
}

func (_c *AnalysisStorage_StartAnalysis_Call) Run(run func(ctx context.Context, in domain.StartAnalysisInput)) *AnalysisStorage_StartAnalysis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.StartAnalysisInput
		if args[1] != nil {
			arg1 = args[1].(domain.StartAnalysisInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AnalysisStorage_StartAnalysis_Call) Return(startAnalysisResult *domain.StartAnalysisResult, err error) *AnalysisStorage_StartAnalysis_Call {
	_c.Call.Return(startAnalysisResult, err)
	return _c
}

func (_c *AnalysisStorage_StartAnalysis_Call) RunAndReturn(run func(ctx context.Context, in domain.StartAnalysisInput) (*domain.StartAnalysisResult, error)) *AnalysisStorage_StartAnalysis_Call {
	_c.Call.Return(run)
	return _c
}
