server:
  http_addr: ":8080"
  cors:
    allowed_origins:
      - "http://localhost:5173"
      - "http://127.0.0.1:5173"
      - "http://localhost:4173"
      - "http://127.0.0.1:4173"

auth:
  grpc_addr: "auth:50050"

vacancy:
  grpc_addr: "vacancy:50051"

resume:
  grpc_addr: "resume:50052"

analysis:
  grpc_addr: "analysis:50054"
