// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/artem13815/hr/multiagent/internal/domain"
	"github.com/gojuno/minimock/v3"
)

// LLMMock implements mm_usecase.LLM
type LLMMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcComplete          func(ctx context.Context, in domain.CompletionRequest) (s1 string, err error)
	funcCompleteOrigin    string
	inspectFuncComplete   func(ctx context.Context, in domain.CompletionRequest)
	afterCompleteCounter  uint64
	beforeCompleteCounter uint64
	CompleteMock          mLLMMockComplete
}

// NewLLMMock returns a mock for mm_usecase.LLM
func NewLLMMock(t minimock.Tester) *LLMMock {
	m := &LLMMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CompleteMock = mLLMMockComplete{mock: m}
	m.CompleteMock.callArgs = []*LLMMockCompleteParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mLLMMockComplete struct {
	optional           bool
	mock               *LLMMock
	defaultExpectation *LLMMockCompleteExpectation
	expectations       []*LLMMockCompleteExpectation

	callArgs []*LLMMockCompleteParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LLMMockCompleteExpectation specifies expectation struct of the LLM.Complete
type LLMMockCompleteExpectation struct {
	mock               *LLMMock
	params             *LLMMockCompleteParams
	paramPtrs          *LLMMockCompleteParamPtrs
	expectationOrigins LLMMockCompleteExpectationOrigins
	results            *LLMMockCompleteResults
	returnOrigin       string
	Counter            uint64
}

// LLMMockCompleteParams contains parameters of the LLM.Complete
type LLMMockCompleteParams struct {
	ctx context.Context
	in  domain.CompletionRequest
}

// LLMMockCompleteParamPtrs contains pointers to parameters of the LLM.Complete
type LLMMockCompleteParamPtrs struct {
	ctx *context.Context
	in  *domain.CompletionRequest
}

// LLMMockCompleteResults contains results of the LLM.Complete
type LLMMockCompleteResults struct {
	s1  string
	err error
}

// LLMMockCompleteOrigins contains origins of expectations of the LLM.Complete
type LLMMockCompleteExpectationOrigins struct {
	origin    string
	originCtx string
	originIn  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmComplete *mLLMMockComplete) Optional() *mLLMMockComplete {
	mmComplete.optional = true
	return mmComplete
}

// Expect sets up expected params for LLM.Complete
func (mmComplete *mLLMMockComplete) Expect(ctx context.Context, in domain.CompletionRequest) *mLLMMockComplete {
	if mmComplete.mock.funcComplete != nil {
		mmComplete.mock.t.Fatalf("LLMMock.Complete mock is already set by Set")
	}

	if mmComplete.defaultExpectation == nil {
		mmComplete.defaultExpectation = &LLMMockCompleteExpectation{}
	}

	if mmComplete.defaultExpectation.paramPtrs != nil {
		mmComplete.mock.t.Fatalf("LLMMock.Complete mock is already set by ExpectParams functions")
	}

	mmComplete.defaultExpectation.params = &LLMMockCompleteParams{ctx, in}
	mmComplete.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmComplete.expectations {
		if minimock.Equal(e.params, mmComplete.defaultExpectation.params) {
			mmComplete.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmComplete.defaultExpectation.params)
		}
	}

	return mmComplete
}

// ExpectCtxParam1 sets up expected param ctx for LLM.Complete
func (mmComplete *mLLMMockComplete) ExpectCtxParam1(ctx context.Context) *mLLMMockComplete {
	if mmComplete.mock.funcComplete != nil {
		mmComplete.mock.t.Fatalf("LLMMock.Complete mock is already set by Set")
	}

	if mmComplete.defaultExpectation == nil {
		mmComplete.defaultExpectation = &LLMMockCompleteExpectation{}
	}

	if mmComplete.defaultExpectation.params != nil {
		mmComplete.mock.t.Fatalf("LLMMock.Complete mock is already set by Expect")
	}

	if mmComplete.defaultExpectation.paramPtrs == nil {
		mmComplete.defaultExpectation.paramPtrs = &LLMMockCompleteParamPtrs{}
	}
	mmComplete.defaultExpectation.paramPtrs.ctx = &ctx
	mmComplete.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmComplete
}

// ExpectInParam2 sets up expected param in for LLM.Complete
func (mmComplete *mLLMMockComplete) ExpectInParam2(in domain.CompletionRequest) *mLLMMockComplete {
	if mmComplete.mock.funcComplete != nil {
		mmComplete.mock.t.Fatalf("LLMMock.Complete mock is already set by Set")
	}

	if mmComplete.defaultExpectation == nil {
		mmComplete.defaultExpectation = &LLMMockCompleteExpectation{}
	}

	if mmComplete.defaultExpectation.params != nil {
		mmComplete.mock.t.Fatalf("LLMMock.Complete mock is already set by Expect")
	}

	if mmComplete.defaultExpectation.paramPtrs == nil {
		mmComplete.defaultExpectation.paramPtrs = &LLMMockCompleteParamPtrs{}
	}
	mmComplete.defaultExpectation.paramPtrs.in = &in
	mmComplete.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmComplete
}

// Inspect accepts an inspector function that has same arguments as the LLM.Complete
func (mmComplete *mLLMMockComplete) Inspect(f func(ctx context.Context, in domain.CompletionRequest)) *mLLMMockComplete {
	if mmComplete.mock.inspectFuncComplete != nil {
		mmComplete.mock.t.Fatalf("Inspect function is already set for LLMMock.Complete")
	}

	mmComplete.mock.inspectFuncComplete = f

	return mmComplete
}

// Return sets up results that will be returned by LLM.Complete
func (mmComplete *mLLMMockComplete) Return(s1 string, err error) *LLMMock {
	if mmComplete.mock.funcComplete != nil {
		mmComplete.mock.t.Fatalf("LLMMock.Complete mock is already set by Set")
	}

	if mmComplete.defaultExpectation == nil {
		mmComplete.defaultExpectation = &LLMMockCompleteExpectation{mock: mmComplete.mock}
	}
	mmComplete.defaultExpectation.results = &LLMMockCompleteResults{s1, err}
	mmComplete.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmComplete.mock
}

// Set uses given function f to mock the LLM.Complete method
func (mmComplete *mLLMMockComplete) Set(f func(ctx context.Context, in domain.CompletionRequest) (s1 string, err error)) *LLMMock {
	if mmComplete.defaultExpectation != nil {
		mmComplete.mock.t.Fatalf("Default expectation is already set for the LLM.Complete method")
	}

	if len(mmComplete.expectations) > 0 {
		mmComplete.mock.t.Fatalf("Some expectations are already set for the LLM.Complete method")
	}

	mmComplete.mock.funcComplete = f
	mmComplete.mock.funcCompleteOrigin = minimock.CallerInfo(1)
	return mmComplete.mock
}

// When sets expectation for the LLM.Complete which will trigger the result defined by the following
// Then helper
func (mmComplete *mLLMMockComplete) When(ctx context.Context, in domain.CompletionRequest) *LLMMockCompleteExpectation {
	if mmComplete.mock.funcComplete != nil {
		mmComplete.mock.t.Fatalf("LLMMock.Complete mock is already set by Set")
	}

	expectation := &LLMMockCompleteExpectation{
		mock:               mmComplete.mock,
		params:             &LLMMockCompleteParams{ctx, in},
		expectationOrigins: LLMMockCompleteExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmComplete.expectations = append(mmComplete.expectations, expectation)
	return expectation
}

// Then sets up LLM.Complete return parameters for the expectation previously defined by the When method
func (e *LLMMockCompleteExpectation) Then(s1 string, err error) *LLMMock {
	e.results = &LLMMockCompleteResults{s1, err}
	return e.mock
}

// Times sets number of times LLM.Complete should be invoked
func (mmComplete *mLLMMockComplete) Times(n uint64) *mLLMMockComplete {
	if n == 0 {
		mmComplete.mock.t.Fatalf("Times of LLMMock.Complete mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmComplete.expectedInvocations, n)
	mmComplete.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmComplete
}

func (mmComplete *mLLMMockComplete) invocationsDone() bool {
	if len(mmComplete.expectations) == 0 && mmComplete.defaultExpectation == nil && mmComplete.mock.funcComplete == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmComplete.mock.afterCompleteCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmComplete.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Complete implements mm_usecase.LLM
func (mmComplete *LLMMock) Complete(ctx context.Context, in domain.CompletionRequest) (s1 string, err error) {
	mm_atomic.AddUint64(&mmComplete.beforeCompleteCounter, 1)
	defer mm_atomic.AddUint64(&mmComplete.afterCompleteCounter, 1)

	mmComplete.t.Helper()

	if mmComplete.inspectFuncComplete != nil {
		mmComplete.inspectFuncComplete(ctx, in)
	}

	mm_params := LLMMockCompleteParams{ctx, in}

	// Record call args
	mmComplete.CompleteMock.mutex.Lock()
	mmComplete.CompleteMock.callArgs = append(mmComplete.CompleteMock.callArgs, &mm_params)
	mmComplete.CompleteMock.mutex.Unlock()

	for _, e := range mmComplete.CompleteMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmComplete.CompleteMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmComplete.CompleteMock.defaultExpectation.Counter, 1)
		mm_want := mmComplete.CompleteMock.defaultExpectation.params
		mm_want_ptrs := mmComplete.CompleteMock.defaultExpectation.paramPtrs

		mm_got := LLMMockCompleteParams{ctx, in}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmComplete.t.Errorf("LLMMock.Complete got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmComplete.CompleteMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmComplete.t.Errorf("LLMMock.Complete got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmComplete.CompleteMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmComplete.t.Errorf("LLMMock.Complete got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmComplete.CompleteMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmComplete.CompleteMock.defaultExpectation.results
		if mm_results == nil {
			mmComplete.t.Fatal("No results are set for the LLMMock.Complete")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmComplete.funcComplete != nil {
		return mmComplete.funcComplete(ctx, in)
	}
	mmComplete.t.Fatalf("Unexpected call to LLMMock.Complete. %v %v", ctx, in)
	return
}

// CompleteAfterCounter returns a count of finished LLMMock.Complete invocations
func (mmComplete *LLMMock) CompleteAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmComplete.afterCompleteCounter)
}

// CompleteBeforeCounter returns a count of LLMMock.Complete invocations
func (mmComplete *LLMMock) CompleteBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmComplete.beforeCompleteCounter)
}

// Calls returns a list of arguments used in each call to LLMMock.Complete.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmComplete *mLLMMockComplete) Calls() []*LLMMockCompleteParams {
	mmComplete.mutex.RLock()

	argCopy := make([]*LLMMockCompleteParams, len(mmComplete.callArgs))
	copy(argCopy, mmComplete.callArgs)

	mmComplete.mutex.RUnlock()

	return argCopy
}

// MinimockCompleteDone returns true if the count of the Complete invocations corresponds
// the number of defined expectations
func (m *LLMMock) MinimockCompleteDone() bool {
	if m.CompleteMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CompleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CompleteMock.invocationsDone()
}

// MinimockCompleteInspect logs each unmet expectation
func (m *LLMMock) MinimockCompleteInspect() {
	for _, e := range m.CompleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LLMMock.Complete at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCompleteCounter := mm_atomic.LoadUint64(&m.afterCompleteCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CompleteMock.defaultExpectation != nil && afterCompleteCounter < 1 {
		if m.CompleteMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LLMMock.Complete at\n%s", m.CompleteMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LLMMock.Complete at\n%s with params: %#v", m.CompleteMock.defaultExpectation.expectationOrigins.origin, *m.CompleteMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcComplete != nil && afterCompleteCounter < 1 {
		m.t.Errorf("Expected call to LLMMock.Complete at\n%s", m.funcCompleteOrigin)
	}

	if !m.CompleteMock.invocationsDone() && afterCompleteCounter > 0 {
		m.t.Errorf("Expected %d calls to LLMMock.Complete at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CompleteMock.expectedInvocations), m.CompleteMock.expectedInvocationsOrigin, afterCompleteCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *LLMMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCompleteInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *LLMMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *LLMMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCompleteDone()
}
