// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// PromptStoreMock implements mm_usecase.PromptStore
type PromptStoreMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGet          func(role string) (s1 string)
	funcGetOrigin    string
	inspectFuncGet   func(role string)
	afterGetCounter  uint64
	beforeGetCounter uint64
	GetMock          mPromptStoreMockGet
}

// NewPromptStoreMock returns a mock for mm_usecase.PromptStore
func NewPromptStoreMock(t minimock.Tester) *PromptStoreMock {
	m := &PromptStoreMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetMock = mPromptStoreMockGet{mock: m}
	m.GetMock.callArgs = []*PromptStoreMockGetParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mPromptStoreMockGet struct {
	optional           bool
	mock               *PromptStoreMock
	defaultExpectation *PromptStoreMockGetExpectation
	expectations       []*PromptStoreMockGetExpectation

	callArgs []*PromptStoreMockGetParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// PromptStoreMockGetExpectation specifies expectation struct of the PromptStore.Get
type PromptStoreMockGetExpectation struct {
	mock               *PromptStoreMock
	params             *PromptStoreMockGetParams
	paramPtrs          *PromptStoreMockGetParamPtrs
	expectationOrigins PromptStoreMockGetExpectationOrigins
	results            *PromptStoreMockGetResults
	returnOrigin       string
	Counter            uint64
}

// PromptStoreMockGetParams contains parameters of the PromptStore.Get
type PromptStoreMockGetParams struct {
	role string
}

// PromptStoreMockGetParamPtrs contains pointers to parameters of the PromptStore.Get
type PromptStoreMockGetParamPtrs struct {
	role *string
}

// PromptStoreMockGetResults contains results of the PromptStore.Get
type PromptStoreMockGetResults struct {
	s1 string
}

// PromptStoreMockGetOrigins contains origins of expectations of the PromptStore.Get
type PromptStoreMockGetExpectationOrigins struct {
	origin     string
	originRole string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGet *mPromptStoreMockGet) Optional() *mPromptStoreMockGet {
	mmGet.optional = true
	return mmGet
}

// Expect sets up expected params for PromptStore.Get
func (mmGet *mPromptStoreMockGet) Expect(role string) *mPromptStoreMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("PromptStoreMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &PromptStoreMockGetExpectation{}
	}

	if mmGet.defaultExpectation.paramPtrs != nil {
		mmGet.mock.t.Fatalf("PromptStoreMock.Get mock is already set by ExpectParams functions")
	}

	mmGet.defaultExpectation.params = &PromptStoreMockGetParams{role}
	mmGet.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGet.expectations {
		if minimock.Equal(e.params, mmGet.defaultExpectation.params) {
			mmGet.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGet.defaultExpectation.params)
		}
	}

	return mmGet
}

// ExpectRoleParam1 sets up expected param role for PromptStore.Get
func (mmGet *mPromptStoreMockGet) ExpectRoleParam1(role string) *mPromptStoreMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("PromptStoreMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &PromptStoreMockGetExpectation{}
	}

	if mmGet.defaultExpectation.params != nil {
		mmGet.mock.t.Fatalf("PromptStoreMock.Get mock is already set by Expect")
	}

	if mmGet.defaultExpectation.paramPtrs == nil {
		mmGet.defaultExpectation.paramPtrs = &PromptStoreMockGetParamPtrs{}
	}
	mmGet.defaultExpectation.paramPtrs.role = &role
	mmGet.defaultExpectation.expectationOrigins.originRole = minimock.CallerInfo(1)

	return mmGet
}

// Inspect accepts an inspector function that has same arguments as the PromptStore.Get
func (mmGet *mPromptStoreMockGet) Inspect(f func(role string)) *mPromptStoreMockGet {
	if mmGet.mock.inspectFuncGet != nil {
		mmGet.mock.t.Fatalf("Inspect function is already set for PromptStoreMock.Get")
	}

	mmGet.mock.inspectFuncGet = f

	return mmGet
}

// Return sets up results that will be returned by PromptStore.Get
func (mmGet *mPromptStoreMockGet) Return(s1 string) *PromptStoreMock {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("PromptStoreMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &PromptStoreMockGetExpectation{mock: mmGet.mock}
	}
	mmGet.defaultExpectation.results = &PromptStoreMockGetResults{s1}
	mmGet.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGet.mock
}

// Set uses given function f to mock the PromptStore.Get method
func (mmGet *mPromptStoreMockGet) Set(f func(role string) (s1 string)) *PromptStoreMock {
	if mmGet.defaultExpectation != nil {
		mmGet.mock.t.Fatalf("Default expectation is already set for the PromptStore.Get method")
	}

	if len(mmGet.expectations) > 0 {
		mmGet.mock.t.Fatalf("Some expectations are already set for the PromptStore.Get method")
	}

	mmGet.mock.funcGet = f
	mmGet.mock.funcGetOrigin = minimock.CallerInfo(1)
	return mmGet.mock
}

// When sets expectation for the PromptStore.Get which will trigger the result defined by the following
// Then helper
func (mmGet *mPromptStoreMockGet) When(role string) *PromptStoreMockGetExpectation {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("PromptStoreMock.Get mock is already set by Set")
	}

	expectation := &PromptStoreMockGetExpectation{
		mock:               mmGet.mock,
		params:             &PromptStoreMockGetParams{role},
		expectationOrigins: PromptStoreMockGetExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGet.expectations = append(mmGet.expectations, expectation)
	return expectation
}

// Then sets up PromptStore.Get return parameters for the expectation previously defined by the When method
func (e *PromptStoreMockGetExpectation) Then(s1 string) *PromptStoreMock {
	e.results = &PromptStoreMockGetResults{s1}
	return e.mock
}

// Times sets number of times PromptStore.Get should be invoked
func (mmGet *mPromptStoreMockGet) Times(n uint64) *mPromptStoreMockGet {
	if n == 0 {
		mmGet.mock.t.Fatalf("Times of PromptStoreMock.Get mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGet.expectedInvocations, n)
	mmGet.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGet
}

func (mmGet *mPromptStoreMockGet) invocationsDone() bool {
	if len(mmGet.expectations) == 0 && mmGet.defaultExpectation == nil && mmGet.mock.funcGet == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGet.mock.afterGetCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGet.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Get implements mm_usecase.PromptStore
func (mmGet *PromptStoreMock) Get(role string) (s1 string) {
	mm_atomic.AddUint64(&mmGet.beforeGetCounter, 1)
	defer mm_atomic.AddUint64(&mmGet.afterGetCounter, 1)

	mmGet.t.Helper()

	if mmGet.inspectFuncGet != nil {
		mmGet.inspectFuncGet(role)
	}

	mm_params := PromptStoreMockGetParams{role}

	// Record call args
	mmGet.GetMock.mutex.Lock()
	mmGet.GetMock.callArgs = append(mmGet.GetMock.callArgs, &mm_params)
	mmGet.GetMock.mutex.Unlock()

	for _, e := range mmGet.GetMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1
		}
	}

	if mmGet.GetMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGet.GetMock.defaultExpectation.Counter, 1)
		mm_want := mmGet.GetMock.defaultExpectation.params
		mm_want_ptrs := mmGet.GetMock.defaultExpectation.paramPtrs

		mm_got := PromptStoreMockGetParams{role}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.role != nil && !minimock.Equal(*mm_want_ptrs.role, mm_got.role) {
				mmGet.t.Errorf("PromptStoreMock.Get got unexpected parameter role, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGet.GetMock.defaultExpectation.expectationOrigins.originRole, *mm_want_ptrs.role, mm_got.role, minimock.Diff(*mm_want_ptrs.role, mm_got.role))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGet.t.Errorf("PromptStoreMock.Get got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGet.GetMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGet.GetMock.defaultExpectation.results
		if mm_results == nil {
			mmGet.t.Fatal("No results are set for the PromptStoreMock.Get")
		}
		return (*mm_results).s1
	}
	if mmGet.funcGet != nil {
		return mmGet.funcGet(role)
	}
	mmGet.t.Fatalf("Unexpected call to PromptStoreMock.Get. %v", role)
	return
}

// GetAfterCounter returns a count of finished PromptStoreMock.Get invocations
func (mmGet *PromptStoreMock) GetAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.afterGetCounter)
}

// GetBeforeCounter returns a count of PromptStoreMock.Get invocations
func (mmGet *PromptStoreMock) GetBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.beforeGetCounter)
}

// Calls returns a list of arguments used in each call to PromptStoreMock.Get.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGet *mPromptStoreMockGet) Calls() []*PromptStoreMockGetParams {
	mmGet.mutex.RLock()

	argCopy := make([]*PromptStoreMockGetParams, len(mmGet.callArgs))
	copy(argCopy, mmGet.callArgs)

	mmGet.mutex.RUnlock()

	return argCopy
}

// MinimockGetDone returns true if the count of the Get invocations corresponds
// the number of defined expectations
func (m *PromptStoreMock) MinimockGetDone() bool {
	if m.GetMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetMock.invocationsDone()
}

// MinimockGetInspect logs each unmet expectation
func (m *PromptStoreMock) MinimockGetInspect() {
	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to PromptStoreMock.Get at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetCounter := mm_atomic.LoadUint64(&m.afterGetCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetMock.defaultExpectation != nil && afterGetCounter < 1 {
		if m.GetMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to PromptStoreMock.Get at\n%s", m.GetMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to PromptStoreMock.Get at\n%s with params: %#v", m.GetMock.defaultExpectation.expectationOrigins.origin, *m.GetMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGet != nil && afterGetCounter < 1 {
		m.t.Errorf("Expected call to PromptStoreMock.Get at\n%s", m.funcGetOrigin)
	}

	if !m.GetMock.invocationsDone() && afterGetCounter > 0 {
		m.t.Errorf("Expected %d calls to PromptStoreMock.Get at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetMock.expectedInvocations), m.GetMock.expectedInvocationsOrigin, afterGetCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *PromptStoreMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *PromptStoreMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *PromptStoreMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetDone()
}
