// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/artem13815/hr/auth/internal/domain"
	"github.com/gojuno/minimock/v3"
)

// AuthStorageMock implements mm_auth_service.AuthStorage
type AuthStorageMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateUser          func(ctx context.Context, email string, passwordHash string) (u1 uint64, err error)
	funcCreateUserOrigin    string
	inspectFuncCreateUser   func(ctx context.Context, email string, passwordHash string)
	afterCreateUserCounter  uint64
	beforeCreateUserCounter uint64
	CreateUserMock          mAuthStorageMockCreateUser

	funcGetUserByEmail          func(ctx context.Context, email string) (up1 *domain.User, err error)
	funcGetUserByEmailOrigin    string
	inspectFuncGetUserByEmail   func(ctx context.Context, email string)
	afterGetUserByEmailCounter  uint64
	beforeGetUserByEmailCounter uint64
	GetUserByEmailMock          mAuthStorageMockGetUserByEmail

	funcGetUserByID          func(ctx context.Context, userID uint64) (up1 *domain.User, err error)
	funcGetUserByIDOrigin    string
	inspectFuncGetUserByID   func(ctx context.Context, userID uint64)
	afterGetUserByIDCounter  uint64
	beforeGetUserByIDCounter uint64
	GetUserByIDMock          mAuthStorageMockGetUserByID

	funcUpdateUserRole          func(ctx context.Context, userID uint64, role string) (err error)
	funcUpdateUserRoleOrigin    string
	inspectFuncUpdateUserRole   func(ctx context.Context, userID uint64, role string)
	afterUpdateUserRoleCounter  uint64
	beforeUpdateUserRoleCounter uint64
	UpdateUserRoleMock          mAuthStorageMockUpdateUserRole
}

// NewAuthStorageMock returns a mock for mm_auth_service.AuthStorage
func NewAuthStorageMock(t minimock.Tester) *AuthStorageMock {
	m := &AuthStorageMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateUserMock = mAuthStorageMockCreateUser{mock: m}
	m.CreateUserMock.callArgs = []*AuthStorageMockCreateUserParams{}

	m.GetUserByEmailMock = mAuthStorageMockGetUserByEmail{mock: m}
	m.GetUserByEmailMock.callArgs = []*AuthStorageMockGetUserByEmailParams{}

	m.GetUserByIDMock = mAuthStorageMockGetUserByID{mock: m}
	m.GetUserByIDMock.callArgs = []*AuthStorageMockGetUserByIDParams{}

	m.UpdateUserRoleMock = mAuthStorageMockUpdateUserRole{mock: m}
	m.UpdateUserRoleMock.callArgs = []*AuthStorageMockUpdateUserRoleParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAuthStorageMockCreateUser struct {
	optional           bool
	mock               *AuthStorageMock
	defaultExpectation *AuthStorageMockCreateUserExpectation
	expectations       []*AuthStorageMockCreateUserExpectation

	callArgs []*AuthStorageMockCreateUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthStorageMockCreateUserExpectation specifies expectation struct of the AuthStorage.CreateUser
type AuthStorageMockCreateUserExpectation struct {
	mock               *AuthStorageMock
	params             *AuthStorageMockCreateUserParams
	paramPtrs          *AuthStorageMockCreateUserParamPtrs
	expectationOrigins AuthStorageMockCreateUserExpectationOrigins
	results            *AuthStorageMockCreateUserResults
	returnOrigin       string
	Counter            uint64
}

// AuthStorageMockCreateUserParams contains parameters of the AuthStorage.CreateUser
type AuthStorageMockCreateUserParams struct {
	ctx          context.Context
	email        string
	passwordHash string
}

// AuthStorageMockCreateUserParamPtrs contains pointers to parameters of the AuthStorage.CreateUser
type AuthStorageMockCreateUserParamPtrs struct {
	ctx          *context.Context
	email        *string
	passwordHash *string
}

// AuthStorageMockCreateUserResults contains results of the AuthStorage.CreateUser
type AuthStorageMockCreateUserResults struct {
	u1  uint64
	err error
}

// AuthStorageMockCreateUserOrigins contains origins of expectations of the AuthStorage.CreateUser
type AuthStorageMockCreateUserExpectationOrigins struct {
	origin             string
	originCtx          string
	originEmail        string
	originPasswordHash string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateUser *mAuthStorageMockCreateUser) Optional() *mAuthStorageMockCreateUser {
	mmCreateUser.optional = true
	return mmCreateUser
}

// Expect sets up expected params for AuthStorage.CreateUser
func (mmCreateUser *mAuthStorageMockCreateUser) Expect(ctx context.Context, email string, passwordHash string) *mAuthStorageMockCreateUser {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("AuthStorageMock.CreateUser mock is already set by Set")
	}

	if mmCreateUser.defaultExpectation == nil {
		mmCreateUser.defaultExpectation = &AuthStorageMockCreateUserExpectation{}
	}

	if mmCreateUser.defaultExpectation.paramPtrs != nil {
		mmCreateUser.mock.t.Fatalf("AuthStorageMock.CreateUser mock is already set by ExpectParams functions")
	}

	mmCreateUser.defaultExpectation.params = &AuthStorageMockCreateUserParams{ctx, email, passwordHash}
	mmCreateUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateUser.expectations {
		if minimock.Equal(e.params, mmCreateUser.defaultExpectation.params) {
			mmCreateUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateUser.defaultExpectation.params)
		}
	}

	return mmCreateUser
}

// ExpectCtxParam1 sets up expected param ctx for AuthStorage.CreateUser
func (mmCreateUser *mAuthStorageMockCreateUser) ExpectCtxParam1(ctx context.Context) *mAuthStorageMockCreateUser {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("AuthStorageMock.CreateUser mock is already set by Set")
	}

	if mmCreateUser.defaultExpectation == nil {
		mmCreateUser.defaultExpectation = &AuthStorageMockCreateUserExpectation{}
	}

	if mmCreateUser.defaultExpectation.params != nil {
		mmCreateUser.mock.t.Fatalf("AuthStorageMock.CreateUser mock is already set by Expect")
	}

	if mmCreateUser.defaultExpectation.paramPtrs == nil {
		mmCreateUser.defaultExpectation.paramPtrs = &AuthStorageMockCreateUserParamPtrs{}
	}
	mmCreateUser.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateUser.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateUser
}

// ExpectEmailParam2 sets up expected param email for AuthStorage.CreateUser
func (mmCreateUser *mAuthStorageMockCreateUser) ExpectEmailParam2(email string) *mAuthStorageMockCreateUser {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("AuthStorageMock.CreateUser mock is already set by Set")
	}

	if mmCreateUser.defaultExpectation == nil {
		mmCreateUser.defaultExpectation = &AuthStorageMockCreateUserExpectation{}
	}

	if mmCreateUser.defaultExpectation.params != nil {
		mmCreateUser.mock.t.Fatalf("AuthStorageMock.CreateUser mock is already set by Expect")
	}

	if mmCreateUser.defaultExpectation.paramPtrs == nil {
		mmCreateUser.defaultExpectation.paramPtrs = &AuthStorageMockCreateUserParamPtrs{}
	}
	mmCreateUser.defaultExpectation.paramPtrs.email = &email
	mmCreateUser.defaultExpectation.expectationOrigins.originEmail = minimock.CallerInfo(1)

	return mmCreateUser
}

// ExpectPasswordHashParam3 sets up expected param passwordHash for AuthStorage.CreateUser
func (mmCreateUser *mAuthStorageMockCreateUser) ExpectPasswordHashParam3(passwordHash string) *mAuthStorageMockCreateUser {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("AuthStorageMock.CreateUser mock is already set by Set")
	}

	if mmCreateUser.defaultExpectation == nil {
		mmCreateUser.defaultExpectation = &AuthStorageMockCreateUserExpectation{}
	}

	if mmCreateUser.defaultExpectation.params != nil {
		mmCreateUser.mock.t.Fatalf("AuthStorageMock.CreateUser mock is already set by Expect")
	}

	if mmCreateUser.defaultExpectation.paramPtrs == nil {
		mmCreateUser.defaultExpectation.paramPtrs = &AuthStorageMockCreateUserParamPtrs{}
	}
	mmCreateUser.defaultExpectation.paramPtrs.passwordHash = &passwordHash
	mmCreateUser.defaultExpectation.expectationOrigins.originPasswordHash = minimock.CallerInfo(1)

	return mmCreateUser
}

// Inspect accepts an inspector function that has same arguments as the AuthStorage.CreateUser
func (mmCreateUser *mAuthStorageMockCreateUser) Inspect(f func(ctx context.Context, email string, passwordHash string)) *mAuthStorageMockCreateUser {
	if mmCreateUser.mock.inspectFuncCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("Inspect function is already set for AuthStorageMock.CreateUser")
	}

	mmCreateUser.mock.inspectFuncCreateUser = f

	return mmCreateUser
}

// Return sets up results that will be returned by AuthStorage.CreateUser
func (mmCreateUser *mAuthStorageMockCreateUser) Return(u1 uint64, err error) *AuthStorageMock {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("AuthStorageMock.CreateUser mock is already set by Set")
	}

	if mmCreateUser.defaultExpectation == nil {
		mmCreateUser.defaultExpectation = &AuthStorageMockCreateUserExpectation{mock: mmCreateUser.mock}
	}
	mmCreateUser.defaultExpectation.results = &AuthStorageMockCreateUserResults{u1, err}
	mmCreateUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateUser.mock
}

// Set uses given function f to mock the AuthStorage.CreateUser method
func (mmCreateUser *mAuthStorageMockCreateUser) Set(f func(ctx context.Context, email string, passwordHash string) (u1 uint64, err error)) *AuthStorageMock {
	if mmCreateUser.defaultExpectation != nil {
		mmCreateUser.mock.t.Fatalf("Default expectation is already set for the AuthStorage.CreateUser method")
	}

	if len(mmCreateUser.expectations) > 0 {
		mmCreateUser.mock.t.Fatalf("Some expectations are already set for the AuthStorage.CreateUser method")
	}

	mmCreateUser.mock.funcCreateUser = f
	mmCreateUser.mock.funcCreateUserOrigin = minimock.CallerInfo(1)
	return mmCreateUser.mock
}

// When sets expectation for the AuthStorage.CreateUser which will trigger the result defined by the following
// Then helper
func (mmCreateUser *mAuthStorageMockCreateUser) When(ctx context.Context, email string, passwordHash string) *AuthStorageMockCreateUserExpectation {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("AuthStorageMock.CreateUser mock is already set by Set")
	}

	expectation := &AuthStorageMockCreateUserExpectation{
		mock:               mmCreateUser.mock,
		params:             &AuthStorageMockCreateUserParams{ctx, email, passwordHash},
		expectationOrigins: AuthStorageMockCreateUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateUser.expectations = append(mmCreateUser.expectations, expectation)
	return expectation
}

// Then sets up AuthStorage.CreateUser return parameters for the expectation previously defined by the When method
func (e *AuthStorageMockCreateUserExpectation) Then(u1 uint64, err error) *AuthStorageMock {
	e.results = &AuthStorageMockCreateUserResults{u1, err}
	return e.mock
}

// Times sets number of times AuthStorage.CreateUser should be invoked
func (mmCreateUser *mAuthStorageMockCreateUser) Times(n uint64) *mAuthStorageMockCreateUser {
	if n == 0 {
		mmCreateUser.mock.t.Fatalf("Times of AuthStorageMock.CreateUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateUser.expectedInvocations, n)
	mmCreateUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateUser
}

func (mmCreateUser *mAuthStorageMockCreateUser) invocationsDone() bool {
	if len(mmCreateUser.expectations) == 0 && mmCreateUser.defaultExpectation == nil && mmCreateUser.mock.funcCreateUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateUser.mock.afterCreateUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateUser implements mm_auth_service.AuthStorage
func (mmCreateUser *AuthStorageMock) CreateUser(ctx context.Context, email string, passwordHash string) (u1 uint64, err error) {
	mm_atomic.AddUint64(&mmCreateUser.beforeCreateUserCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateUser.afterCreateUserCounter, 1)

	mmCreateUser.t.Helper()

	if mmCreateUser.inspectFuncCreateUser != nil {
		mmCreateUser.inspectFuncCreateUser(ctx, email, passwordHash)
	}

	mm_params := AuthStorageMockCreateUserParams{ctx, email, passwordHash}

	// Record call args
	mmCreateUser.CreateUserMock.mutex.Lock()
	mmCreateUser.CreateUserMock.callArgs = append(mmCreateUser.CreateUserMock.callArgs, &mm_params)
	mmCreateUser.CreateUserMock.mutex.Unlock()

	for _, e := range mmCreateUser.CreateUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.u1, e.results.err
		}
	}

	if mmCreateUser.CreateUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateUser.CreateUserMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateUser.CreateUserMock.defaultExpectation.params
		mm_want_ptrs := mmCreateUser.CreateUserMock.defaultExpectation.paramPtrs

		mm_got := AuthStorageMockCreateUserParams{ctx, email, passwordHash}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateUser.t.Errorf("AuthStorageMock.CreateUser got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateUser.CreateUserMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.email != nil && !minimock.Equal(*mm_want_ptrs.email, mm_got.email) {
				mmCreateUser.t.Errorf("AuthStorageMock.CreateUser got unexpected parameter email, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateUser.CreateUserMock.defaultExpectation.expectationOrigins.originEmail, *mm_want_ptrs.email, mm_got.email, minimock.Diff(*mm_want_ptrs.email, mm_got.email))
			}

			if mm_want_ptrs.passwordHash != nil && !minimock.Equal(*mm_want_ptrs.passwordHash, mm_got.passwordHash) {
				mmCreateUser.t.Errorf("AuthStorageMock.CreateUser got unexpected parameter passwordHash, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateUser.CreateUserMock.defaultExpectation.expectationOrigins.originPasswordHash, *mm_want_ptrs.passwordHash, mm_got.passwordHash, minimock.Diff(*mm_want_ptrs.passwordHash, mm_got.passwordHash))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateUser.t.Errorf("AuthStorageMock.CreateUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateUser.CreateUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateUser.CreateUserMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateUser.t.Fatal("No results are set for the AuthStorageMock.CreateUser")
		}
		return (*mm_results).u1, (*mm_results).err
	}
	if mmCreateUser.funcCreateUser != nil {
		return mmCreateUser.funcCreateUser(ctx, email, passwordHash)
	}
	mmCreateUser.t.Fatalf("Unexpected call to AuthStorageMock.CreateUser. %v %v %v", ctx, email, passwordHash)
	return
}

// CreateUserAfterCounter returns a count of finished AuthStorageMock.CreateUser invocations
func (mmCreateUser *AuthStorageMock) CreateUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateUser.afterCreateUserCounter)
}

// CreateUserBeforeCounter returns a count of AuthStorageMock.CreateUser invocations
func (mmCreateUser *AuthStorageMock) CreateUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateUser.beforeCreateUserCounter)
}

// Calls returns a list of arguments used in each call to AuthStorageMock.CreateUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateUser *mAuthStorageMockCreateUser) Calls() []*AuthStorageMockCreateUserParams {
	mmCreateUser.mutex.RLock()

	argCopy := make([]*AuthStorageMockCreateUserParams, len(mmCreateUser.callArgs))
	copy(argCopy, mmCreateUser.callArgs)

	mmCreateUser.mutex.RUnlock()

	return argCopy
}

// MinimockCreateUserDone returns true if the count of the CreateUser invocations corresponds
// the number of defined expectations
func (m *AuthStorageMock) MinimockCreateUserDone() bool {
	if m.CreateUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateUserMock.invocationsDone()
}

// MinimockCreateUserInspect logs each unmet expectation
func (m *AuthStorageMock) MinimockCreateUserInspect() {
	for _, e := range m.CreateUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthStorageMock.CreateUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateUserCounter := mm_atomic.LoadUint64(&m.afterCreateUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateUserMock.defaultExpectation != nil && afterCreateUserCounter < 1 {
		if m.CreateUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthStorageMock.CreateUser at\n%s", m.CreateUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthStorageMock.CreateUser at\n%s with params: %#v", m.CreateUserMock.defaultExpectation.expectationOrigins.origin, *m.CreateUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateUser != nil && afterCreateUserCounter < 1 {
		m.t.Errorf("Expected call to AuthStorageMock.CreateUser at\n%s", m.funcCreateUserOrigin)
	}

	if !m.CreateUserMock.invocationsDone() && afterCreateUserCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthStorageMock.CreateUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateUserMock.expectedInvocations), m.CreateUserMock.expectedInvocationsOrigin, afterCreateUserCounter)
	}
}

type mAuthStorageMockGetUserByEmail struct {
	optional           bool
	mock               *AuthStorageMock
	defaultExpectation *AuthStorageMockGetUserByEmailExpectation
	expectations       []*AuthStorageMockGetUserByEmailExpectation

	callArgs []*AuthStorageMockGetUserByEmailParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthStorageMockGetUserByEmailExpectation specifies expectation struct of the AuthStorage.GetUserByEmail
type AuthStorageMockGetUserByEmailExpectation struct {
	mock               *AuthStorageMock
	params             *AuthStorageMockGetUserByEmailParams
	paramPtrs          *AuthStorageMockGetUserByEmailParamPtrs
	expectationOrigins AuthStorageMockGetUserByEmailExpectationOrigins
	results            *AuthStorageMockGetUserByEmailResults
	returnOrigin       string
	Counter            uint64
}

// AuthStorageMockGetUserByEmailParams contains parameters of the AuthStorage.GetUserByEmail
type AuthStorageMockGetUserByEmailParams struct {
	ctx   context.Context
	email string
}

// AuthStorageMockGetUserByEmailParamPtrs contains pointers to parameters of the AuthStorage.GetUserByEmail
type AuthStorageMockGetUserByEmailParamPtrs struct {
	ctx   *context.Context
	email *string
}

// AuthStorageMockGetUserByEmailResults contains results of the AuthStorage.GetUserByEmail
type AuthStorageMockGetUserByEmailResults struct {
	up1 *domain.User
	err error
}

// AuthStorageMockGetUserByEmailOrigins contains origins of expectations of the AuthStorage.GetUserByEmail
type AuthStorageMockGetUserByEmailExpectationOrigins struct {
	origin      string
	originCtx   string
	originEmail string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetUserByEmail *mAuthStorageMockGetUserByEmail) Optional() *mAuthStorageMockGetUserByEmail {
	mmGetUserByEmail.optional = true
	return mmGetUserByEmail
}

// Expect sets up expected params for AuthStorage.GetUserByEmail
func (mmGetUserByEmail *mAuthStorageMockGetUserByEmail) Expect(ctx context.Context, email string) *mAuthStorageMockGetUserByEmail {
	if mmGetUserByEmail.mock.funcGetUserByEmail != nil {
		mmGetUserByEmail.mock.t.Fatalf("AuthStorageMock.GetUserByEmail mock is already set by Set")
	}

	if mmGetUserByEmail.defaultExpectation == nil {
		mmGetUserByEmail.defaultExpectation = &AuthStorageMockGetUserByEmailExpectation{}
	}

	if mmGetUserByEmail.defaultExpectation.paramPtrs != nil {
		mmGetUserByEmail.mock.t.Fatalf("AuthStorageMock.GetUserByEmail mock is already set by ExpectParams functions")
	}

	mmGetUserByEmail.defaultExpectation.params = &AuthStorageMockGetUserByEmailParams{ctx, email}
	mmGetUserByEmail.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetUserByEmail.expectations {
		if minimock.Equal(e.params, mmGetUserByEmail.defaultExpectation.params) {
			mmGetUserByEmail.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetUserByEmail.defaultExpectation.params)
		}
	}

	return mmGetUserByEmail
}

// ExpectCtxParam1 sets up expected param ctx for AuthStorage.GetUserByEmail
func (mmGetUserByEmail *mAuthStorageMockGetUserByEmail) ExpectCtxParam1(ctx context.Context) *mAuthStorageMockGetUserByEmail {
	if mmGetUserByEmail.mock.funcGetUserByEmail != nil {
		mmGetUserByEmail.mock.t.Fatalf("AuthStorageMock.GetUserByEmail mock is already set by Set")
	}

	if mmGetUserByEmail.defaultExpectation == nil {
		mmGetUserByEmail.defaultExpectation = &AuthStorageMockGetUserByEmailExpectation{}
	}

	if mmGetUserByEmail.defaultExpectation.params != nil {
		mmGetUserByEmail.mock.t.Fatalf("AuthStorageMock.GetUserByEmail mock is already set by Expect")
	}

	if mmGetUserByEmail.defaultExpectation.paramPtrs == nil {
		mmGetUserByEmail.defaultExpectation.paramPtrs = &AuthStorageMockGetUserByEmailParamPtrs{}
	}
	mmGetUserByEmail.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetUserByEmail.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetUserByEmail
}

// ExpectEmailParam2 sets up expected param email for AuthStorage.GetUserByEmail
func (mmGetUserByEmail *mAuthStorageMockGetUserByEmail) ExpectEmailParam2(email string) *mAuthStorageMockGetUserByEmail {
	if mmGetUserByEmail.mock.funcGetUserByEmail != nil {
		mmGetUserByEmail.mock.t.Fatalf("AuthStorageMock.GetUserByEmail mock is already set by Set")
	}

	if mmGetUserByEmail.defaultExpectation == nil {
		mmGetUserByEmail.defaultExpectation = &AuthStorageMockGetUserByEmailExpectation{}
	}

	if mmGetUserByEmail.defaultExpectation.params != nil {
		mmGetUserByEmail.mock.t.Fatalf("AuthStorageMock.GetUserByEmail mock is already set by Expect")
	}

	if mmGetUserByEmail.defaultExpectation.paramPtrs == nil {
		mmGetUserByEmail.defaultExpectation.paramPtrs = &AuthStorageMockGetUserByEmailParamPtrs{}
	}
	mmGetUserByEmail.defaultExpectation.paramPtrs.email = &email
	mmGetUserByEmail.defaultExpectation.expectationOrigins.originEmail = minimock.CallerInfo(1)

	return mmGetUserByEmail
}

// Inspect accepts an inspector function that has same arguments as the AuthStorage.GetUserByEmail
func (mmGetUserByEmail *mAuthStorageMockGetUserByEmail) Inspect(f func(ctx context.Context, email string)) *mAuthStorageMockGetUserByEmail {
	if mmGetUserByEmail.mock.inspectFuncGetUserByEmail != nil {
		mmGetUserByEmail.mock.t.Fatalf("Inspect function is already set for AuthStorageMock.GetUserByEmail")
	}

	mmGetUserByEmail.mock.inspectFuncGetUserByEmail = f

	return mmGetUserByEmail
}

// Return sets up results that will be returned by AuthStorage.GetUserByEmail
func (mmGetUserByEmail *mAuthStorageMockGetUserByEmail) Return(up1 *domain.User, err error) *AuthStorageMock {
	if mmGetUserByEmail.mock.funcGetUserByEmail != nil {
		mmGetUserByEmail.mock.t.Fatalf("AuthStorageMock.GetUserByEmail mock is already set by Set")
	}

	if mmGetUserByEmail.defaultExpectation == nil {
		mmGetUserByEmail.defaultExpectation = &AuthStorageMockGetUserByEmailExpectation{mock: mmGetUserByEmail.mock}
	}
	mmGetUserByEmail.defaultExpectation.results = &AuthStorageMockGetUserByEmailResults{up1, err}
	mmGetUserByEmail.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetUserByEmail.mock
}

// Set uses given function f to mock the AuthStorage.GetUserByEmail method
func (mmGetUserByEmail *mAuthStorageMockGetUserByEmail) Set(f func(ctx context.Context, email string) (up1 *domain.User, err error)) *AuthStorageMock {
	if mmGetUserByEmail.defaultExpectation != nil {
		mmGetUserByEmail.mock.t.Fatalf("Default expectation is already set for the AuthStorage.GetUserByEmail method")
	}

	if len(mmGetUserByEmail.expectations) > 0 {
		mmGetUserByEmail.mock.t.Fatalf("Some expectations are already set for the AuthStorage.GetUserByEmail method")
	}

	mmGetUserByEmail.mock.funcGetUserByEmail = f
	mmGetUserByEmail.mock.funcGetUserByEmailOrigin = minimock.CallerInfo(1)
	return mmGetUserByEmail.mock
}

// When sets expectation for the AuthStorage.GetUserByEmail which will trigger the result defined by the following
// Then helper
func (mmGetUserByEmail *mAuthStorageMockGetUserByEmail) When(ctx context.Context, email string) *AuthStorageMockGetUserByEmailExpectation {
	if mmGetUserByEmail.mock.funcGetUserByEmail != nil {
		mmGetUserByEmail.mock.t.Fatalf("AuthStorageMock.GetUserByEmail mock is already set by Set")
	}

	expectation := &AuthStorageMockGetUserByEmailExpectation{
		mock:               mmGetUserByEmail.mock,
		params:             &AuthStorageMockGetUserByEmailParams{ctx, email},
		expectationOrigins: AuthStorageMockGetUserByEmailExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetUserByEmail.expectations = append(mmGetUserByEmail.expectations, expectation)
	return expectation
}

// Then sets up AuthStorage.GetUserByEmail return parameters for the expectation previously defined by the When method
func (e *AuthStorageMockGetUserByEmailExpectation) Then(up1 *domain.User, err error) *AuthStorageMock {
	e.results = &AuthStorageMockGetUserByEmailResults{up1, err}
	return e.mock
}

// Times sets number of times AuthStorage.GetUserByEmail should be invoked
func (mmGetUserByEmail *mAuthStorageMockGetUserByEmail) Times(n uint64) *mAuthStorageMockGetUserByEmail {
	if n == 0 {
		mmGetUserByEmail.mock.t.Fatalf("Times of AuthStorageMock.GetUserByEmail mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetUserByEmail.expectedInvocations, n)
	mmGetUserByEmail.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetUserByEmail
}

func (mmGetUserByEmail *mAuthStorageMockGetUserByEmail) invocationsDone() bool {
	if len(mmGetUserByEmail.expectations) == 0 && mmGetUserByEmail.defaultExpectation == nil && mmGetUserByEmail.mock.funcGetUserByEmail == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetUserByEmail.mock.afterGetUserByEmailCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetUserByEmail.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetUserByEmail implements mm_auth_service.AuthStorage
func (mmGetUserByEmail *AuthStorageMock) GetUserByEmail(ctx context.Context, email string) (up1 *domain.User, err error) {
	mm_atomic.AddUint64(&mmGetUserByEmail.beforeGetUserByEmailCounter, 1)
	defer mm_atomic.AddUint64(&mmGetUserByEmail.afterGetUserByEmailCounter, 1)

	mmGetUserByEmail.t.Helper()

	if mmGetUserByEmail.inspectFuncGetUserByEmail != nil {
		mmGetUserByEmail.inspectFuncGetUserByEmail(ctx, email)
	}

	mm_params := AuthStorageMockGetUserByEmailParams{ctx, email}

	// Record call args
	mmGetUserByEmail.GetUserByEmailMock.mutex.Lock()
	mmGetUserByEmail.GetUserByEmailMock.callArgs = append(mmGetUserByEmail.GetUserByEmailMock.callArgs, &mm_params)
	mmGetUserByEmail.GetUserByEmailMock.mutex.Unlock()

	for _, e := range mmGetUserByEmail.GetUserByEmailMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmGetUserByEmail.GetUserByEmailMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetUserByEmail.GetUserByEmailMock.defaultExpectation.Counter, 1)
		mm_want := mmGetUserByEmail.GetUserByEmailMock.defaultExpectation.params
		mm_want_ptrs := mmGetUserByEmail.GetUserByEmailMock.defaultExpectation.paramPtrs

		mm_got := AuthStorageMockGetUserByEmailParams{ctx, email}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetUserByEmail.t.Errorf("AuthStorageMock.GetUserByEmail got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUserByEmail.GetUserByEmailMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.email != nil && !minimock.Equal(*mm_want_ptrs.email, mm_got.email) {
				mmGetUserByEmail.t.Errorf("AuthStorageMock.GetUserByEmail got unexpected parameter email, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUserByEmail.GetUserByEmailMock.defaultExpectation.expectationOrigins.originEmail, *mm_want_ptrs.email, mm_got.email, minimock.Diff(*mm_want_ptrs.email, mm_got.email))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetUserByEmail.t.Errorf("AuthStorageMock.GetUserByEmail got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetUserByEmail.GetUserByEmailMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetUserByEmail.GetUserByEmailMock.defaultExpectation.results
		if mm_results == nil {
			mmGetUserByEmail.t.Fatal("No results are set for the AuthStorageMock.GetUserByEmail")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmGetUserByEmail.funcGetUserByEmail != nil {
		return mmGetUserByEmail.funcGetUserByEmail(ctx, email)
	}
	mmGetUserByEmail.t.Fatalf("Unexpected call to AuthStorageMock.GetUserByEmail. %v %v", ctx, email)
	return
}

// GetUserByEmailAfterCounter returns a count of finished AuthStorageMock.GetUserByEmail invocations
func (mmGetUserByEmail *AuthStorageMock) GetUserByEmailAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUserByEmail.afterGetUserByEmailCounter)
}

// GetUserByEmailBeforeCounter returns a count of AuthStorageMock.GetUserByEmail invocations
func (mmGetUserByEmail *AuthStorageMock) GetUserByEmailBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUserByEmail.beforeGetUserByEmailCounter)
}

// Calls returns a list of arguments used in each call to AuthStorageMock.GetUserByEmail.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetUserByEmail *mAuthStorageMockGetUserByEmail) Calls() []*AuthStorageMockGetUserByEmailParams {
	mmGetUserByEmail.mutex.RLock()

	argCopy := make([]*AuthStorageMockGetUserByEmailParams, len(mmGetUserByEmail.callArgs))
	copy(argCopy, mmGetUserByEmail.callArgs)

	mmGetUserByEmail.mutex.RUnlock()

	return argCopy
}

// MinimockGetUserByEmailDone returns true if the count of the GetUserByEmail invocations corresponds
// the number of defined expectations
func (m *AuthStorageMock) MinimockGetUserByEmailDone() bool {
	if m.GetUserByEmailMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetUserByEmailMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetUserByEmailMock.invocationsDone()
}

// MinimockGetUserByEmailInspect logs each unmet expectation
func (m *AuthStorageMock) MinimockGetUserByEmailInspect() {
	for _, e := range m.GetUserByEmailMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthStorageMock.GetUserByEmail at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetUserByEmailCounter := mm_atomic.LoadUint64(&m.afterGetUserByEmailCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetUserByEmailMock.defaultExpectation != nil && afterGetUserByEmailCounter < 1 {
		if m.GetUserByEmailMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthStorageMock.GetUserByEmail at\n%s", m.GetUserByEmailMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthStorageMock.GetUserByEmail at\n%s with params: %#v", m.GetUserByEmailMock.defaultExpectation.expectationOrigins.origin, *m.GetUserByEmailMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetUserByEmail != nil && afterGetUserByEmailCounter < 1 {
		m.t.Errorf("Expected call to AuthStorageMock.GetUserByEmail at\n%s", m.funcGetUserByEmailOrigin)
	}

	if !m.GetUserByEmailMock.invocationsDone() && afterGetUserByEmailCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthStorageMock.GetUserByEmail at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetUserByEmailMock.expectedInvocations), m.GetUserByEmailMock.expectedInvocationsOrigin, afterGetUserByEmailCounter)
	}
}

type mAuthStorageMockGetUserByID struct {
	optional           bool
	mock               *AuthStorageMock
	defaultExpectation *AuthStorageMockGetUserByIDExpectation
	expectations       []*AuthStorageMockGetUserByIDExpectation

	callArgs []*AuthStorageMockGetUserByIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthStorageMockGetUserByIDExpectation specifies expectation struct of the AuthStorage.GetUserByID
type AuthStorageMockGetUserByIDExpectation struct {
	mock               *AuthStorageMock
	params             *AuthStorageMockGetUserByIDParams
	paramPtrs          *AuthStorageMockGetUserByIDParamPtrs
	expectationOrigins AuthStorageMockGetUserByIDExpectationOrigins
	results            *AuthStorageMockGetUserByIDResults
	returnOrigin       string
	Counter            uint64
}

// AuthStorageMockGetUserByIDParams contains parameters of the AuthStorage.GetUserByID
type AuthStorageMockGetUserByIDParams struct {
	ctx    context.Context
	userID uint64
}

// AuthStorageMockGetUserByIDParamPtrs contains pointers to parameters of the AuthStorage.GetUserByID
type AuthStorageMockGetUserByIDParamPtrs struct {
	ctx    *context.Context
	userID *uint64
}

// AuthStorageMockGetUserByIDResults contains results of the AuthStorage.GetUserByID
type AuthStorageMockGetUserByIDResults struct {
	up1 *domain.User
	err error
}

// AuthStorageMockGetUserByIDOrigins contains origins of expectations of the AuthStorage.GetUserByID
type AuthStorageMockGetUserByIDExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetUserByID *mAuthStorageMockGetUserByID) Optional() *mAuthStorageMockGetUserByID {
	mmGetUserByID.optional = true
	return mmGetUserByID
}

// Expect sets up expected params for AuthStorage.GetUserByID
func (mmGetUserByID *mAuthStorageMockGetUserByID) Expect(ctx context.Context, userID uint64) *mAuthStorageMockGetUserByID {
	if mmGetUserByID.mock.funcGetUserByID != nil {
		mmGetUserByID.mock.t.Fatalf("AuthStorageMock.GetUserByID mock is already set by Set")
	}

	if mmGetUserByID.defaultExpectation == nil {
		mmGetUserByID.defaultExpectation = &AuthStorageMockGetUserByIDExpectation{}
	}

	if mmGetUserByID.defaultExpectation.paramPtrs != nil {
		mmGetUserByID.mock.t.Fatalf("AuthStorageMock.GetUserByID mock is already set by ExpectParams functions")
	}

	mmGetUserByID.defaultExpectation.params = &AuthStorageMockGetUserByIDParams{ctx, userID}
	mmGetUserByID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetUserByID.expectations {
		if minimock.Equal(e.params, mmGetUserByID.defaultExpectation.params) {
			mmGetUserByID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetUserByID.defaultExpectation.params)
		}
	}

	return mmGetUserByID
}

// ExpectCtxParam1 sets up expected param ctx for AuthStorage.GetUserByID
func (mmGetUserByID *mAuthStorageMockGetUserByID) ExpectCtxParam1(ctx context.Context) *mAuthStorageMockGetUserByID {
	if mmGetUserByID.mock.funcGetUserByID != nil {
		mmGetUserByID.mock.t.Fatalf("AuthStorageMock.GetUserByID mock is already set by Set")
	}

	if mmGetUserByID.defaultExpectation == nil {
		mmGetUserByID.defaultExpectation = &AuthStorageMockGetUserByIDExpectation{}
	}

	if mmGetUserByID.defaultExpectation.params != nil {
		mmGetUserByID.mock.t.Fatalf("AuthStorageMock.GetUserByID mock is already set by Expect")
	}

	if mmGetUserByID.defaultExpectation.paramPtrs == nil {
		mmGetUserByID.defaultExpectation.paramPtrs = &AuthStorageMockGetUserByIDParamPtrs{}
	}
	mmGetUserByID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetUserByID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetUserByID
}

// ExpectUserIDParam2 sets up expected param userID for AuthStorage.GetUserByID
func (mmGetUserByID *mAuthStorageMockGetUserByID) ExpectUserIDParam2(userID uint64) *mAuthStorageMockGetUserByID {
	if mmGetUserByID.mock.funcGetUserByID != nil {
		mmGetUserByID.mock.t.Fatalf("AuthStorageMock.GetUserByID mock is already set by Set")
	}

	if mmGetUserByID.defaultExpectation == nil {
		mmGetUserByID.defaultExpectation = &AuthStorageMockGetUserByIDExpectation{}
	}

	if mmGetUserByID.defaultExpectation.params != nil {
		mmGetUserByID.mock.t.Fatalf("AuthStorageMock.GetUserByID mock is already set by Expect")
	}

	if mmGetUserByID.defaultExpectation.paramPtrs == nil {
		mmGetUserByID.defaultExpectation.paramPtrs = &AuthStorageMockGetUserByIDParamPtrs{}
	}
	mmGetUserByID.defaultExpectation.paramPtrs.userID = &userID
	mmGetUserByID.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmGetUserByID
}

// Inspect accepts an inspector function that has same arguments as the AuthStorage.GetUserByID
func (mmGetUserByID *mAuthStorageMockGetUserByID) Inspect(f func(ctx context.Context, userID uint64)) *mAuthStorageMockGetUserByID {
	if mmGetUserByID.mock.inspectFuncGetUserByID != nil {
		mmGetUserByID.mock.t.Fatalf("Inspect function is already set for AuthStorageMock.GetUserByID")
	}

	mmGetUserByID.mock.inspectFuncGetUserByID = f

	return mmGetUserByID
}

// Return sets up results that will be returned by AuthStorage.GetUserByID
func (mmGetUserByID *mAuthStorageMockGetUserByID) Return(up1 *domain.User, err error) *AuthStorageMock {
	if mmGetUserByID.mock.funcGetUserByID != nil {
		mmGetUserByID.mock.t.Fatalf("AuthStorageMock.GetUserByID mock is already set by Set")
	}

	if mmGetUserByID.defaultExpectation == nil {
		mmGetUserByID.defaultExpectation = &AuthStorageMockGetUserByIDExpectation{mock: mmGetUserByID.mock}
	}
	mmGetUserByID.defaultExpectation.results = &AuthStorageMockGetUserByIDResults{up1, err}
	mmGetUserByID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetUserByID.mock
}

// Set uses given function f to mock the AuthStorage.GetUserByID method
func (mmGetUserByID *mAuthStorageMockGetUserByID) Set(f func(ctx context.Context, userID uint64) (up1 *domain.User, err error)) *AuthStorageMock {
	if mmGetUserByID.defaultExpectation != nil {
		mmGetUserByID.mock.t.Fatalf("Default expectation is already set for the AuthStorage.GetUserByID method")
	}

	if len(mmGetUserByID.expectations) > 0 {
		mmGetUserByID.mock.t.Fatalf("Some expectations are already set for the AuthStorage.GetUserByID method")
	}

	mmGetUserByID.mock.funcGetUserByID = f
	mmGetUserByID.mock.funcGetUserByIDOrigin = minimock.CallerInfo(1)
	return mmGetUserByID.mock
}

// When sets expectation for the AuthStorage.GetUserByID which will trigger the result defined by the following
// Then helper
func (mmGetUserByID *mAuthStorageMockGetUserByID) When(ctx context.Context, userID uint64) *AuthStorageMockGetUserByIDExpectation {
	if mmGetUserByID.mock.funcGetUserByID != nil {
		mmGetUserByID.mock.t.Fatalf("AuthStorageMock.GetUserByID mock is already set by Set")
	}

	expectation := &AuthStorageMockGetUserByIDExpectation{
		mock:               mmGetUserByID.mock,
		params:             &AuthStorageMockGetUserByIDParams{ctx, userID},
		expectationOrigins: AuthStorageMockGetUserByIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetUserByID.expectations = append(mmGetUserByID.expectations, expectation)
	return expectation
}

// Then sets up AuthStorage.GetUserByID return parameters for the expectation previously defined by the When method
func (e *AuthStorageMockGetUserByIDExpectation) Then(up1 *domain.User, err error) *AuthStorageMock {
	e.results = &AuthStorageMockGetUserByIDResults{up1, err}
	return e.mock
}

// Times sets number of times AuthStorage.GetUserByID should be invoked
func (mmGetUserByID *mAuthStorageMockGetUserByID) Times(n uint64) *mAuthStorageMockGetUserByID {
	if n == 0 {
		mmGetUserByID.mock.t.Fatalf("Times of AuthStorageMock.GetUserByID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetUserByID.expectedInvocations, n)
	mmGetUserByID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetUserByID
}

func (mmGetUserByID *mAuthStorageMockGetUserByID) invocationsDone() bool {
	if len(mmGetUserByID.expectations) == 0 && mmGetUserByID.defaultExpectation == nil && mmGetUserByID.mock.funcGetUserByID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetUserByID.mock.afterGetUserByIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetUserByID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetUserByID implements mm_auth_service.AuthStorage
func (mmGetUserByID *AuthStorageMock) GetUserByID(ctx context.Context, userID uint64) (up1 *domain.User, err error) {
	mm_atomic.AddUint64(&mmGetUserByID.beforeGetUserByIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetUserByID.afterGetUserByIDCounter, 1)

	mmGetUserByID.t.Helper()

	if mmGetUserByID.inspectFuncGetUserByID != nil {
		mmGetUserByID.inspectFuncGetUserByID(ctx, userID)
	}

	mm_params := AuthStorageMockGetUserByIDParams{ctx, userID}

	// Record call args
	mmGetUserByID.GetUserByIDMock.mutex.Lock()
	mmGetUserByID.GetUserByIDMock.callArgs = append(mmGetUserByID.GetUserByIDMock.callArgs, &mm_params)
	mmGetUserByID.GetUserByIDMock.mutex.Unlock()

	for _, e := range mmGetUserByID.GetUserByIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmGetUserByID.GetUserByIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetUserByID.GetUserByIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetUserByID.GetUserByIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetUserByID.GetUserByIDMock.defaultExpectation.paramPtrs

		mm_got := AuthStorageMockGetUserByIDParams{ctx, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetUserByID.t.Errorf("AuthStorageMock.GetUserByID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUserByID.GetUserByIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmGetUserByID.t.Errorf("AuthStorageMock.GetUserByID got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUserByID.GetUserByIDMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetUserByID.t.Errorf("AuthStorageMock.GetUserByID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetUserByID.GetUserByIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetUserByID.GetUserByIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetUserByID.t.Fatal("No results are set for the AuthStorageMock.GetUserByID")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmGetUserByID.funcGetUserByID != nil {
		return mmGetUserByID.funcGetUserByID(ctx, userID)
	}
	mmGetUserByID.t.Fatalf("Unexpected call to AuthStorageMock.GetUserByID. %v %v", ctx, userID)
	return
}

// GetUserByIDAfterCounter returns a count of finished AuthStorageMock.GetUserByID invocations
func (mmGetUserByID *AuthStorageMock) GetUserByIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUserByID.afterGetUserByIDCounter)
}

// GetUserByIDBeforeCounter returns a count of AuthStorageMock.GetUserByID invocations
func (mmGetUserByID *AuthStorageMock) GetUserByIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUserByID.beforeGetUserByIDCounter)
}

// Calls returns a list of arguments used in each call to AuthStorageMock.GetUserByID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetUserByID *mAuthStorageMockGetUserByID) Calls() []*AuthStorageMockGetUserByIDParams {
	mmGetUserByID.mutex.RLock()

	argCopy := make([]*AuthStorageMockGetUserByIDParams, len(mmGetUserByID.callArgs))
	copy(argCopy, mmGetUserByID.callArgs)

	mmGetUserByID.mutex.RUnlock()

	return argCopy
}

// MinimockGetUserByIDDone returns true if the count of the GetUserByID invocations corresponds
// the number of defined expectations
func (m *AuthStorageMock) MinimockGetUserByIDDone() bool {
	if m.GetUserByIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetUserByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetUserByIDMock.invocationsDone()
}

// MinimockGetUserByIDInspect logs each unmet expectation
func (m *AuthStorageMock) MinimockGetUserByIDInspect() {
	for _, e := range m.GetUserByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthStorageMock.GetUserByID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetUserByIDCounter := mm_atomic.LoadUint64(&m.afterGetUserByIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetUserByIDMock.defaultExpectation != nil && afterGetUserByIDCounter < 1 {
		if m.GetUserByIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthStorageMock.GetUserByID at\n%s", m.GetUserByIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthStorageMock.GetUserByID at\n%s with params: %#v", m.GetUserByIDMock.defaultExpectation.expectationOrigins.origin, *m.GetUserByIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetUserByID != nil && afterGetUserByIDCounter < 1 {
		m.t.Errorf("Expected call to AuthStorageMock.GetUserByID at\n%s", m.funcGetUserByIDOrigin)
	}

	if !m.GetUserByIDMock.invocationsDone() && afterGetUserByIDCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthStorageMock.GetUserByID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetUserByIDMock.expectedInvocations), m.GetUserByIDMock.expectedInvocationsOrigin, afterGetUserByIDCounter)
	}
}

type mAuthStorageMockUpdateUserRole struct {
	optional           bool
	mock               *AuthStorageMock
	defaultExpectation *AuthStorageMockUpdateUserRoleExpectation
	expectations       []*AuthStorageMockUpdateUserRoleExpectation

	callArgs []*AuthStorageMockUpdateUserRoleParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthStorageMockUpdateUserRoleExpectation specifies expectation struct of the AuthStorage.UpdateUserRole
type AuthStorageMockUpdateUserRoleExpectation struct {
	mock               *AuthStorageMock
	params             *AuthStorageMockUpdateUserRoleParams
	paramPtrs          *AuthStorageMockUpdateUserRoleParamPtrs
	expectationOrigins AuthStorageMockUpdateUserRoleExpectationOrigins
	results            *AuthStorageMockUpdateUserRoleResults
	returnOrigin       string
	Counter            uint64
}

// AuthStorageMockUpdateUserRoleParams contains parameters of the AuthStorage.UpdateUserRole
type AuthStorageMockUpdateUserRoleParams struct {
	ctx    context.Context
	userID uint64
	role   string
}

// AuthStorageMockUpdateUserRoleParamPtrs contains pointers to parameters of the AuthStorage.UpdateUserRole
type AuthStorageMockUpdateUserRoleParamPtrs struct {
	ctx    *context.Context
	userID *uint64
	role   *string
}

// AuthStorageMockUpdateUserRoleResults contains results of the AuthStorage.UpdateUserRole
type AuthStorageMockUpdateUserRoleResults struct {
	err error
}

// AuthStorageMockUpdateUserRoleOrigins contains origins of expectations of the AuthStorage.UpdateUserRole
type AuthStorageMockUpdateUserRoleExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
	originRole   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdateUserRole *mAuthStorageMockUpdateUserRole) Optional() *mAuthStorageMockUpdateUserRole {
	mmUpdateUserRole.optional = true
	return mmUpdateUserRole
}

// Expect sets up expected params for AuthStorage.UpdateUserRole
func (mmUpdateUserRole *mAuthStorageMockUpdateUserRole) Expect(ctx context.Context, userID uint64, role string) *mAuthStorageMockUpdateUserRole {
	if mmUpdateUserRole.mock.funcUpdateUserRole != nil {
		mmUpdateUserRole.mock.t.Fatalf("AuthStorageMock.UpdateUserRole mock is already set by Set")
	}

	if mmUpdateUserRole.defaultExpectation == nil {
		mmUpdateUserRole.defaultExpectation = &AuthStorageMockUpdateUserRoleExpectation{}
	}

	if mmUpdateUserRole.defaultExpectation.paramPtrs != nil {
		mmUpdateUserRole.mock.t.Fatalf("AuthStorageMock.UpdateUserRole mock is already set by ExpectParams functions")
	}

	mmUpdateUserRole.defaultExpectation.params = &AuthStorageMockUpdateUserRoleParams{ctx, userID, role}
	mmUpdateUserRole.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUpdateUserRole.expectations {
		if minimock.Equal(e.params, mmUpdateUserRole.defaultExpectation.params) {
			mmUpdateUserRole.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdateUserRole.defaultExpectation.params)
		}
	}

	return mmUpdateUserRole
}

// ExpectCtxParam1 sets up expected param ctx for AuthStorage.UpdateUserRole
func (mmUpdateUserRole *mAuthStorageMockUpdateUserRole) ExpectCtxParam1(ctx context.Context) *mAuthStorageMockUpdateUserRole {
	if mmUpdateUserRole.mock.funcUpdateUserRole != nil {
		mmUpdateUserRole.mock.t.Fatalf("AuthStorageMock.UpdateUserRole mock is already set by Set")
	}

	if mmUpdateUserRole.defaultExpectation == nil {
		mmUpdateUserRole.defaultExpectation = &AuthStorageMockUpdateUserRoleExpectation{}
	}

	if mmUpdateUserRole.defaultExpectation.params != nil {
		mmUpdateUserRole.mock.t.Fatalf("AuthStorageMock.UpdateUserRole mock is already set by Expect")
	}

	if mmUpdateUserRole.defaultExpectation.paramPtrs == nil {
		mmUpdateUserRole.defaultExpectation.paramPtrs = &AuthStorageMockUpdateUserRoleParamPtrs{}
	}
	mmUpdateUserRole.defaultExpectation.paramPtrs.ctx = &ctx
	mmUpdateUserRole.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUpdateUserRole
}

// ExpectUserIDParam2 sets up expected param userID for AuthStorage.UpdateUserRole
func (mmUpdateUserRole *mAuthStorageMockUpdateUserRole) ExpectUserIDParam2(userID uint64) *mAuthStorageMockUpdateUserRole {
	if mmUpdateUserRole.mock.funcUpdateUserRole != nil {
		mmUpdateUserRole.mock.t.Fatalf("AuthStorageMock.UpdateUserRole mock is already set by Set")
	}

	if mmUpdateUserRole.defaultExpectation == nil {
		mmUpdateUserRole.defaultExpectation = &AuthStorageMockUpdateUserRoleExpectation{}
	}

	if mmUpdateUserRole.defaultExpectation.params != nil {
		mmUpdateUserRole.mock.t.Fatalf("AuthStorageMock.UpdateUserRole mock is already set by Expect")
	}

	if mmUpdateUserRole.defaultExpectation.paramPtrs == nil {
		mmUpdateUserRole.defaultExpectation.paramPtrs = &AuthStorageMockUpdateUserRoleParamPtrs{}
	}
	mmUpdateUserRole.defaultExpectation.paramPtrs.userID = &userID
	mmUpdateUserRole.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmUpdateUserRole
}

// ExpectRoleParam3 sets up expected param role for AuthStorage.UpdateUserRole
func (mmUpdateUserRole *mAuthStorageMockUpdateUserRole) ExpectRoleParam3(role string) *mAuthStorageMockUpdateUserRole {
	if mmUpdateUserRole.mock.funcUpdateUserRole != nil {
		mmUpdateUserRole.mock.t.Fatalf("AuthStorageMock.UpdateUserRole mock is already set by Set")
	}

	if mmUpdateUserRole.defaultExpectation == nil {
		mmUpdateUserRole.defaultExpectation = &AuthStorageMockUpdateUserRoleExpectation{}
	}

	if mmUpdateUserRole.defaultExpectation.params != nil {
		mmUpdateUserRole.mock.t.Fatalf("AuthStorageMock.UpdateUserRole mock is already set by Expect")
	}

	if mmUpdateUserRole.defaultExpectation.paramPtrs == nil {
		mmUpdateUserRole.defaultExpectation.paramPtrs = &AuthStorageMockUpdateUserRoleParamPtrs{}
	}
	mmUpdateUserRole.defaultExpectation.paramPtrs.role = &role
	mmUpdateUserRole.defaultExpectation.expectationOrigins.originRole = minimock.CallerInfo(1)

	return mmUpdateUserRole
}

// Inspect accepts an inspector function that has same arguments as the AuthStorage.UpdateUserRole
func (mmUpdateUserRole *mAuthStorageMockUpdateUserRole) Inspect(f func(ctx context.Context, userID uint64, role string)) *mAuthStorageMockUpdateUserRole {
	if mmUpdateUserRole.mock.inspectFuncUpdateUserRole != nil {
		mmUpdateUserRole.mock.t.Fatalf("Inspect function is already set for AuthStorageMock.UpdateUserRole")
	}

	mmUpdateUserRole.mock.inspectFuncUpdateUserRole = f

	return mmUpdateUserRole
}

// Return sets up results that will be returned by AuthStorage.UpdateUserRole
func (mmUpdateUserRole *mAuthStorageMockUpdateUserRole) Return(err error) *AuthStorageMock {
	if mmUpdateUserRole.mock.funcUpdateUserRole != nil {
		mmUpdateUserRole.mock.t.Fatalf("AuthStorageMock.UpdateUserRole mock is already set by Set")
	}

	if mmUpdateUserRole.defaultExpectation == nil {
		mmUpdateUserRole.defaultExpectation = &AuthStorageMockUpdateUserRoleExpectation{mock: mmUpdateUserRole.mock}
	}
	mmUpdateUserRole.defaultExpectation.results = &AuthStorageMockUpdateUserRoleResults{err}
	mmUpdateUserRole.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpdateUserRole.mock
}

// Set uses given function f to mock the AuthStorage.UpdateUserRole method
func (mmUpdateUserRole *mAuthStorageMockUpdateUserRole) Set(f func(ctx context.Context, userID uint64, role string) (err error)) *AuthStorageMock {
	if mmUpdateUserRole.defaultExpectation != nil {
		mmUpdateUserRole.mock.t.Fatalf("Default expectation is already set for the AuthStorage.UpdateUserRole method")
	}

	if len(mmUpdateUserRole.expectations) > 0 {
		mmUpdateUserRole.mock.t.Fatalf("Some expectations are already set for the AuthStorage.UpdateUserRole method")
	}

	mmUpdateUserRole.mock.funcUpdateUserRole = f
	mmUpdateUserRole.mock.funcUpdateUserRoleOrigin = minimock.CallerInfo(1)
	return mmUpdateUserRole.mock
}

// When sets expectation for the AuthStorage.UpdateUserRole which will trigger the result defined by the following
// Then helper
func (mmUpdateUserRole *mAuthStorageMockUpdateUserRole) When(ctx context.Context, userID uint64, role string) *AuthStorageMockUpdateUserRoleExpectation {
	if mmUpdateUserRole.mock.funcUpdateUserRole != nil {
		mmUpdateUserRole.mock.t.Fatalf("AuthStorageMock.UpdateUserRole mock is already set by Set")
	}

	expectation := &AuthStorageMockUpdateUserRoleExpectation{
		mock:               mmUpdateUserRole.mock,
		params:             &AuthStorageMockUpdateUserRoleParams{ctx, userID, role},
		expectationOrigins: AuthStorageMockUpdateUserRoleExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUpdateUserRole.expectations = append(mmUpdateUserRole.expectations, expectation)
	return expectation
}

// Then sets up AuthStorage.UpdateUserRole return parameters for the expectation previously defined by the When method
func (e *AuthStorageMockUpdateUserRoleExpectation) Then(err error) *AuthStorageMock {
	e.results = &AuthStorageMockUpdateUserRoleResults{err}
	return e.mock
}

// Times sets number of times AuthStorage.UpdateUserRole should be invoked
func (mmUpdateUserRole *mAuthStorageMockUpdateUserRole) Times(n uint64) *mAuthStorageMockUpdateUserRole {
	if n == 0 {
		mmUpdateUserRole.mock.t.Fatalf("Times of AuthStorageMock.UpdateUserRole mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdateUserRole.expectedInvocations, n)
	mmUpdateUserRole.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpdateUserRole
}

func (mmUpdateUserRole *mAuthStorageMockUpdateUserRole) invocationsDone() bool {
	if len(mmUpdateUserRole.expectations) == 0 && mmUpdateUserRole.defaultExpectation == nil && mmUpdateUserRole.mock.funcUpdateUserRole == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdateUserRole.mock.afterUpdateUserRoleCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdateUserRole.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// UpdateUserRole implements mm_auth_service.AuthStorage
func (mmUpdateUserRole *AuthStorageMock) UpdateUserRole(ctx context.Context, userID uint64, role string) (err error) {
	mm_atomic.AddUint64(&mmUpdateUserRole.beforeUpdateUserRoleCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdateUserRole.afterUpdateUserRoleCounter, 1)

	mmUpdateUserRole.t.Helper()

	if mmUpdateUserRole.inspectFuncUpdateUserRole != nil {
		mmUpdateUserRole.inspectFuncUpdateUserRole(ctx, userID, role)
	}

	mm_params := AuthStorageMockUpdateUserRoleParams{ctx, userID, role}

	// Record call args
	mmUpdateUserRole.UpdateUserRoleMock.mutex.Lock()
	mmUpdateUserRole.UpdateUserRoleMock.callArgs = append(mmUpdateUserRole.UpdateUserRoleMock.callArgs, &mm_params)
	mmUpdateUserRole.UpdateUserRoleMock.mutex.Unlock()

	for _, e := range mmUpdateUserRole.UpdateUserRoleMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmUpdateUserRole.UpdateUserRoleMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdateUserRole.UpdateUserRoleMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdateUserRole.UpdateUserRoleMock.defaultExpectation.params
		mm_want_ptrs := mmUpdateUserRole.UpdateUserRoleMock.defaultExpectation.paramPtrs

		mm_got := AuthStorageMockUpdateUserRoleParams{ctx, userID, role}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUpdateUserRole.t.Errorf("AuthStorageMock.UpdateUserRole got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateUserRole.UpdateUserRoleMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmUpdateUserRole.t.Errorf("AuthStorageMock.UpdateUserRole got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateUserRole.UpdateUserRoleMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.role != nil && !minimock.Equal(*mm_want_ptrs.role, mm_got.role) {
				mmUpdateUserRole.t.Errorf("AuthStorageMock.UpdateUserRole got unexpected parameter role, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateUserRole.UpdateUserRoleMock.defaultExpectation.expectationOrigins.originRole, *mm_want_ptrs.role, mm_got.role, minimock.Diff(*mm_want_ptrs.role, mm_got.role))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdateUserRole.t.Errorf("AuthStorageMock.UpdateUserRole got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUpdateUserRole.UpdateUserRoleMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdateUserRole.UpdateUserRoleMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdateUserRole.t.Fatal("No results are set for the AuthStorageMock.UpdateUserRole")
		}
		return (*mm_results).err
	}
	if mmUpdateUserRole.funcUpdateUserRole != nil {
		return mmUpdateUserRole.funcUpdateUserRole(ctx, userID, role)
	}
	mmUpdateUserRole.t.Fatalf("Unexpected call to AuthStorageMock.UpdateUserRole. %v %v %v", ctx, userID, role)
	return
}

// UpdateUserRoleAfterCounter returns a count of finished AuthStorageMock.UpdateUserRole invocations
func (mmUpdateUserRole *AuthStorageMock) UpdateUserRoleAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateUserRole.afterUpdateUserRoleCounter)
}

// UpdateUserRoleBeforeCounter returns a count of AuthStorageMock.UpdateUserRole invocations
func (mmUpdateUserRole *AuthStorageMock) UpdateUserRoleBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateUserRole.beforeUpdateUserRoleCounter)
}

// Calls returns a list of arguments used in each call to AuthStorageMock.UpdateUserRole.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdateUserRole *mAuthStorageMockUpdateUserRole) Calls() []*AuthStorageMockUpdateUserRoleParams {
	mmUpdateUserRole.mutex.RLock()

	argCopy := make([]*AuthStorageMockUpdateUserRoleParams, len(mmUpdateUserRole.callArgs))
	copy(argCopy, mmUpdateUserRole.callArgs)

	mmUpdateUserRole.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateUserRoleDone returns true if the count of the UpdateUserRole invocations corresponds
// the number of defined expectations
func (m *AuthStorageMock) MinimockUpdateUserRoleDone() bool {
	if m.UpdateUserRoleMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdateUserRoleMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdateUserRoleMock.invocationsDone()
}

// MinimockUpdateUserRoleInspect logs each unmet expectation
func (m *AuthStorageMock) MinimockUpdateUserRoleInspect() {
	for _, e := range m.UpdateUserRoleMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthStorageMock.UpdateUserRole at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUpdateUserRoleCounter := mm_atomic.LoadUint64(&m.afterUpdateUserRoleCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateUserRoleMock.defaultExpectation != nil && afterUpdateUserRoleCounter < 1 {
		if m.UpdateUserRoleMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthStorageMock.UpdateUserRole at\n%s", m.UpdateUserRoleMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthStorageMock.UpdateUserRole at\n%s with params: %#v", m.UpdateUserRoleMock.defaultExpectation.expectationOrigins.origin, *m.UpdateUserRoleMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdateUserRole != nil && afterUpdateUserRoleCounter < 1 {
		m.t.Errorf("Expected call to AuthStorageMock.UpdateUserRole at\n%s", m.funcUpdateUserRoleOrigin)
	}

	if !m.UpdateUserRoleMock.invocationsDone() && afterUpdateUserRoleCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthStorageMock.UpdateUserRole at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpdateUserRoleMock.expectedInvocations), m.UpdateUserRoleMock.expectedInvocationsOrigin, afterUpdateUserRoleCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AuthStorageMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateUserInspect()

			m.MinimockGetUserByEmailInspect()

			m.MinimockGetUserByIDInspect()

			m.MinimockUpdateUserRoleInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AuthStorageMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AuthStorageMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateUserDone() &&
		m.MinimockGetUserByEmailDone() &&
		m.MinimockGetUserByIDDone() &&
		m.MinimockUpdateUserRoleDone()
}
