// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// RoleClassifierMock implements mm_usecase.RoleClassifier
type RoleClassifierMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcClassify          func(ctx context.Context, title string, description string) (s1 string, err error)
	funcClassifyOrigin    string
	inspectFuncClassify   func(ctx context.Context, title string, description string)
	afterClassifyCounter  uint64
	beforeClassifyCounter uint64
	ClassifyMock          mRoleClassifierMockClassify
}

// NewRoleClassifierMock returns a mock for mm_usecase.RoleClassifier
func NewRoleClassifierMock(t minimock.Tester) *RoleClassifierMock {
	m := &RoleClassifierMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ClassifyMock = mRoleClassifierMockClassify{mock: m}
	m.ClassifyMock.callArgs = []*RoleClassifierMockClassifyParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mRoleClassifierMockClassify struct {
	optional           bool
	mock               *RoleClassifierMock
	defaultExpectation *RoleClassifierMockClassifyExpectation
	expectations       []*RoleClassifierMockClassifyExpectation

	callArgs []*RoleClassifierMockClassifyParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RoleClassifierMockClassifyExpectation specifies expectation struct of the RoleClassifier.Classify
type RoleClassifierMockClassifyExpectation struct {
	mock               *RoleClassifierMock
	params             *RoleClassifierMockClassifyParams
	paramPtrs          *RoleClassifierMockClassifyParamPtrs
	expectationOrigins RoleClassifierMockClassifyExpectationOrigins
	results            *RoleClassifierMockClassifyResults
	returnOrigin       string
	Counter            uint64
}

// RoleClassifierMockClassifyParams contains parameters of the RoleClassifier.Classify
type RoleClassifierMockClassifyParams struct {
	ctx         context.Context
	title       string
	description string
}

// RoleClassifierMockClassifyParamPtrs contains pointers to parameters of the RoleClassifier.Classify
type RoleClassifierMockClassifyParamPtrs struct {
	ctx         *context.Context
	title       *string
	description *string
}

// RoleClassifierMockClassifyResults contains results of the RoleClassifier.Classify
type RoleClassifierMockClassifyResults struct {
	s1  string
	err error
}

// RoleClassifierMockClassifyOrigins contains origins of expectations of the RoleClassifier.Classify
type RoleClassifierMockClassifyExpectationOrigins struct {
	origin            string
	originCtx         string
	originTitle       string
	originDescription string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmClassify *mRoleClassifierMockClassify) Optional() *mRoleClassifierMockClassify {
	mmClassify.optional = true
	return mmClassify
}

// Expect sets up expected params for RoleClassifier.Classify
func (mmClassify *mRoleClassifierMockClassify) Expect(ctx context.Context, title string, description string) *mRoleClassifierMockClassify {
	if mmClassify.mock.funcClassify != nil {
		mmClassify.mock.t.Fatalf("RoleClassifierMock.Classify mock is already set by Set")
	}

	if mmClassify.defaultExpectation == nil {
		mmClassify.defaultExpectation = &RoleClassifierMockClassifyExpectation{}
	}

	if mmClassify.defaultExpectation.paramPtrs != nil {
		mmClassify.mock.t.Fatalf("RoleClassifierMock.Classify mock is already set by ExpectParams functions")
	}

	mmClassify.defaultExpectation.params = &RoleClassifierMockClassifyParams{ctx, title, description}
	mmClassify.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmClassify.expectations {
		if minimock.Equal(e.params, mmClassify.defaultExpectation.params) {
			mmClassify.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmClassify.defaultExpectation.params)
		}
	}

	return mmClassify
}

// ExpectCtxParam1 sets up expected param ctx for RoleClassifier.Classify
func (mmClassify *mRoleClassifierMockClassify) ExpectCtxParam1(ctx context.Context) *mRoleClassifierMockClassify {
	if mmClassify.mock.funcClassify != nil {
		mmClassify.mock.t.Fatalf("RoleClassifierMock.Classify mock is already set by Set")
	}

	if mmClassify.defaultExpectation == nil {
		mmClassify.defaultExpectation = &RoleClassifierMockClassifyExpectation{}
	}

	if mmClassify.defaultExpectation.params != nil {
		mmClassify.mock.t.Fatalf("RoleClassifierMock.Classify mock is already set by Expect")
	}

	if mmClassify.defaultExpectation.paramPtrs == nil {
		mmClassify.defaultExpectation.paramPtrs = &RoleClassifierMockClassifyParamPtrs{}
	}
	mmClassify.defaultExpectation.paramPtrs.ctx = &ctx
	mmClassify.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmClassify
}

// ExpectTitleParam2 sets up expected param title for RoleClassifier.Classify
func (mmClassify *mRoleClassifierMockClassify) ExpectTitleParam2(title string) *mRoleClassifierMockClassify {
	if mmClassify.mock.funcClassify != nil {
		mmClassify.mock.t.Fatalf("RoleClassifierMock.Classify mock is already set by Set")
	}

	if mmClassify.defaultExpectation == nil {
		mmClassify.defaultExpectation = &RoleClassifierMockClassifyExpectation{}
	}

	if mmClassify.defaultExpectation.params != nil {
		mmClassify.mock.t.Fatalf("RoleClassifierMock.Classify mock is already set by Expect")
	}

	if mmClassify.defaultExpectation.paramPtrs == nil {
		mmClassify.defaultExpectation.paramPtrs = &RoleClassifierMockClassifyParamPtrs{}
	}
	mmClassify.defaultExpectation.paramPtrs.title = &title
	mmClassify.defaultExpectation.expectationOrigins.originTitle = minimock.CallerInfo(1)

	return mmClassify
}

// ExpectDescriptionParam3 sets up expected param description for RoleClassifier.Classify
func (mmClassify *mRoleClassifierMockClassify) ExpectDescriptionParam3(description string) *mRoleClassifierMockClassify {
	if mmClassify.mock.funcClassify != nil {
		mmClassify.mock.t.Fatalf("RoleClassifierMock.Classify mock is already set by Set")
	}

	if mmClassify.defaultExpectation == nil {
		mmClassify.defaultExpectation = &RoleClassifierMockClassifyExpectation{}
	}

	if mmClassify.defaultExpectation.params != nil {
		mmClassify.mock.t.Fatalf("RoleClassifierMock.Classify mock is already set by Expect")
	}

	if mmClassify.defaultExpectation.paramPtrs == nil {
		mmClassify.defaultExpectation.paramPtrs = &RoleClassifierMockClassifyParamPtrs{}
	}
	mmClassify.defaultExpectation.paramPtrs.description = &description
	mmClassify.defaultExpectation.expectationOrigins.originDescription = minimock.CallerInfo(1)

	return mmClassify
}

// Inspect accepts an inspector function that has same arguments as the RoleClassifier.Classify
func (mmClassify *mRoleClassifierMockClassify) Inspect(f func(ctx context.Context, title string, description string)) *mRoleClassifierMockClassify {
	if mmClassify.mock.inspectFuncClassify != nil {
		mmClassify.mock.t.Fatalf("Inspect function is already set for RoleClassifierMock.Classify")
	}

	mmClassify.mock.inspectFuncClassify = f

	return mmClassify
}

// Return sets up results that will be returned by RoleClassifier.Classify
func (mmClassify *mRoleClassifierMockClassify) Return(s1 string, err error) *RoleClassifierMock {
	if mmClassify.mock.funcClassify != nil {
		mmClassify.mock.t.Fatalf("RoleClassifierMock.Classify mock is already set by Set")
	}

	if mmClassify.defaultExpectation == nil {
		mmClassify.defaultExpectation = &RoleClassifierMockClassifyExpectation{mock: mmClassify.mock}
	}
	mmClassify.defaultExpectation.results = &RoleClassifierMockClassifyResults{s1, err}
	mmClassify.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmClassify.mock
}

// Set uses given function f to mock the RoleClassifier.Classify method
func (mmClassify *mRoleClassifierMockClassify) Set(f func(ctx context.Context, title string, description string) (s1 string, err error)) *RoleClassifierMock {
	if mmClassify.defaultExpectation != nil {
		mmClassify.mock.t.Fatalf("Default expectation is already set for the RoleClassifier.Classify method")
	}

	if len(mmClassify.expectations) > 0 {
		mmClassify.mock.t.Fatalf("Some expectations are already set for the RoleClassifier.Classify method")
	}

	mmClassify.mock.funcClassify = f
	mmClassify.mock.funcClassifyOrigin = minimock.CallerInfo(1)
	return mmClassify.mock
}

// When sets expectation for the RoleClassifier.Classify which will trigger the result defined by the following
// Then helper
func (mmClassify *mRoleClassifierMockClassify) When(ctx context.Context, title string, description string) *RoleClassifierMockClassifyExpectation {
	if mmClassify.mock.funcClassify != nil {
		mmClassify.mock.t.Fatalf("RoleClassifierMock.Classify mock is already set by Set")
	}

	expectation := &RoleClassifierMockClassifyExpectation{
		mock:               mmClassify.mock,
		params:             &RoleClassifierMockClassifyParams{ctx, title, description},
		expectationOrigins: RoleClassifierMockClassifyExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmClassify.expectations = append(mmClassify.expectations, expectation)
	return expectation
}

// Then sets up RoleClassifier.Classify return parameters for the expectation previously defined by the When method
func (e *RoleClassifierMockClassifyExpectation) Then(s1 string, err error) *RoleClassifierMock {
	e.results = &RoleClassifierMockClassifyResults{s1, err}
	return e.mock
}

// Times sets number of times RoleClassifier.Classify should be invoked
func (mmClassify *mRoleClassifierMockClassify) Times(n uint64) *mRoleClassifierMockClassify {
	if n == 0 {
		mmClassify.mock.t.Fatalf("Times of RoleClassifierMock.Classify mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmClassify.expectedInvocations, n)
	mmClassify.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmClassify
}

func (mmClassify *mRoleClassifierMockClassify) invocationsDone() bool {
	if len(mmClassify.expectations) == 0 && mmClassify.defaultExpectation == nil && mmClassify.mock.funcClassify == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmClassify.mock.afterClassifyCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmClassify.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Classify implements mm_usecase.RoleClassifier
func (mmClassify *RoleClassifierMock) Classify(ctx context.Context, title string, description string) (s1 string, err error) {
	mm_atomic.AddUint64(&mmClassify.beforeClassifyCounter, 1)
	defer mm_atomic.AddUint64(&mmClassify.afterClassifyCounter, 1)

	mmClassify.t.Helper()

	if mmClassify.inspectFuncClassify != nil {
		mmClassify.inspectFuncClassify(ctx, title, description)
	}

	mm_params := RoleClassifierMockClassifyParams{ctx, title, description}

	// Record call args
	mmClassify.ClassifyMock.mutex.Lock()
	mmClassify.ClassifyMock.callArgs = append(mmClassify.ClassifyMock.callArgs, &mm_params)
	mmClassify.ClassifyMock.mutex.Unlock()

	for _, e := range mmClassify.ClassifyMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmClassify.ClassifyMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmClassify.ClassifyMock.defaultExpectation.Counter, 1)
		mm_want := mmClassify.ClassifyMock.defaultExpectation.params
		mm_want_ptrs := mmClassify.ClassifyMock.defaultExpectation.paramPtrs

		mm_got := RoleClassifierMockClassifyParams{ctx, title, description}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmClassify.t.Errorf("RoleClassifierMock.Classify got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmClassify.ClassifyMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.title != nil && !minimock.Equal(*mm_want_ptrs.title, mm_got.title) {
				mmClassify.t.Errorf("RoleClassifierMock.Classify got unexpected parameter title, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmClassify.ClassifyMock.defaultExpectation.expectationOrigins.originTitle, *mm_want_ptrs.title, mm_got.title, minimock.Diff(*mm_want_ptrs.title, mm_got.title))
			}

			if mm_want_ptrs.description != nil && !minimock.Equal(*mm_want_ptrs.description, mm_got.description) {
				mmClassify.t.Errorf("RoleClassifierMock.Classify got unexpected parameter description, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmClassify.ClassifyMock.defaultExpectation.expectationOrigins.originDescription, *mm_want_ptrs.description, mm_got.description, minimock.Diff(*mm_want_ptrs.description, mm_got.description))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmClassify.t.Errorf("RoleClassifierMock.Classify got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmClassify.ClassifyMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmClassify.ClassifyMock.defaultExpectation.results
		if mm_results == nil {
			mmClassify.t.Fatal("No results are set for the RoleClassifierMock.Classify")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmClassify.funcClassify != nil {
		return mmClassify.funcClassify(ctx, title, description)
	}
	mmClassify.t.Fatalf("Unexpected call to RoleClassifierMock.Classify. %v %v %v", ctx, title, description)
	return
}

// ClassifyAfterCounter returns a count of finished RoleClassifierMock.Classify invocations
func (mmClassify *RoleClassifierMock) ClassifyAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmClassify.afterClassifyCounter)
}

// ClassifyBeforeCounter returns a count of RoleClassifierMock.Classify invocations
func (mmClassify *RoleClassifierMock) ClassifyBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmClassify.beforeClassifyCounter)
}

// Calls returns a list of arguments used in each call to RoleClassifierMock.Classify.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmClassify *mRoleClassifierMockClassify) Calls() []*RoleClassifierMockClassifyParams {
	mmClassify.mutex.RLock()

	argCopy := make([]*RoleClassifierMockClassifyParams, len(mmClassify.callArgs))
	copy(argCopy, mmClassify.callArgs)

	mmClassify.mutex.RUnlock()

	return argCopy
}

// MinimockClassifyDone returns true if the count of the Classify invocations corresponds
// the number of defined expectations
func (m *RoleClassifierMock) MinimockClassifyDone() bool {
	if m.ClassifyMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ClassifyMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ClassifyMock.invocationsDone()
}

// MinimockClassifyInspect logs each unmet expectation
func (m *RoleClassifierMock) MinimockClassifyInspect() {
	for _, e := range m.ClassifyMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RoleClassifierMock.Classify at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterClassifyCounter := mm_atomic.LoadUint64(&m.afterClassifyCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ClassifyMock.defaultExpectation != nil && afterClassifyCounter < 1 {
		if m.ClassifyMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RoleClassifierMock.Classify at\n%s", m.ClassifyMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RoleClassifierMock.Classify at\n%s with params: %#v", m.ClassifyMock.defaultExpectation.expectationOrigins.origin, *m.ClassifyMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcClassify != nil && afterClassifyCounter < 1 {
		m.t.Errorf("Expected call to RoleClassifierMock.Classify at\n%s", m.funcClassifyOrigin)
	}

	if !m.ClassifyMock.invocationsDone() && afterClassifyCounter > 0 {
		m.t.Errorf("Expected %d calls to RoleClassifierMock.Classify at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ClassifyMock.expectedInvocations), m.ClassifyMock.expectedInvocationsOrigin, afterClassifyCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RoleClassifierMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockClassifyInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RoleClassifierMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RoleClassifierMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockClassifyDone()
}
