// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: multiagent_api/multiagent.proto

package multiagent_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMode int32

const (
	AgentMode_AGENT_MODE_UNSPECIFIED AgentMode = 0
	AgentMode_AGENT_MODE_FAST        AgentMode = 1
	AgentMode_AGENT_MODE_BALANCED    AgentMode = 2
	AgentMode_AGENT_MODE_STRICT      AgentMode = 3
)

// Enum value maps for AgentMode.
var (
	AgentMode_name = map[int32]string{
		0: "AGENT_MODE_UNSPECIFIED",
		1: "AGENT_MODE_FAST",
		2: "AGENT_MODE_BALANCED",
		3: "AGENT_MODE_STRICT",
	}
	AgentMode_value = map[string]int32{
		"AGENT_MODE_UNSPECIFIED": 0,
		"AGENT_MODE_FAST":        1,
		"AGENT_MODE_BALANCED":    2,
		"AGENT_MODE_STRICT":      3,
	}
)

func (x AgentMode) Enum() *AgentMode {
	p := new(AgentMode)
	*p = x
	return p
}

func (x AgentMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentMode) Descriptor() protoreflect.EnumDescriptor {
	return file_multiagent_api_multiagent_proto_enumTypes[0].Descriptor()
}

func (AgentMode) Type() protoreflect.EnumType {
	return &file_multiagent_api_multiagent_proto_enumTypes[0]
}

func (x AgentMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentMode.Descriptor instead.
func (AgentMode) EnumDescriptor() ([]byte, []int) {
	return file_multiagent_api_multiagent_proto_rawDescGZIP(), []int{0}
}

type GenerateDecisionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Model              string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Mode               AgentMode              `protobuf:"varint,2,opt,name=mode,proto3,enum=multiagent.service.v1.AgentMode" json:"mode,omitempty"`
	VacancyTitle       string                 `protobuf:"bytes,3,opt,name=vacancy_title,json=vacancyTitle,proto3" json:"vacancy_title,omitempty"`
	VacancyDescription string                 `protobuf:"bytes,4,opt,name=vacancy_description,json=vacancyDescription,proto3" json:"vacancy_description,omitempty"`
	VacancyMustHave    []string               `protobuf:"bytes,5,rep,name=vacancy_must_have,json=vacancyMustHave,proto3" json:"vacancy_must_have,omitempty"`
	VacancyNiceToHave  []string               `protobuf:"bytes,6,rep,name=vacancy_nice_to_have,json=vacancyNiceToHave,proto3" json:"vacancy_nice_to_have,omitempty"`
	CandidateSkills    []string               `protobuf:"bytes,7,rep,name=candidate_skills,json=candidateSkills,proto3" json:"candidate_skills,omitempty"`
	MissingSkills      []string               `protobuf:"bytes,8,rep,name=missing_skills,json=missingSkills,proto3" json:"missing_skills,omitempty"`
	CandidateSummary   string                 `protobuf:"bytes,9,opt,name=candidate_summary,json=candidateSummary,proto3" json:"candidate_summary,omitempty"`
	ScoreExplanation   string                 `protobuf:"bytes,10,opt,name=score_explanation,json=scoreExplanation,proto3" json:"score_explanation,omitempty"`
	MatchScore         float32                `protobuf:"fixed32,11,opt,name=match_score,json=matchScore,proto3" json:"match_score,omitempty"`
	ResumeText         string                 `protobuf:"bytes,12,opt,name=resume_text,json=resumeText,proto3" json:"resume_text,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GenerateDecisionRequest) Reset() {
	*x = GenerateDecisionRequest{}
	mi := &file_multiagent_api_multiagent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDecisionRequest) ProtoMessage() {}

func (x *GenerateDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiagent_api_multiagent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDecisionRequest.ProtoReflect.Descriptor instead.
func (*GenerateDecisionRequest) Descriptor() ([]byte, []int) {
	return file_multiagent_api_multiagent_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateDecisionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateDecisionRequest) GetMode() AgentMode {
	if x != nil {
		return x.Mode
	}
	return AgentMode_AGENT_MODE_UNSPECIFIED
}

func (x *GenerateDecisionRequest) GetVacancyTitle() string {
	if x != nil {
		return x.VacancyTitle
	}
	return ""
}

func (x *GenerateDecisionRequest) GetVacancyDescription() string {
	if x != nil {
		return x.VacancyDescription
	}
	return ""
}

func (x *GenerateDecisionRequest) GetVacancyMustHave() []string {
	if x != nil {
		return x.VacancyMustHave
	}
	return nil
}

func (x *GenerateDecisionRequest) GetVacancyNiceToHave() []string {
	if x != nil {
		return x.VacancyNiceToHave
	}
	return nil
}

func (x *GenerateDecisionRequest) GetCandidateSkills() []string {
	if x != nil {
		return x.CandidateSkills
	}
	return nil
}

func (x *GenerateDecisionRequest) GetMissingSkills() []string {
	if x != nil {
		return x.MissingSkills
	}
	return nil
}

func (x *GenerateDecisionRequest) GetCandidateSummary() string {
	if x != nil {
		return x.CandidateSummary
	}
	return ""
}

func (x *GenerateDecisionRequest) GetScoreExplanation() string {
	if x != nil {
		return x.ScoreExplanation
	}
	return ""
}

func (x *GenerateDecisionRequest) GetMatchScore() float32 {
	if x != nil {
		return x.MatchScore
	}
	return 0
}

func (x *GenerateDecisionRequest) GetResumeText() string {
	if x != nil {
		return x.ResumeText
	}
	return ""
}

type AgentResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentName      string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Summary        string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	StructuredJson string                 `protobuf:"bytes,3,opt,name=structured_json,json=structuredJson,proto3" json:"structured_json,omitempty"`
	Confidence     float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentResult) Reset() {
	*x = AgentResult{}
	mi := &file_multiagent_api_multiagent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResult) ProtoMessage() {}

func (x *AgentResult) ProtoReflect() protoreflect.Message {
	mi := &file_multiagent_api_multiagent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResult.ProtoReflect.Descriptor instead.
func (*AgentResult) Descriptor() ([]byte, []int) {
	return file_multiagent_api_multiagent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentResult) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentResult) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AgentResult) GetStructuredJson() string {
	if x != nil {
		return x.StructuredJson
	}
	return ""
}

func (x *AgentResult) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type GenerateDecisionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HrRecommendation  string                 `protobuf:"bytes,1,opt,name=hr_recommendation,json=hrRecommendation,proto3" json:"hr_recommendation,omitempty"`
	Confidence        float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	HrRationale       string                 `protobuf:"bytes,3,opt,name=hr_rationale,json=hrRationale,proto3" json:"hr_rationale,omitempty"`
	CandidateFeedback string                 `protobuf:"bytes,4,opt,name=candidate_feedback,json=candidateFeedback,proto3" json:"candidate_feedback,omitempty"`
	SoftSkillsNotes   string                 `protobuf:"bytes,5,opt,name=soft_skills_notes,json=softSkillsNotes,proto3" json:"soft_skills_notes,omitempty"`
	AgentResults      []*AgentResult         `protobuf:"bytes,6,rep,name=agent_results,json=agentResults,proto3" json:"agent_results,omitempty"`
	RawTrace          string                 `protobuf:"bytes,7,opt,name=raw_trace,json=rawTrace,proto3" json:"raw_trace,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GenerateDecisionResponse) Reset() {
	*x = GenerateDecisionResponse{}
	mi := &file_multiagent_api_multiagent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDecisionResponse) ProtoMessage() {}

func (x *GenerateDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiagent_api_multiagent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDecisionResponse.ProtoReflect.Descriptor instead.
func (*GenerateDecisionResponse) Descriptor() ([]byte, []int) {
	return file_multiagent_api_multiagent_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateDecisionResponse) GetHrRecommendation() string {
	if x != nil {
		return x.HrRecommendation
	}
	return ""
}

func (x *GenerateDecisionResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *GenerateDecisionResponse) GetHrRationale() string {
	if x != nil {
		return x.HrRationale
	}
	return ""
}

func (x *GenerateDecisionResponse) GetCandidateFeedback() string {
	if x != nil {
		return x.CandidateFeedback
	}
	return ""
}

func (x *GenerateDecisionResponse) GetSoftSkillsNotes() string {
	if x != nil {
		return x.SoftSkillsNotes
	}
	return ""
}

func (x *GenerateDecisionResponse) GetAgentResults() []*AgentResult {
	if x != nil {
		return x.AgentResults
	}
	return nil
}

func (x *GenerateDecisionResponse) GetRawTrace() string {
	if x != nil {
		return x.RawTrace
	}
	return ""
}

func (x *GenerateDecisionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_multiagent_api_multiagent_proto protoreflect.FileDescriptor

const file_multiagent_api_multiagent_proto_rawDesc = "" +
	"\n" +
	"\x1fmultiagent_api/multiagent.proto\x12\x15multiagent.service.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x04\n" +
	"\x17GenerateDecisionRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x124\n" +
	"\x04mode\x18\x02 \x01(\x0e2 .multiagent.service.v1.AgentModeR\x04mode\x12#\n" +
	"\rvacancy_title\x18\x03 \x01(\tR\fvacancyTitle\x12/\n" +
	"\x13vacancy_description\x18\x04 \x01(\tR\x12vacancyDescription\x12*\n" +
	"\x11vacancy_must_have\x18\x05 \x03(\tR\x0fvacancyMustHave\x12/\n" +
	"\x14vacancy_nice_to_have\x18\x06 \x03(\tR\x11vacancyNiceToHave\x12)\n" +
	"\x10candidate_skills\x18\a \x03(\tR\x0fcandidateSkills\x12%\n" +
	"\x0emissing_skills\x18\b \x03(\tR\rmissingSkills\x12+\n" +
	"\x11candidate_summary\x18\t \x01(\tR\x10candidateSummary\x12+\n" +
	"\x11score_explanation\x18\n" +
	" \x01(\tR\x10scoreExplanation\x12\x1f\n" +
	"\vmatch_score\x18\v \x01(\x02R\n" +
	"matchScore\x12\x1f\n" +
	"\vresume_text\x18\f \x01(\tR\n" +
	"resumeText\"\x8f\x01\n" +
	"\vAgentResult\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12'\n" +
	"\x0fstructured_json\x18\x03 \x01(\tR\x0estructuredJson\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\"\x86\x03\n" +
	"\x18GenerateDecisionResponse\x12+\n" +
	"\x11hr_recommendation\x18\x01 \x01(\tR\x10hrRecommendation\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12!\n" +
	"\fhr_rationale\x18\x03 \x01(\tR\vhrRationale\x12-\n" +
	"\x12candidate_feedback\x18\x04 \x01(\tR\x11candidateFeedback\x12*\n" +
	"\x11soft_skills_notes\x18\x05 \x01(\tR\x0fsoftSkillsNotes\x12G\n" +
	"\ragent_results\x18\x06 \x03(\v2\".multiagent.service.v1.AgentResultR\fagentResults\x12\x1b\n" +
	"\traw_trace\x18\a \x01(\tR\brawTrace\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*l\n" +
	"\tAgentMode\x12\x1a\n" +
	"\x16AGENT_MODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fAGENT_MODE_FAST\x10\x01\x12\x17\n" +
	"\x13AGENT_MODE_BALANCED\x10\x02\x12\x15\n" +
	"\x11AGENT_MODE_STRICT\x10\x032\x88\x01\n" +
	"\x11MultiAgentService\x12s\n" +
	"\x10GenerateDecision\x12..multiagent.service.v1.GenerateDecisionRequest\x1a/.multiagent.service.v1.GenerateDecisionResponseB@Z>github.com/artem13815/hr/multiagent/internal/pb/multiagent_apib\x06proto3"

var (
	file_multiagent_api_multiagent_proto_rawDescOnce sync.Once
	file_multiagent_api_multiagent_proto_rawDescData []byte
)

func file_multiagent_api_multiagent_proto_rawDescGZIP() []byte {
	file_multiagent_api_multiagent_proto_rawDescOnce.Do(func() {
		file_multiagent_api_multiagent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multiagent_api_multiagent_proto_rawDesc), len(file_multiagent_api_multiagent_proto_rawDesc)))
	})
	return file_multiagent_api_multiagent_proto_rawDescData
}

var file_multiagent_api_multiagent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_multiagent_api_multiagent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_multiagent_api_multiagent_proto_goTypes = []any{
	(AgentMode)(0),                   // 0: multiagent.service.v1.AgentMode
	(*GenerateDecisionRequest)(nil),  // 1: multiagent.service.v1.GenerateDecisionRequest
	(*AgentResult)(nil),              // 2: multiagent.service.v1.AgentResult
	(*GenerateDecisionResponse)(nil), // 3: multiagent.service.v1.GenerateDecisionResponse
	(*timestamppb.Timestamp)(nil),    // 4: google.protobuf.Timestamp
}
var file_multiagent_api_multiagent_proto_depIdxs = []int32{
	0, // 0: multiagent.service.v1.GenerateDecisionRequest.mode:type_name -> multiagent.service.v1.AgentMode
	2, // 1: multiagent.service.v1.GenerateDecisionResponse.agent_results:type_name -> multiagent.service.v1.AgentResult
	4, // 2: multiagent.service.v1.GenerateDecisionResponse.created_at:type_name -> google.protobuf.Timestamp
	1, // 3: multiagent.service.v1.MultiAgentService.GenerateDecision:input_type -> multiagent.service.v1.GenerateDecisionRequest
	3, // 4: multiagent.service.v1.MultiAgentService.GenerateDecision:output_type -> multiagent.service.v1.GenerateDecisionResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_multiagent_api_multiagent_proto_init() }
func file_multiagent_api_multiagent_proto_init() {
	if File_multiagent_api_multiagent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multiagent_api_multiagent_proto_rawDesc), len(file_multiagent_api_multiagent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multiagent_api_multiagent_proto_goTypes,
		DependencyIndexes: file_multiagent_api_multiagent_proto_depIdxs,
		EnumInfos:         file_multiagent_api_multiagent_proto_enumTypes,
		MessageInfos:      file_multiagent_api_multiagent_proto_msgTypes,
	}.Build()
	File_multiagent_api_multiagent_proto = out.File
	file_multiagent_api_multiagent_proto_goTypes = nil
	file_multiagent_api_multiagent_proto_depIdxs = nil
}
