// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: models/resume_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Candidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VacancyId     string                 `protobuf:"bytes,2,opt,name=vacancy_id,json=vacancyId,proto3" json:"vacancy_id,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Comment       string                 `protobuf:"bytes,7,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_models_resume_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_models_resume_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_models_resume_model_proto_rawDescGZIP(), []int{0}
}

func (x *Candidate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Candidate) GetVacancyId() string {
	if x != nil {
		return x.VacancyId
	}
	return ""
}

func (x *Candidate) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Candidate) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Candidate) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Candidate) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Candidate) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Candidate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Resume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CandidateId   string                 `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType      string                 `protobuf:"bytes,4,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	FileSizeBytes uint64                 `protobuf:"varint,5,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	StoragePath   string                 `protobuf:"bytes,6,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	ExtractedText string                 `protobuf:"bytes,7,opt,name=extracted_text,json=extractedText,proto3" json:"extracted_text,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resume) Reset() {
	*x = Resume{}
	mi := &file_models_resume_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resume) ProtoMessage() {}

func (x *Resume) ProtoReflect() protoreflect.Message {
	mi := &file_models_resume_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resume.ProtoReflect.Descriptor instead.
func (*Resume) Descriptor() ([]byte, []int) {
	return file_models_resume_model_proto_rawDescGZIP(), []int{1}
}

func (x *Resume) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resume) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *Resume) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Resume) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *Resume) GetFileSizeBytes() uint64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

func (x *Resume) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *Resume) GetExtractedText() string {
	if x != nil {
		return x.ExtractedText
	}
	return ""
}

func (x *Resume) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateCandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VacancyId     string                 `protobuf:"bytes,1,opt,name=vacancy_id,json=vacancyId,proto3" json:"vacancy_id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Comment       string                 `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCandidateRequest) Reset() {
	*x = CreateCandidateRequest{}
	mi := &file_models_resume_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCandidateRequest) ProtoMessage() {}

func (x *CreateCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_resume_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCandidateRequest.ProtoReflect.Descriptor instead.
func (*CreateCandidateRequest) Descriptor() ([]byte, []int) {
	return file_models_resume_model_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCandidateRequest) GetVacancyId() string {
	if x != nil {
		return x.VacancyId
	}
	return ""
}

func (x *CreateCandidateRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateCandidateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateCandidateRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateCandidateRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateCandidateRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type GetCandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateId   string                 `protobuf:"bytes,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidateRequest) Reset() {
	*x = GetCandidateRequest{}
	mi := &file_models_resume_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidateRequest) ProtoMessage() {}

func (x *GetCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_resume_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidateRequest.ProtoReflect.Descriptor instead.
func (*GetCandidateRequest) Descriptor() ([]byte, []int) {
	return file_models_resume_model_proto_rawDescGZIP(), []int{3}
}

func (x *GetCandidateRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

type CandidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidate     *Candidate             `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateResponse) Reset() {
	*x = CandidateResponse{}
	mi := &file_models_resume_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateResponse) ProtoMessage() {}

func (x *CandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_resume_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateResponse.ProtoReflect.Descriptor instead.
func (*CandidateResponse) Descriptor() ([]byte, []int) {
	return file_models_resume_model_proto_rawDescGZIP(), []int{4}
}

func (x *CandidateResponse) GetCandidate() *Candidate {
	if x != nil {
		return x.Candidate
	}
	return nil
}

type CandidateResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidate     *Candidate             `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	Resume        *Resume                `protobuf:"bytes,2,opt,name=resume,proto3" json:"resume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateResumeResponse) Reset() {
	*x = CandidateResumeResponse{}
	mi := &file_models_resume_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateResumeResponse) ProtoMessage() {}

func (x *CandidateResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_resume_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateResumeResponse.ProtoReflect.Descriptor instead.
func (*CandidateResumeResponse) Descriptor() ([]byte, []int) {
	return file_models_resume_model_proto_rawDescGZIP(), []int{5}
}

func (x *CandidateResumeResponse) GetCandidate() *Candidate {
	if x != nil {
		return x.Candidate
	}
	return nil
}

func (x *CandidateResumeResponse) GetResume() *Resume {
	if x != nil {
		return x.Resume
	}
	return nil
}

type CreateCandidateFromResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VacancyId     string                 `protobuf:"bytes,1,opt,name=vacancy_id,json=vacancyId,proto3" json:"vacancy_id,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCandidateFromResumeRequest) Reset() {
	*x = CreateCandidateFromResumeRequest{}
	mi := &file_models_resume_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCandidateFromResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCandidateFromResumeRequest) ProtoMessage() {}

func (x *CreateCandidateFromResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_resume_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCandidateFromResumeRequest.ProtoReflect.Descriptor instead.
func (*CreateCandidateFromResumeRequest) Descriptor() ([]byte, []int) {
	return file_models_resume_model_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCandidateFromResumeRequest) GetVacancyId() string {
	if x != nil {
		return x.VacancyId
	}
	return ""
}

func (x *CreateCandidateFromResumeRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type ResumeIntakeFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeIntakeFile) Reset() {
	*x = ResumeIntakeFile{}
	mi := &file_models_resume_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeIntakeFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeIntakeFile) ProtoMessage() {}

func (x *ResumeIntakeFile) ProtoReflect() protoreflect.Message {
	mi := &file_models_resume_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeIntakeFile.ProtoReflect.Descriptor instead.
func (*ResumeIntakeFile) Descriptor() ([]byte, []int) {
	return file_models_resume_model_proto_rawDescGZIP(), []int{7}
}

func (x *ResumeIntakeFile) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ResumeIntakeFile) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type BatchIngestResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*ResumeIntakeFile    `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchIngestResumeRequest) Reset() {
	*x = BatchIngestResumeRequest{}
	mi := &file_models_resume_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchIngestResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchIngestResumeRequest) ProtoMessage() {}

func (x *BatchIngestResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_resume_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchIngestResumeRequest.ProtoReflect.Descriptor instead.
func (*BatchIngestResumeRequest) Descriptor() ([]byte, []int) {
	return file_models_resume_model_proto_rawDescGZIP(), []int{8}
}

func (x *BatchIngestResumeRequest) GetFiles() []*ResumeIntakeFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type BatchIngestResumeItemResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Candidate     *Candidate             `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	Resume        *Resume                `protobuf:"bytes,3,opt,name=resume,proto3" json:"resume,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchIngestResumeItemResult) Reset() {
	*x = BatchIngestResumeItemResult{}
	mi := &file_models_resume_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchIngestResumeItemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchIngestResumeItemResult) ProtoMessage() {}

func (x *BatchIngestResumeItemResult) ProtoReflect() protoreflect.Message {
	mi := &file_models_resume_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchIngestResumeItemResult.ProtoReflect.Descriptor instead.
func (*BatchIngestResumeItemResult) Descriptor() ([]byte, []int) {
	return file_models_resume_model_proto_rawDescGZIP(), []int{9}
}

func (x *BatchIngestResumeItemResult) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *BatchIngestResumeItemResult) GetCandidate() *Candidate {
	if x != nil {
		return x.Candidate
	}
	return nil
}

func (x *BatchIngestResumeItemResult) GetResume() *Resume {
	if x != nil {
		return x.Resume
	}
	return nil
}

func (x *BatchIngestResumeItemResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchIngestResumeResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Results       []*BatchIngestResumeItemResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchIngestResumeResponse) Reset() {
	*x = BatchIngestResumeResponse{}
	mi := &file_models_resume_model_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchIngestResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchIngestResumeResponse) ProtoMessage() {}

func (x *BatchIngestResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_resume_model_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchIngestResumeResponse.ProtoReflect.Descriptor instead.
func (*BatchIngestResumeResponse) Descriptor() ([]byte, []int) {
	return file_models_resume_model_proto_rawDescGZIP(), []int{10}
}

func (x *BatchIngestResumeResponse) GetResults() []*BatchIngestResumeItemResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type UploadResumeMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateId   string                 `protobuf:"bytes,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType      string                 `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResumeMeta) Reset() {
	*x = UploadResumeMeta{}
	mi := &file_models_resume_model_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResumeMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResumeMeta) ProtoMessage() {}

func (x *UploadResumeMeta) ProtoReflect() protoreflect.Message {
	mi := &file_models_resume_model_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResumeMeta.ProtoReflect.Descriptor instead.
func (*UploadResumeMeta) Descriptor() ([]byte, []int) {
	return file_models_resume_model_proto_rawDescGZIP(), []int{11}
}

func (x *UploadResumeMeta) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *UploadResumeMeta) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadResumeMeta) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

type UploadResumeChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResumeChunk) Reset() {
	*x = UploadResumeChunk{}
	mi := &file_models_resume_model_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResumeChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResumeChunk) ProtoMessage() {}

func (x *UploadResumeChunk) ProtoReflect() protoreflect.Message {
	mi := &file_models_resume_model_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResumeChunk.ProtoReflect.Descriptor instead.
func (*UploadResumeChunk) Descriptor() ([]byte, []int) {
	return file_models_resume_model_proto_rawDescGZIP(), []int{12}
}

func (x *UploadResumeChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadResumeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadResumeRequest_Meta
	//	*UploadResumeRequest_Chunk
	Payload       isUploadResumeRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResumeRequest) Reset() {
	*x = UploadResumeRequest{}
	mi := &file_models_resume_model_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResumeRequest) ProtoMessage() {}

func (x *UploadResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_resume_model_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResumeRequest.ProtoReflect.Descriptor instead.
func (*UploadResumeRequest) Descriptor() ([]byte, []int) {
	return file_models_resume_model_proto_rawDescGZIP(), []int{13}
}

func (x *UploadResumeRequest) GetPayload() isUploadResumeRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadResumeRequest) GetMeta() *UploadResumeMeta {
	if x != nil {
		if x, ok := x.Payload.(*UploadResumeRequest_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *UploadResumeRequest) GetChunk() *UploadResumeChunk {
	if x != nil {
		if x, ok := x.Payload.(*UploadResumeRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadResumeRequest_Payload interface {
	isUploadResumeRequest_Payload()
}

type UploadResumeRequest_Meta struct {
	Meta *UploadResumeMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type UploadResumeRequest_Chunk struct {
	Chunk *UploadResumeChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadResumeRequest_Meta) isUploadResumeRequest_Payload() {}

func (*UploadResumeRequest_Chunk) isUploadResumeRequest_Payload() {}

type UploadResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resume        *Resume                `protobuf:"bytes,1,opt,name=resume,proto3" json:"resume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResumeResponse) Reset() {
	*x = UploadResumeResponse{}
	mi := &file_models_resume_model_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResumeResponse) ProtoMessage() {}

func (x *UploadResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_resume_model_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResumeResponse.ProtoReflect.Descriptor instead.
func (*UploadResumeResponse) Descriptor() ([]byte, []int) {
	return file_models_resume_model_proto_rawDescGZIP(), []int{14}
}

func (x *UploadResumeResponse) GetResume() *Resume {
	if x != nil {
		return x.Resume
	}
	return nil
}

type GetResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResumeId      string                 `protobuf:"bytes,1,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResumeRequest) Reset() {
	*x = GetResumeRequest{}
	mi := &file_models_resume_model_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResumeRequest) ProtoMessage() {}

func (x *GetResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_resume_model_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResumeRequest.ProtoReflect.Descriptor instead.
func (*GetResumeRequest) Descriptor() ([]byte, []int) {
	return file_models_resume_model_proto_rawDescGZIP(), []int{15}
}

func (x *GetResumeRequest) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

type ResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resume        *Resume                `protobuf:"bytes,1,opt,name=resume,proto3" json:"resume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeResponse) Reset() {
	*x = ResumeResponse{}
	mi := &file_models_resume_model_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeResponse) ProtoMessage() {}

func (x *ResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_resume_model_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeResponse.ProtoReflect.Descriptor instead.
func (*ResumeResponse) Descriptor() ([]byte, []int) {
	return file_models_resume_model_proto_rawDescGZIP(), []int{16}
}

func (x *ResumeResponse) GetResume() *Resume {
	if x != nil {
		return x.Resume
	}
	return nil
}

var File_models_resume_model_proto protoreflect.FileDescriptor

const file_models_resume_model_proto_rawDesc = "" +
	"\n" +
	"\x19models/resume_model.proto\x12\x10resume.models.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf0\x01\n" +
	"\tCandidate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"vacancy_id\x18\x02 \x01(\tR\tvacancyId\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x18\n" +
	"\acomment\x18\a \x01(\tR\acomment\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa2\x02\n" +
	"\x06Resume\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\tR\vcandidateId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\x04 \x01(\tR\bfileType\x12&\n" +
	"\x0ffile_size_bytes\x18\x05 \x01(\x04R\rfileSizeBytes\x12!\n" +
	"\fstorage_path\x18\x06 \x01(\tR\vstoragePath\x12%\n" +
	"\x0eextracted_text\x18\a \x01(\tR\rextractedText\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb2\x01\n" +
	"\x16CreateCandidateRequest\x12\x1d\n" +
	"\n" +
	"vacancy_id\x18\x01 \x01(\tR\tvacancyId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x18\n" +
	"\acomment\x18\x06 \x01(\tR\acomment\"8\n" +
	"\x13GetCandidateRequest\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\tR\vcandidateId\"N\n" +
	"\x11CandidateResponse\x129\n" +
	"\tcandidate\x18\x01 \x01(\v2\x1b.resume.models.v1.CandidateR\tcandidate\"\x86\x01\n" +
	"\x17CandidateResumeResponse\x129\n" +
	"\tcandidate\x18\x01 \x01(\v2\x1b.resume.models.v1.CandidateR\tcandidate\x120\n" +
	"\x06resume\x18\x02 \x01(\v2\x18.resume.models.v1.ResumeR\x06resume\"^\n" +
	" CreateCandidateFromResumeRequest\x12\x1d\n" +
	"\n" +
	"vacancy_id\x18\x01 \x01(\tR\tvacancyId\x12\x1b\n" +
	"\tfile_data\x18\x02 \x01(\fR\bfileData\"P\n" +
	"\x10ResumeIntakeFile\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x1b\n" +
	"\tfile_data\x18\x02 \x01(\fR\bfileData\"T\n" +
	"\x18BatchIngestResumeRequest\x128\n" +
	"\x05files\x18\x01 \x03(\v2\".resume.models.v1.ResumeIntakeFileR\x05files\"\xc1\x01\n" +
	"\x1bBatchIngestResumeItemResult\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x129\n" +
	"\tcandidate\x18\x02 \x01(\v2\x1b.resume.models.v1.CandidateR\tcandidate\x120\n" +
	"\x06resume\x18\x03 \x01(\v2\x18.resume.models.v1.ResumeR\x06resume\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"d\n" +
	"\x19BatchIngestResumeResponse\x12G\n" +
	"\aresults\x18\x01 \x03(\v2-.resume.models.v1.BatchIngestResumeItemResultR\aresults\"o\n" +
	"\x10UploadResumeMeta\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\tR\vcandidateId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\tR\bfileType\"'\n" +
	"\x11UploadResumeChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x97\x01\n" +
	"\x13UploadResumeRequest\x128\n" +
	"\x04meta\x18\x01 \x01(\v2\".resume.models.v1.UploadResumeMetaH\x00R\x04meta\x12;\n" +
	"\x05chunk\x18\x02 \x01(\v2#.resume.models.v1.UploadResumeChunkH\x00R\x05chunkB\t\n" +
	"\apayload\"H\n" +
	"\x14UploadResumeResponse\x120\n" +
	"\x06resume\x18\x01 \x01(\v2\x18.resume.models.v1.ResumeR\x06resume\"/\n" +
	"\x10GetResumeRequest\x12\x1b\n" +
	"\tresume_id\x18\x01 \x01(\tR\bresumeId\"B\n" +
	"\x0eResumeResponse\x120\n" +
	"\x06resume\x18\x01 \x01(\v2\x18.resume.models.v1.ResumeR\x06resumeB5Z3github.com/artem13815/hr/gateway/internal/pb/modelsb\x06proto3"

var (
	file_models_resume_model_proto_rawDescOnce sync.Once
	file_models_resume_model_proto_rawDescData []byte
)

func file_models_resume_model_proto_rawDescGZIP() []byte {
	file_models_resume_model_proto_rawDescOnce.Do(func() {
		file_models_resume_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_resume_model_proto_rawDesc), len(file_models_resume_model_proto_rawDesc)))
	})
	return file_models_resume_model_proto_rawDescData
}

var file_models_resume_model_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_models_resume_model_proto_goTypes = []any{
	(*Candidate)(nil),                        // 0: resume.models.v1.Candidate
	(*Resume)(nil),                           // 1: resume.models.v1.Resume
	(*CreateCandidateRequest)(nil),           // 2: resume.models.v1.CreateCandidateRequest
	(*GetCandidateRequest)(nil),              // 3: resume.models.v1.GetCandidateRequest
	(*CandidateResponse)(nil),                // 4: resume.models.v1.CandidateResponse
	(*CandidateResumeResponse)(nil),          // 5: resume.models.v1.CandidateResumeResponse
	(*CreateCandidateFromResumeRequest)(nil), // 6: resume.models.v1.CreateCandidateFromResumeRequest
	(*ResumeIntakeFile)(nil),                 // 7: resume.models.v1.ResumeIntakeFile
	(*BatchIngestResumeRequest)(nil),         // 8: resume.models.v1.BatchIngestResumeRequest
	(*BatchIngestResumeItemResult)(nil),      // 9: resume.models.v1.BatchIngestResumeItemResult
	(*BatchIngestResumeResponse)(nil),        // 10: resume.models.v1.BatchIngestResumeResponse
	(*UploadResumeMeta)(nil),                 // 11: resume.models.v1.UploadResumeMeta
	(*UploadResumeChunk)(nil),                // 12: resume.models.v1.UploadResumeChunk
	(*UploadResumeRequest)(nil),              // 13: resume.models.v1.UploadResumeRequest
	(*UploadResumeResponse)(nil),             // 14: resume.models.v1.UploadResumeResponse
	(*GetResumeRequest)(nil),                 // 15: resume.models.v1.GetResumeRequest
	(*ResumeResponse)(nil),                   // 16: resume.models.v1.ResumeResponse
	(*timestamppb.Timestamp)(nil),            // 17: google.protobuf.Timestamp
}
var file_models_resume_model_proto_depIdxs = []int32{
	17, // 0: resume.models.v1.Candidate.created_at:type_name -> google.protobuf.Timestamp
	17, // 1: resume.models.v1.Resume.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: resume.models.v1.CandidateResponse.candidate:type_name -> resume.models.v1.Candidate
	0,  // 3: resume.models.v1.CandidateResumeResponse.candidate:type_name -> resume.models.v1.Candidate
	1,  // 4: resume.models.v1.CandidateResumeResponse.resume:type_name -> resume.models.v1.Resume
	7,  // 5: resume.models.v1.BatchIngestResumeRequest.files:type_name -> resume.models.v1.ResumeIntakeFile
	0,  // 6: resume.models.v1.BatchIngestResumeItemResult.candidate:type_name -> resume.models.v1.Candidate
	1,  // 7: resume.models.v1.BatchIngestResumeItemResult.resume:type_name -> resume.models.v1.Resume
	9,  // 8: resume.models.v1.BatchIngestResumeResponse.results:type_name -> resume.models.v1.BatchIngestResumeItemResult
	11, // 9: resume.models.v1.UploadResumeRequest.meta:type_name -> resume.models.v1.UploadResumeMeta
	12, // 10: resume.models.v1.UploadResumeRequest.chunk:type_name -> resume.models.v1.UploadResumeChunk
	1,  // 11: resume.models.v1.UploadResumeResponse.resume:type_name -> resume.models.v1.Resume
	1,  // 12: resume.models.v1.ResumeResponse.resume:type_name -> resume.models.v1.Resume
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_models_resume_model_proto_init() }
func file_models_resume_model_proto_init() {
	if File_models_resume_model_proto != nil {
		return
	}
	file_models_resume_model_proto_msgTypes[13].OneofWrappers = []any{
		(*UploadResumeRequest_Meta)(nil),
		(*UploadResumeRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_resume_model_proto_rawDesc), len(file_models_resume_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_resume_model_proto_goTypes,
		DependencyIndexes: file_models_resume_model_proto_depIdxs,
		MessageInfos:      file_models_resume_model_proto_msgTypes,
	}.Build()
	File_models_resume_model_proto = out.File
	file_models_resume_model_proto_goTypes = nil
	file_models_resume_model_proto_depIdxs = nil
}
