// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/artem13815/hr/vacancy/internal/domain"
	"github.com/gojuno/minimock/v3"
)

// VacancyStorageMock implements mm_vacancy_service.VacancyStorage
type VacancyStorageMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcArchiveVacancy          func(ctx context.Context, in domain.ArchiveVacancyInput) (err error)
	funcArchiveVacancyOrigin    string
	inspectFuncArchiveVacancy   func(ctx context.Context, in domain.ArchiveVacancyInput)
	afterArchiveVacancyCounter  uint64
	beforeArchiveVacancyCounter uint64
	ArchiveVacancyMock          mVacancyStorageMockArchiveVacancy

	funcCreateVacancy          func(ctx context.Context, in domain.CreateVacancyInput) (vp1 *domain.Vacancy, err error)
	funcCreateVacancyOrigin    string
	inspectFuncCreateVacancy   func(ctx context.Context, in domain.CreateVacancyInput)
	afterCreateVacancyCounter  uint64
	beforeCreateVacancyCounter uint64
	CreateVacancyMock          mVacancyStorageMockCreateVacancy

	funcGetVacancy          func(ctx context.Context, vacancyID string, ownerUserID uint64, isAdmin bool) (vp1 *domain.Vacancy, err error)
	funcGetVacancyOrigin    string
	inspectFuncGetVacancy   func(ctx context.Context, vacancyID string, ownerUserID uint64, isAdmin bool)
	afterGetVacancyCounter  uint64
	beforeGetVacancyCounter uint64
	GetVacancyMock          mVacancyStorageMockGetVacancy

	funcListVacancies          func(ctx context.Context, in domain.ListVacanciesInput) (lp1 *domain.ListVacanciesResult, err error)
	funcListVacanciesOrigin    string
	inspectFuncListVacancies   func(ctx context.Context, in domain.ListVacanciesInput)
	afterListVacanciesCounter  uint64
	beforeListVacanciesCounter uint64
	ListVacanciesMock          mVacancyStorageMockListVacancies

	funcUpdateVacancy          func(ctx context.Context, in domain.UpdateVacancyInput) (vp1 *domain.Vacancy, err error)
	funcUpdateVacancyOrigin    string
	inspectFuncUpdateVacancy   func(ctx context.Context, in domain.UpdateVacancyInput)
	afterUpdateVacancyCounter  uint64
	beforeUpdateVacancyCounter uint64
	UpdateVacancyMock          mVacancyStorageMockUpdateVacancy
}

// NewVacancyStorageMock returns a mock for mm_vacancy_service.VacancyStorage
func NewVacancyStorageMock(t minimock.Tester) *VacancyStorageMock {
	m := &VacancyStorageMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ArchiveVacancyMock = mVacancyStorageMockArchiveVacancy{mock: m}
	m.ArchiveVacancyMock.callArgs = []*VacancyStorageMockArchiveVacancyParams{}

	m.CreateVacancyMock = mVacancyStorageMockCreateVacancy{mock: m}
	m.CreateVacancyMock.callArgs = []*VacancyStorageMockCreateVacancyParams{}

	m.GetVacancyMock = mVacancyStorageMockGetVacancy{mock: m}
	m.GetVacancyMock.callArgs = []*VacancyStorageMockGetVacancyParams{}

	m.ListVacanciesMock = mVacancyStorageMockListVacancies{mock: m}
	m.ListVacanciesMock.callArgs = []*VacancyStorageMockListVacanciesParams{}

	m.UpdateVacancyMock = mVacancyStorageMockUpdateVacancy{mock: m}
	m.UpdateVacancyMock.callArgs = []*VacancyStorageMockUpdateVacancyParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mVacancyStorageMockArchiveVacancy struct {
	optional           bool
	mock               *VacancyStorageMock
	defaultExpectation *VacancyStorageMockArchiveVacancyExpectation
	expectations       []*VacancyStorageMockArchiveVacancyExpectation

	callArgs []*VacancyStorageMockArchiveVacancyParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// VacancyStorageMockArchiveVacancyExpectation specifies expectation struct of the VacancyStorage.ArchiveVacancy
type VacancyStorageMockArchiveVacancyExpectation struct {
	mock               *VacancyStorageMock
	params             *VacancyStorageMockArchiveVacancyParams
	paramPtrs          *VacancyStorageMockArchiveVacancyParamPtrs
	expectationOrigins VacancyStorageMockArchiveVacancyExpectationOrigins
	results            *VacancyStorageMockArchiveVacancyResults
	returnOrigin       string
	Counter            uint64
}

// VacancyStorageMockArchiveVacancyParams contains parameters of the VacancyStorage.ArchiveVacancy
type VacancyStorageMockArchiveVacancyParams struct {
	ctx context.Context
	in  domain.ArchiveVacancyInput
}

// VacancyStorageMockArchiveVacancyParamPtrs contains pointers to parameters of the VacancyStorage.ArchiveVacancy
type VacancyStorageMockArchiveVacancyParamPtrs struct {
	ctx *context.Context
	in  *domain.ArchiveVacancyInput
}

// VacancyStorageMockArchiveVacancyResults contains results of the VacancyStorage.ArchiveVacancy
type VacancyStorageMockArchiveVacancyResults struct {
	err error
}

// VacancyStorageMockArchiveVacancyOrigins contains origins of expectations of the VacancyStorage.ArchiveVacancy
type VacancyStorageMockArchiveVacancyExpectationOrigins struct {
	origin    string
	originCtx string
	originIn  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmArchiveVacancy *mVacancyStorageMockArchiveVacancy) Optional() *mVacancyStorageMockArchiveVacancy {
	mmArchiveVacancy.optional = true
	return mmArchiveVacancy
}

// Expect sets up expected params for VacancyStorage.ArchiveVacancy
func (mmArchiveVacancy *mVacancyStorageMockArchiveVacancy) Expect(ctx context.Context, in domain.ArchiveVacancyInput) *mVacancyStorageMockArchiveVacancy {
	if mmArchiveVacancy.mock.funcArchiveVacancy != nil {
		mmArchiveVacancy.mock.t.Fatalf("VacancyStorageMock.ArchiveVacancy mock is already set by Set")
	}

	if mmArchiveVacancy.defaultExpectation == nil {
		mmArchiveVacancy.defaultExpectation = &VacancyStorageMockArchiveVacancyExpectation{}
	}

	if mmArchiveVacancy.defaultExpectation.paramPtrs != nil {
		mmArchiveVacancy.mock.t.Fatalf("VacancyStorageMock.ArchiveVacancy mock is already set by ExpectParams functions")
	}

	mmArchiveVacancy.defaultExpectation.params = &VacancyStorageMockArchiveVacancyParams{ctx, in}
	mmArchiveVacancy.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmArchiveVacancy.expectations {
		if minimock.Equal(e.params, mmArchiveVacancy.defaultExpectation.params) {
			mmArchiveVacancy.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmArchiveVacancy.defaultExpectation.params)
		}
	}

	return mmArchiveVacancy
}

// ExpectCtxParam1 sets up expected param ctx for VacancyStorage.ArchiveVacancy
func (mmArchiveVacancy *mVacancyStorageMockArchiveVacancy) ExpectCtxParam1(ctx context.Context) *mVacancyStorageMockArchiveVacancy {
	if mmArchiveVacancy.mock.funcArchiveVacancy != nil {
		mmArchiveVacancy.mock.t.Fatalf("VacancyStorageMock.ArchiveVacancy mock is already set by Set")
	}

	if mmArchiveVacancy.defaultExpectation == nil {
		mmArchiveVacancy.defaultExpectation = &VacancyStorageMockArchiveVacancyExpectation{}
	}

	if mmArchiveVacancy.defaultExpectation.params != nil {
		mmArchiveVacancy.mock.t.Fatalf("VacancyStorageMock.ArchiveVacancy mock is already set by Expect")
	}

	if mmArchiveVacancy.defaultExpectation.paramPtrs == nil {
		mmArchiveVacancy.defaultExpectation.paramPtrs = &VacancyStorageMockArchiveVacancyParamPtrs{}
	}
	mmArchiveVacancy.defaultExpectation.paramPtrs.ctx = &ctx
	mmArchiveVacancy.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmArchiveVacancy
}

// ExpectInParam2 sets up expected param in for VacancyStorage.ArchiveVacancy
func (mmArchiveVacancy *mVacancyStorageMockArchiveVacancy) ExpectInParam2(in domain.ArchiveVacancyInput) *mVacancyStorageMockArchiveVacancy {
	if mmArchiveVacancy.mock.funcArchiveVacancy != nil {
		mmArchiveVacancy.mock.t.Fatalf("VacancyStorageMock.ArchiveVacancy mock is already set by Set")
	}

	if mmArchiveVacancy.defaultExpectation == nil {
		mmArchiveVacancy.defaultExpectation = &VacancyStorageMockArchiveVacancyExpectation{}
	}

	if mmArchiveVacancy.defaultExpectation.params != nil {
		mmArchiveVacancy.mock.t.Fatalf("VacancyStorageMock.ArchiveVacancy mock is already set by Expect")
	}

	if mmArchiveVacancy.defaultExpectation.paramPtrs == nil {
		mmArchiveVacancy.defaultExpectation.paramPtrs = &VacancyStorageMockArchiveVacancyParamPtrs{}
	}
	mmArchiveVacancy.defaultExpectation.paramPtrs.in = &in
	mmArchiveVacancy.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmArchiveVacancy
}

// Inspect accepts an inspector function that has same arguments as the VacancyStorage.ArchiveVacancy
func (mmArchiveVacancy *mVacancyStorageMockArchiveVacancy) Inspect(f func(ctx context.Context, in domain.ArchiveVacancyInput)) *mVacancyStorageMockArchiveVacancy {
	if mmArchiveVacancy.mock.inspectFuncArchiveVacancy != nil {
		mmArchiveVacancy.mock.t.Fatalf("Inspect function is already set for VacancyStorageMock.ArchiveVacancy")
	}

	mmArchiveVacancy.mock.inspectFuncArchiveVacancy = f

	return mmArchiveVacancy
}

// Return sets up results that will be returned by VacancyStorage.ArchiveVacancy
func (mmArchiveVacancy *mVacancyStorageMockArchiveVacancy) Return(err error) *VacancyStorageMock {
	if mmArchiveVacancy.mock.funcArchiveVacancy != nil {
		mmArchiveVacancy.mock.t.Fatalf("VacancyStorageMock.ArchiveVacancy mock is already set by Set")
	}

	if mmArchiveVacancy.defaultExpectation == nil {
		mmArchiveVacancy.defaultExpectation = &VacancyStorageMockArchiveVacancyExpectation{mock: mmArchiveVacancy.mock}
	}
	mmArchiveVacancy.defaultExpectation.results = &VacancyStorageMockArchiveVacancyResults{err}
	mmArchiveVacancy.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmArchiveVacancy.mock
}

// Set uses given function f to mock the VacancyStorage.ArchiveVacancy method
func (mmArchiveVacancy *mVacancyStorageMockArchiveVacancy) Set(f func(ctx context.Context, in domain.ArchiveVacancyInput) (err error)) *VacancyStorageMock {
	if mmArchiveVacancy.defaultExpectation != nil {
		mmArchiveVacancy.mock.t.Fatalf("Default expectation is already set for the VacancyStorage.ArchiveVacancy method")
	}

	if len(mmArchiveVacancy.expectations) > 0 {
		mmArchiveVacancy.mock.t.Fatalf("Some expectations are already set for the VacancyStorage.ArchiveVacancy method")
	}

	mmArchiveVacancy.mock.funcArchiveVacancy = f
	mmArchiveVacancy.mock.funcArchiveVacancyOrigin = minimock.CallerInfo(1)
	return mmArchiveVacancy.mock
}

// When sets expectation for the VacancyStorage.ArchiveVacancy which will trigger the result defined by the following
// Then helper
func (mmArchiveVacancy *mVacancyStorageMockArchiveVacancy) When(ctx context.Context, in domain.ArchiveVacancyInput) *VacancyStorageMockArchiveVacancyExpectation {
	if mmArchiveVacancy.mock.funcArchiveVacancy != nil {
		mmArchiveVacancy.mock.t.Fatalf("VacancyStorageMock.ArchiveVacancy mock is already set by Set")
	}

	expectation := &VacancyStorageMockArchiveVacancyExpectation{
		mock:               mmArchiveVacancy.mock,
		params:             &VacancyStorageMockArchiveVacancyParams{ctx, in},
		expectationOrigins: VacancyStorageMockArchiveVacancyExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmArchiveVacancy.expectations = append(mmArchiveVacancy.expectations, expectation)
	return expectation
}

// Then sets up VacancyStorage.ArchiveVacancy return parameters for the expectation previously defined by the When method
func (e *VacancyStorageMockArchiveVacancyExpectation) Then(err error) *VacancyStorageMock {
	e.results = &VacancyStorageMockArchiveVacancyResults{err}
	return e.mock
}

// Times sets number of times VacancyStorage.ArchiveVacancy should be invoked
func (mmArchiveVacancy *mVacancyStorageMockArchiveVacancy) Times(n uint64) *mVacancyStorageMockArchiveVacancy {
	if n == 0 {
		mmArchiveVacancy.mock.t.Fatalf("Times of VacancyStorageMock.ArchiveVacancy mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmArchiveVacancy.expectedInvocations, n)
	mmArchiveVacancy.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmArchiveVacancy
}

func (mmArchiveVacancy *mVacancyStorageMockArchiveVacancy) invocationsDone() bool {
	if len(mmArchiveVacancy.expectations) == 0 && mmArchiveVacancy.defaultExpectation == nil && mmArchiveVacancy.mock.funcArchiveVacancy == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmArchiveVacancy.mock.afterArchiveVacancyCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmArchiveVacancy.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ArchiveVacancy implements mm_vacancy_service.VacancyStorage
func (mmArchiveVacancy *VacancyStorageMock) ArchiveVacancy(ctx context.Context, in domain.ArchiveVacancyInput) (err error) {
	mm_atomic.AddUint64(&mmArchiveVacancy.beforeArchiveVacancyCounter, 1)
	defer mm_atomic.AddUint64(&mmArchiveVacancy.afterArchiveVacancyCounter, 1)

	mmArchiveVacancy.t.Helper()

	if mmArchiveVacancy.inspectFuncArchiveVacancy != nil {
		mmArchiveVacancy.inspectFuncArchiveVacancy(ctx, in)
	}

	mm_params := VacancyStorageMockArchiveVacancyParams{ctx, in}

	// Record call args
	mmArchiveVacancy.ArchiveVacancyMock.mutex.Lock()
	mmArchiveVacancy.ArchiveVacancyMock.callArgs = append(mmArchiveVacancy.ArchiveVacancyMock.callArgs, &mm_params)
	mmArchiveVacancy.ArchiveVacancyMock.mutex.Unlock()

	for _, e := range mmArchiveVacancy.ArchiveVacancyMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmArchiveVacancy.ArchiveVacancyMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmArchiveVacancy.ArchiveVacancyMock.defaultExpectation.Counter, 1)
		mm_want := mmArchiveVacancy.ArchiveVacancyMock.defaultExpectation.params
		mm_want_ptrs := mmArchiveVacancy.ArchiveVacancyMock.defaultExpectation.paramPtrs

		mm_got := VacancyStorageMockArchiveVacancyParams{ctx, in}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmArchiveVacancy.t.Errorf("VacancyStorageMock.ArchiveVacancy got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmArchiveVacancy.ArchiveVacancyMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmArchiveVacancy.t.Errorf("VacancyStorageMock.ArchiveVacancy got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmArchiveVacancy.ArchiveVacancyMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmArchiveVacancy.t.Errorf("VacancyStorageMock.ArchiveVacancy got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmArchiveVacancy.ArchiveVacancyMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmArchiveVacancy.ArchiveVacancyMock.defaultExpectation.results
		if mm_results == nil {
			mmArchiveVacancy.t.Fatal("No results are set for the VacancyStorageMock.ArchiveVacancy")
		}
		return (*mm_results).err
	}
	if mmArchiveVacancy.funcArchiveVacancy != nil {
		return mmArchiveVacancy.funcArchiveVacancy(ctx, in)
	}
	mmArchiveVacancy.t.Fatalf("Unexpected call to VacancyStorageMock.ArchiveVacancy. %v %v", ctx, in)
	return
}

// ArchiveVacancyAfterCounter returns a count of finished VacancyStorageMock.ArchiveVacancy invocations
func (mmArchiveVacancy *VacancyStorageMock) ArchiveVacancyAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmArchiveVacancy.afterArchiveVacancyCounter)
}

// ArchiveVacancyBeforeCounter returns a count of VacancyStorageMock.ArchiveVacancy invocations
func (mmArchiveVacancy *VacancyStorageMock) ArchiveVacancyBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmArchiveVacancy.beforeArchiveVacancyCounter)
}

// Calls returns a list of arguments used in each call to VacancyStorageMock.ArchiveVacancy.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmArchiveVacancy *mVacancyStorageMockArchiveVacancy) Calls() []*VacancyStorageMockArchiveVacancyParams {
	mmArchiveVacancy.mutex.RLock()

	argCopy := make([]*VacancyStorageMockArchiveVacancyParams, len(mmArchiveVacancy.callArgs))
	copy(argCopy, mmArchiveVacancy.callArgs)

	mmArchiveVacancy.mutex.RUnlock()

	return argCopy
}

// MinimockArchiveVacancyDone returns true if the count of the ArchiveVacancy invocations corresponds
// the number of defined expectations
func (m *VacancyStorageMock) MinimockArchiveVacancyDone() bool {
	if m.ArchiveVacancyMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ArchiveVacancyMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ArchiveVacancyMock.invocationsDone()
}

// MinimockArchiveVacancyInspect logs each unmet expectation
func (m *VacancyStorageMock) MinimockArchiveVacancyInspect() {
	for _, e := range m.ArchiveVacancyMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to VacancyStorageMock.ArchiveVacancy at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterArchiveVacancyCounter := mm_atomic.LoadUint64(&m.afterArchiveVacancyCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ArchiveVacancyMock.defaultExpectation != nil && afterArchiveVacancyCounter < 1 {
		if m.ArchiveVacancyMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to VacancyStorageMock.ArchiveVacancy at\n%s", m.ArchiveVacancyMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to VacancyStorageMock.ArchiveVacancy at\n%s with params: %#v", m.ArchiveVacancyMock.defaultExpectation.expectationOrigins.origin, *m.ArchiveVacancyMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcArchiveVacancy != nil && afterArchiveVacancyCounter < 1 {
		m.t.Errorf("Expected call to VacancyStorageMock.ArchiveVacancy at\n%s", m.funcArchiveVacancyOrigin)
	}

	if !m.ArchiveVacancyMock.invocationsDone() && afterArchiveVacancyCounter > 0 {
		m.t.Errorf("Expected %d calls to VacancyStorageMock.ArchiveVacancy at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ArchiveVacancyMock.expectedInvocations), m.ArchiveVacancyMock.expectedInvocationsOrigin, afterArchiveVacancyCounter)
	}
}

type mVacancyStorageMockCreateVacancy struct {
	optional           bool
	mock               *VacancyStorageMock
	defaultExpectation *VacancyStorageMockCreateVacancyExpectation
	expectations       []*VacancyStorageMockCreateVacancyExpectation

	callArgs []*VacancyStorageMockCreateVacancyParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// VacancyStorageMockCreateVacancyExpectation specifies expectation struct of the VacancyStorage.CreateVacancy
type VacancyStorageMockCreateVacancyExpectation struct {
	mock               *VacancyStorageMock
	params             *VacancyStorageMockCreateVacancyParams
	paramPtrs          *VacancyStorageMockCreateVacancyParamPtrs
	expectationOrigins VacancyStorageMockCreateVacancyExpectationOrigins
	results            *VacancyStorageMockCreateVacancyResults
	returnOrigin       string
	Counter            uint64
}

// VacancyStorageMockCreateVacancyParams contains parameters of the VacancyStorage.CreateVacancy
type VacancyStorageMockCreateVacancyParams struct {
	ctx context.Context
	in  domain.CreateVacancyInput
}

// VacancyStorageMockCreateVacancyParamPtrs contains pointers to parameters of the VacancyStorage.CreateVacancy
type VacancyStorageMockCreateVacancyParamPtrs struct {
	ctx *context.Context
	in  *domain.CreateVacancyInput
}

// VacancyStorageMockCreateVacancyResults contains results of the VacancyStorage.CreateVacancy
type VacancyStorageMockCreateVacancyResults struct {
	vp1 *domain.Vacancy
	err error
}

// VacancyStorageMockCreateVacancyOrigins contains origins of expectations of the VacancyStorage.CreateVacancy
type VacancyStorageMockCreateVacancyExpectationOrigins struct {
	origin    string
	originCtx string
	originIn  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateVacancy *mVacancyStorageMockCreateVacancy) Optional() *mVacancyStorageMockCreateVacancy {
	mmCreateVacancy.optional = true
	return mmCreateVacancy
}

// Expect sets up expected params for VacancyStorage.CreateVacancy
func (mmCreateVacancy *mVacancyStorageMockCreateVacancy) Expect(ctx context.Context, in domain.CreateVacancyInput) *mVacancyStorageMockCreateVacancy {
	if mmCreateVacancy.mock.funcCreateVacancy != nil {
		mmCreateVacancy.mock.t.Fatalf("VacancyStorageMock.CreateVacancy mock is already set by Set")
	}

	if mmCreateVacancy.defaultExpectation == nil {
		mmCreateVacancy.defaultExpectation = &VacancyStorageMockCreateVacancyExpectation{}
	}

	if mmCreateVacancy.defaultExpectation.paramPtrs != nil {
		mmCreateVacancy.mock.t.Fatalf("VacancyStorageMock.CreateVacancy mock is already set by ExpectParams functions")
	}

	mmCreateVacancy.defaultExpectation.params = &VacancyStorageMockCreateVacancyParams{ctx, in}
	mmCreateVacancy.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateVacancy.expectations {
		if minimock.Equal(e.params, mmCreateVacancy.defaultExpectation.params) {
			mmCreateVacancy.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateVacancy.defaultExpectation.params)
		}
	}

	return mmCreateVacancy
}

// ExpectCtxParam1 sets up expected param ctx for VacancyStorage.CreateVacancy
func (mmCreateVacancy *mVacancyStorageMockCreateVacancy) ExpectCtxParam1(ctx context.Context) *mVacancyStorageMockCreateVacancy {
	if mmCreateVacancy.mock.funcCreateVacancy != nil {
		mmCreateVacancy.mock.t.Fatalf("VacancyStorageMock.CreateVacancy mock is already set by Set")
	}

	if mmCreateVacancy.defaultExpectation == nil {
		mmCreateVacancy.defaultExpectation = &VacancyStorageMockCreateVacancyExpectation{}
	}

	if mmCreateVacancy.defaultExpectation.params != nil {
		mmCreateVacancy.mock.t.Fatalf("VacancyStorageMock.CreateVacancy mock is already set by Expect")
	}

	if mmCreateVacancy.defaultExpectation.paramPtrs == nil {
		mmCreateVacancy.defaultExpectation.paramPtrs = &VacancyStorageMockCreateVacancyParamPtrs{}
	}
	mmCreateVacancy.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateVacancy.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateVacancy
}

// ExpectInParam2 sets up expected param in for VacancyStorage.CreateVacancy
func (mmCreateVacancy *mVacancyStorageMockCreateVacancy) ExpectInParam2(in domain.CreateVacancyInput) *mVacancyStorageMockCreateVacancy {
	if mmCreateVacancy.mock.funcCreateVacancy != nil {
		mmCreateVacancy.mock.t.Fatalf("VacancyStorageMock.CreateVacancy mock is already set by Set")
	}

	if mmCreateVacancy.defaultExpectation == nil {
		mmCreateVacancy.defaultExpectation = &VacancyStorageMockCreateVacancyExpectation{}
	}

	if mmCreateVacancy.defaultExpectation.params != nil {
		mmCreateVacancy.mock.t.Fatalf("VacancyStorageMock.CreateVacancy mock is already set by Expect")
	}

	if mmCreateVacancy.defaultExpectation.paramPtrs == nil {
		mmCreateVacancy.defaultExpectation.paramPtrs = &VacancyStorageMockCreateVacancyParamPtrs{}
	}
	mmCreateVacancy.defaultExpectation.paramPtrs.in = &in
	mmCreateVacancy.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmCreateVacancy
}

// Inspect accepts an inspector function that has same arguments as the VacancyStorage.CreateVacancy
func (mmCreateVacancy *mVacancyStorageMockCreateVacancy) Inspect(f func(ctx context.Context, in domain.CreateVacancyInput)) *mVacancyStorageMockCreateVacancy {
	if mmCreateVacancy.mock.inspectFuncCreateVacancy != nil {
		mmCreateVacancy.mock.t.Fatalf("Inspect function is already set for VacancyStorageMock.CreateVacancy")
	}

	mmCreateVacancy.mock.inspectFuncCreateVacancy = f

	return mmCreateVacancy
}

// Return sets up results that will be returned by VacancyStorage.CreateVacancy
func (mmCreateVacancy *mVacancyStorageMockCreateVacancy) Return(vp1 *domain.Vacancy, err error) *VacancyStorageMock {
	if mmCreateVacancy.mock.funcCreateVacancy != nil {
		mmCreateVacancy.mock.t.Fatalf("VacancyStorageMock.CreateVacancy mock is already set by Set")
	}

	if mmCreateVacancy.defaultExpectation == nil {
		mmCreateVacancy.defaultExpectation = &VacancyStorageMockCreateVacancyExpectation{mock: mmCreateVacancy.mock}
	}
	mmCreateVacancy.defaultExpectation.results = &VacancyStorageMockCreateVacancyResults{vp1, err}
	mmCreateVacancy.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateVacancy.mock
}

// Set uses given function f to mock the VacancyStorage.CreateVacancy method
func (mmCreateVacancy *mVacancyStorageMockCreateVacancy) Set(f func(ctx context.Context, in domain.CreateVacancyInput) (vp1 *domain.Vacancy, err error)) *VacancyStorageMock {
	if mmCreateVacancy.defaultExpectation != nil {
		mmCreateVacancy.mock.t.Fatalf("Default expectation is already set for the VacancyStorage.CreateVacancy method")
	}

	if len(mmCreateVacancy.expectations) > 0 {
		mmCreateVacancy.mock.t.Fatalf("Some expectations are already set for the VacancyStorage.CreateVacancy method")
	}

	mmCreateVacancy.mock.funcCreateVacancy = f
	mmCreateVacancy.mock.funcCreateVacancyOrigin = minimock.CallerInfo(1)
	return mmCreateVacancy.mock
}

// When sets expectation for the VacancyStorage.CreateVacancy which will trigger the result defined by the following
// Then helper
func (mmCreateVacancy *mVacancyStorageMockCreateVacancy) When(ctx context.Context, in domain.CreateVacancyInput) *VacancyStorageMockCreateVacancyExpectation {
	if mmCreateVacancy.mock.funcCreateVacancy != nil {
		mmCreateVacancy.mock.t.Fatalf("VacancyStorageMock.CreateVacancy mock is already set by Set")
	}

	expectation := &VacancyStorageMockCreateVacancyExpectation{
		mock:               mmCreateVacancy.mock,
		params:             &VacancyStorageMockCreateVacancyParams{ctx, in},
		expectationOrigins: VacancyStorageMockCreateVacancyExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateVacancy.expectations = append(mmCreateVacancy.expectations, expectation)
	return expectation
}

// Then sets up VacancyStorage.CreateVacancy return parameters for the expectation previously defined by the When method
func (e *VacancyStorageMockCreateVacancyExpectation) Then(vp1 *domain.Vacancy, err error) *VacancyStorageMock {
	e.results = &VacancyStorageMockCreateVacancyResults{vp1, err}
	return e.mock
}

// Times sets number of times VacancyStorage.CreateVacancy should be invoked
func (mmCreateVacancy *mVacancyStorageMockCreateVacancy) Times(n uint64) *mVacancyStorageMockCreateVacancy {
	if n == 0 {
		mmCreateVacancy.mock.t.Fatalf("Times of VacancyStorageMock.CreateVacancy mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateVacancy.expectedInvocations, n)
	mmCreateVacancy.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateVacancy
}

func (mmCreateVacancy *mVacancyStorageMockCreateVacancy) invocationsDone() bool {
	if len(mmCreateVacancy.expectations) == 0 && mmCreateVacancy.defaultExpectation == nil && mmCreateVacancy.mock.funcCreateVacancy == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateVacancy.mock.afterCreateVacancyCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateVacancy.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateVacancy implements mm_vacancy_service.VacancyStorage
func (mmCreateVacancy *VacancyStorageMock) CreateVacancy(ctx context.Context, in domain.CreateVacancyInput) (vp1 *domain.Vacancy, err error) {
	mm_atomic.AddUint64(&mmCreateVacancy.beforeCreateVacancyCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateVacancy.afterCreateVacancyCounter, 1)

	mmCreateVacancy.t.Helper()

	if mmCreateVacancy.inspectFuncCreateVacancy != nil {
		mmCreateVacancy.inspectFuncCreateVacancy(ctx, in)
	}

	mm_params := VacancyStorageMockCreateVacancyParams{ctx, in}

	// Record call args
	mmCreateVacancy.CreateVacancyMock.mutex.Lock()
	mmCreateVacancy.CreateVacancyMock.callArgs = append(mmCreateVacancy.CreateVacancyMock.callArgs, &mm_params)
	mmCreateVacancy.CreateVacancyMock.mutex.Unlock()

	for _, e := range mmCreateVacancy.CreateVacancyMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.vp1, e.results.err
		}
	}

	if mmCreateVacancy.CreateVacancyMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateVacancy.CreateVacancyMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateVacancy.CreateVacancyMock.defaultExpectation.params
		mm_want_ptrs := mmCreateVacancy.CreateVacancyMock.defaultExpectation.paramPtrs

		mm_got := VacancyStorageMockCreateVacancyParams{ctx, in}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateVacancy.t.Errorf("VacancyStorageMock.CreateVacancy got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateVacancy.CreateVacancyMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmCreateVacancy.t.Errorf("VacancyStorageMock.CreateVacancy got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateVacancy.CreateVacancyMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateVacancy.t.Errorf("VacancyStorageMock.CreateVacancy got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateVacancy.CreateVacancyMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateVacancy.CreateVacancyMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateVacancy.t.Fatal("No results are set for the VacancyStorageMock.CreateVacancy")
		}
		return (*mm_results).vp1, (*mm_results).err
	}
	if mmCreateVacancy.funcCreateVacancy != nil {
		return mmCreateVacancy.funcCreateVacancy(ctx, in)
	}
	mmCreateVacancy.t.Fatalf("Unexpected call to VacancyStorageMock.CreateVacancy. %v %v", ctx, in)
	return
}

// CreateVacancyAfterCounter returns a count of finished VacancyStorageMock.CreateVacancy invocations
func (mmCreateVacancy *VacancyStorageMock) CreateVacancyAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateVacancy.afterCreateVacancyCounter)
}

// CreateVacancyBeforeCounter returns a count of VacancyStorageMock.CreateVacancy invocations
func (mmCreateVacancy *VacancyStorageMock) CreateVacancyBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateVacancy.beforeCreateVacancyCounter)
}

// Calls returns a list of arguments used in each call to VacancyStorageMock.CreateVacancy.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateVacancy *mVacancyStorageMockCreateVacancy) Calls() []*VacancyStorageMockCreateVacancyParams {
	mmCreateVacancy.mutex.RLock()

	argCopy := make([]*VacancyStorageMockCreateVacancyParams, len(mmCreateVacancy.callArgs))
	copy(argCopy, mmCreateVacancy.callArgs)

	mmCreateVacancy.mutex.RUnlock()

	return argCopy
}

// MinimockCreateVacancyDone returns true if the count of the CreateVacancy invocations corresponds
// the number of defined expectations
func (m *VacancyStorageMock) MinimockCreateVacancyDone() bool {
	if m.CreateVacancyMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateVacancyMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateVacancyMock.invocationsDone()
}

// MinimockCreateVacancyInspect logs each unmet expectation
func (m *VacancyStorageMock) MinimockCreateVacancyInspect() {
	for _, e := range m.CreateVacancyMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to VacancyStorageMock.CreateVacancy at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateVacancyCounter := mm_atomic.LoadUint64(&m.afterCreateVacancyCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateVacancyMock.defaultExpectation != nil && afterCreateVacancyCounter < 1 {
		if m.CreateVacancyMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to VacancyStorageMock.CreateVacancy at\n%s", m.CreateVacancyMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to VacancyStorageMock.CreateVacancy at\n%s with params: %#v", m.CreateVacancyMock.defaultExpectation.expectationOrigins.origin, *m.CreateVacancyMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateVacancy != nil && afterCreateVacancyCounter < 1 {
		m.t.Errorf("Expected call to VacancyStorageMock.CreateVacancy at\n%s", m.funcCreateVacancyOrigin)
	}

	if !m.CreateVacancyMock.invocationsDone() && afterCreateVacancyCounter > 0 {
		m.t.Errorf("Expected %d calls to VacancyStorageMock.CreateVacancy at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateVacancyMock.expectedInvocations), m.CreateVacancyMock.expectedInvocationsOrigin, afterCreateVacancyCounter)
	}
}

type mVacancyStorageMockGetVacancy struct {
	optional           bool
	mock               *VacancyStorageMock
	defaultExpectation *VacancyStorageMockGetVacancyExpectation
	expectations       []*VacancyStorageMockGetVacancyExpectation

	callArgs []*VacancyStorageMockGetVacancyParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// VacancyStorageMockGetVacancyExpectation specifies expectation struct of the VacancyStorage.GetVacancy
type VacancyStorageMockGetVacancyExpectation struct {
	mock               *VacancyStorageMock
	params             *VacancyStorageMockGetVacancyParams
	paramPtrs          *VacancyStorageMockGetVacancyParamPtrs
	expectationOrigins VacancyStorageMockGetVacancyExpectationOrigins
	results            *VacancyStorageMockGetVacancyResults
	returnOrigin       string
	Counter            uint64
}

// VacancyStorageMockGetVacancyParams contains parameters of the VacancyStorage.GetVacancy
type VacancyStorageMockGetVacancyParams struct {
	ctx         context.Context
	vacancyID   string
	ownerUserID uint64
	isAdmin     bool
}

// VacancyStorageMockGetVacancyParamPtrs contains pointers to parameters of the VacancyStorage.GetVacancy
type VacancyStorageMockGetVacancyParamPtrs struct {
	ctx         *context.Context
	vacancyID   *string
	ownerUserID *uint64
	isAdmin     *bool
}

// VacancyStorageMockGetVacancyResults contains results of the VacancyStorage.GetVacancy
type VacancyStorageMockGetVacancyResults struct {
	vp1 *domain.Vacancy
	err error
}

// VacancyStorageMockGetVacancyOrigins contains origins of expectations of the VacancyStorage.GetVacancy
type VacancyStorageMockGetVacancyExpectationOrigins struct {
	origin            string
	originCtx         string
	originVacancyID   string
	originOwnerUserID string
	originIsAdmin     string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetVacancy *mVacancyStorageMockGetVacancy) Optional() *mVacancyStorageMockGetVacancy {
	mmGetVacancy.optional = true
	return mmGetVacancy
}

// Expect sets up expected params for VacancyStorage.GetVacancy
func (mmGetVacancy *mVacancyStorageMockGetVacancy) Expect(ctx context.Context, vacancyID string, ownerUserID uint64, isAdmin bool) *mVacancyStorageMockGetVacancy {
	if mmGetVacancy.mock.funcGetVacancy != nil {
		mmGetVacancy.mock.t.Fatalf("VacancyStorageMock.GetVacancy mock is already set by Set")
	}

	if mmGetVacancy.defaultExpectation == nil {
		mmGetVacancy.defaultExpectation = &VacancyStorageMockGetVacancyExpectation{}
	}

	if mmGetVacancy.defaultExpectation.paramPtrs != nil {
		mmGetVacancy.mock.t.Fatalf("VacancyStorageMock.GetVacancy mock is already set by ExpectParams functions")
	}

	mmGetVacancy.defaultExpectation.params = &VacancyStorageMockGetVacancyParams{ctx, vacancyID, ownerUserID, isAdmin}
	mmGetVacancy.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetVacancy.expectations {
		if minimock.Equal(e.params, mmGetVacancy.defaultExpectation.params) {
			mmGetVacancy.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetVacancy.defaultExpectation.params)
		}
	}

	return mmGetVacancy
}

// ExpectCtxParam1 sets up expected param ctx for VacancyStorage.GetVacancy
func (mmGetVacancy *mVacancyStorageMockGetVacancy) ExpectCtxParam1(ctx context.Context) *mVacancyStorageMockGetVacancy {
	if mmGetVacancy.mock.funcGetVacancy != nil {
		mmGetVacancy.mock.t.Fatalf("VacancyStorageMock.GetVacancy mock is already set by Set")
	}

	if mmGetVacancy.defaultExpectation == nil {
		mmGetVacancy.defaultExpectation = &VacancyStorageMockGetVacancyExpectation{}
	}

	if mmGetVacancy.defaultExpectation.params != nil {
		mmGetVacancy.mock.t.Fatalf("VacancyStorageMock.GetVacancy mock is already set by Expect")
	}

	if mmGetVacancy.defaultExpectation.paramPtrs == nil {
		mmGetVacancy.defaultExpectation.paramPtrs = &VacancyStorageMockGetVacancyParamPtrs{}
	}
	mmGetVacancy.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetVacancy.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetVacancy
}

// ExpectVacancyIDParam2 sets up expected param vacancyID for VacancyStorage.GetVacancy
func (mmGetVacancy *mVacancyStorageMockGetVacancy) ExpectVacancyIDParam2(vacancyID string) *mVacancyStorageMockGetVacancy {
	if mmGetVacancy.mock.funcGetVacancy != nil {
		mmGetVacancy.mock.t.Fatalf("VacancyStorageMock.GetVacancy mock is already set by Set")
	}

	if mmGetVacancy.defaultExpectation == nil {
		mmGetVacancy.defaultExpectation = &VacancyStorageMockGetVacancyExpectation{}
	}

	if mmGetVacancy.defaultExpectation.params != nil {
		mmGetVacancy.mock.t.Fatalf("VacancyStorageMock.GetVacancy mock is already set by Expect")
	}

	if mmGetVacancy.defaultExpectation.paramPtrs == nil {
		mmGetVacancy.defaultExpectation.paramPtrs = &VacancyStorageMockGetVacancyParamPtrs{}
	}
	mmGetVacancy.defaultExpectation.paramPtrs.vacancyID = &vacancyID
	mmGetVacancy.defaultExpectation.expectationOrigins.originVacancyID = minimock.CallerInfo(1)

	return mmGetVacancy
}

// ExpectOwnerUserIDParam3 sets up expected param ownerUserID for VacancyStorage.GetVacancy
func (mmGetVacancy *mVacancyStorageMockGetVacancy) ExpectOwnerUserIDParam3(ownerUserID uint64) *mVacancyStorageMockGetVacancy {
	if mmGetVacancy.mock.funcGetVacancy != nil {
		mmGetVacancy.mock.t.Fatalf("VacancyStorageMock.GetVacancy mock is already set by Set")
	}

	if mmGetVacancy.defaultExpectation == nil {
		mmGetVacancy.defaultExpectation = &VacancyStorageMockGetVacancyExpectation{}
	}

	if mmGetVacancy.defaultExpectation.params != nil {
		mmGetVacancy.mock.t.Fatalf("VacancyStorageMock.GetVacancy mock is already set by Expect")
	}

	if mmGetVacancy.defaultExpectation.paramPtrs == nil {
		mmGetVacancy.defaultExpectation.paramPtrs = &VacancyStorageMockGetVacancyParamPtrs{}
	}
	mmGetVacancy.defaultExpectation.paramPtrs.ownerUserID = &ownerUserID
	mmGetVacancy.defaultExpectation.expectationOrigins.originOwnerUserID = minimock.CallerInfo(1)

	return mmGetVacancy
}

// ExpectIsAdminParam4 sets up expected param isAdmin for VacancyStorage.GetVacancy
func (mmGetVacancy *mVacancyStorageMockGetVacancy) ExpectIsAdminParam4(isAdmin bool) *mVacancyStorageMockGetVacancy {
	if mmGetVacancy.mock.funcGetVacancy != nil {
		mmGetVacancy.mock.t.Fatalf("VacancyStorageMock.GetVacancy mock is already set by Set")
	}

	if mmGetVacancy.defaultExpectation == nil {
		mmGetVacancy.defaultExpectation = &VacancyStorageMockGetVacancyExpectation{}
	}

	if mmGetVacancy.defaultExpectation.params != nil {
		mmGetVacancy.mock.t.Fatalf("VacancyStorageMock.GetVacancy mock is already set by Expect")
	}

	if mmGetVacancy.defaultExpectation.paramPtrs == nil {
		mmGetVacancy.defaultExpectation.paramPtrs = &VacancyStorageMockGetVacancyParamPtrs{}
	}
	mmGetVacancy.defaultExpectation.paramPtrs.isAdmin = &isAdmin
	mmGetVacancy.defaultExpectation.expectationOrigins.originIsAdmin = minimock.CallerInfo(1)

	return mmGetVacancy
}

// Inspect accepts an inspector function that has same arguments as the VacancyStorage.GetVacancy
func (mmGetVacancy *mVacancyStorageMockGetVacancy) Inspect(f func(ctx context.Context, vacancyID string, ownerUserID uint64, isAdmin bool)) *mVacancyStorageMockGetVacancy {
	if mmGetVacancy.mock.inspectFuncGetVacancy != nil {
		mmGetVacancy.mock.t.Fatalf("Inspect function is already set for VacancyStorageMock.GetVacancy")
	}

	mmGetVacancy.mock.inspectFuncGetVacancy = f

	return mmGetVacancy
}

// Return sets up results that will be returned by VacancyStorage.GetVacancy
func (mmGetVacancy *mVacancyStorageMockGetVacancy) Return(vp1 *domain.Vacancy, err error) *VacancyStorageMock {
	if mmGetVacancy.mock.funcGetVacancy != nil {
		mmGetVacancy.mock.t.Fatalf("VacancyStorageMock.GetVacancy mock is already set by Set")
	}

	if mmGetVacancy.defaultExpectation == nil {
		mmGetVacancy.defaultExpectation = &VacancyStorageMockGetVacancyExpectation{mock: mmGetVacancy.mock}
	}
	mmGetVacancy.defaultExpectation.results = &VacancyStorageMockGetVacancyResults{vp1, err}
	mmGetVacancy.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetVacancy.mock
}

// Set uses given function f to mock the VacancyStorage.GetVacancy method
func (mmGetVacancy *mVacancyStorageMockGetVacancy) Set(f func(ctx context.Context, vacancyID string, ownerUserID uint64, isAdmin bool) (vp1 *domain.Vacancy, err error)) *VacancyStorageMock {
	if mmGetVacancy.defaultExpectation != nil {
		mmGetVacancy.mock.t.Fatalf("Default expectation is already set for the VacancyStorage.GetVacancy method")
	}

	if len(mmGetVacancy.expectations) > 0 {
		mmGetVacancy.mock.t.Fatalf("Some expectations are already set for the VacancyStorage.GetVacancy method")
	}

	mmGetVacancy.mock.funcGetVacancy = f
	mmGetVacancy.mock.funcGetVacancyOrigin = minimock.CallerInfo(1)
	return mmGetVacancy.mock
}

// When sets expectation for the VacancyStorage.GetVacancy which will trigger the result defined by the following
// Then helper
func (mmGetVacancy *mVacancyStorageMockGetVacancy) When(ctx context.Context, vacancyID string, ownerUserID uint64, isAdmin bool) *VacancyStorageMockGetVacancyExpectation {
	if mmGetVacancy.mock.funcGetVacancy != nil {
		mmGetVacancy.mock.t.Fatalf("VacancyStorageMock.GetVacancy mock is already set by Set")
	}

	expectation := &VacancyStorageMockGetVacancyExpectation{
		mock:               mmGetVacancy.mock,
		params:             &VacancyStorageMockGetVacancyParams{ctx, vacancyID, ownerUserID, isAdmin},
		expectationOrigins: VacancyStorageMockGetVacancyExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetVacancy.expectations = append(mmGetVacancy.expectations, expectation)
	return expectation
}

// Then sets up VacancyStorage.GetVacancy return parameters for the expectation previously defined by the When method
func (e *VacancyStorageMockGetVacancyExpectation) Then(vp1 *domain.Vacancy, err error) *VacancyStorageMock {
	e.results = &VacancyStorageMockGetVacancyResults{vp1, err}
	return e.mock
}

// Times sets number of times VacancyStorage.GetVacancy should be invoked
func (mmGetVacancy *mVacancyStorageMockGetVacancy) Times(n uint64) *mVacancyStorageMockGetVacancy {
	if n == 0 {
		mmGetVacancy.mock.t.Fatalf("Times of VacancyStorageMock.GetVacancy mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetVacancy.expectedInvocations, n)
	mmGetVacancy.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetVacancy
}

func (mmGetVacancy *mVacancyStorageMockGetVacancy) invocationsDone() bool {
	if len(mmGetVacancy.expectations) == 0 && mmGetVacancy.defaultExpectation == nil && mmGetVacancy.mock.funcGetVacancy == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetVacancy.mock.afterGetVacancyCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetVacancy.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetVacancy implements mm_vacancy_service.VacancyStorage
func (mmGetVacancy *VacancyStorageMock) GetVacancy(ctx context.Context, vacancyID string, ownerUserID uint64, isAdmin bool) (vp1 *domain.Vacancy, err error) {
	mm_atomic.AddUint64(&mmGetVacancy.beforeGetVacancyCounter, 1)
	defer mm_atomic.AddUint64(&mmGetVacancy.afterGetVacancyCounter, 1)

	mmGetVacancy.t.Helper()

	if mmGetVacancy.inspectFuncGetVacancy != nil {
		mmGetVacancy.inspectFuncGetVacancy(ctx, vacancyID, ownerUserID, isAdmin)
	}

	mm_params := VacancyStorageMockGetVacancyParams{ctx, vacancyID, ownerUserID, isAdmin}

	// Record call args
	mmGetVacancy.GetVacancyMock.mutex.Lock()
	mmGetVacancy.GetVacancyMock.callArgs = append(mmGetVacancy.GetVacancyMock.callArgs, &mm_params)
	mmGetVacancy.GetVacancyMock.mutex.Unlock()

	for _, e := range mmGetVacancy.GetVacancyMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.vp1, e.results.err
		}
	}

	if mmGetVacancy.GetVacancyMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetVacancy.GetVacancyMock.defaultExpectation.Counter, 1)
		mm_want := mmGetVacancy.GetVacancyMock.defaultExpectation.params
		mm_want_ptrs := mmGetVacancy.GetVacancyMock.defaultExpectation.paramPtrs

		mm_got := VacancyStorageMockGetVacancyParams{ctx, vacancyID, ownerUserID, isAdmin}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetVacancy.t.Errorf("VacancyStorageMock.GetVacancy got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetVacancy.GetVacancyMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.vacancyID != nil && !minimock.Equal(*mm_want_ptrs.vacancyID, mm_got.vacancyID) {
				mmGetVacancy.t.Errorf("VacancyStorageMock.GetVacancy got unexpected parameter vacancyID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetVacancy.GetVacancyMock.defaultExpectation.expectationOrigins.originVacancyID, *mm_want_ptrs.vacancyID, mm_got.vacancyID, minimock.Diff(*mm_want_ptrs.vacancyID, mm_got.vacancyID))
			}

			if mm_want_ptrs.ownerUserID != nil && !minimock.Equal(*mm_want_ptrs.ownerUserID, mm_got.ownerUserID) {
				mmGetVacancy.t.Errorf("VacancyStorageMock.GetVacancy got unexpected parameter ownerUserID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetVacancy.GetVacancyMock.defaultExpectation.expectationOrigins.originOwnerUserID, *mm_want_ptrs.ownerUserID, mm_got.ownerUserID, minimock.Diff(*mm_want_ptrs.ownerUserID, mm_got.ownerUserID))
			}

			if mm_want_ptrs.isAdmin != nil && !minimock.Equal(*mm_want_ptrs.isAdmin, mm_got.isAdmin) {
				mmGetVacancy.t.Errorf("VacancyStorageMock.GetVacancy got unexpected parameter isAdmin, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetVacancy.GetVacancyMock.defaultExpectation.expectationOrigins.originIsAdmin, *mm_want_ptrs.isAdmin, mm_got.isAdmin, minimock.Diff(*mm_want_ptrs.isAdmin, mm_got.isAdmin))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetVacancy.t.Errorf("VacancyStorageMock.GetVacancy got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetVacancy.GetVacancyMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetVacancy.GetVacancyMock.defaultExpectation.results
		if mm_results == nil {
			mmGetVacancy.t.Fatal("No results are set for the VacancyStorageMock.GetVacancy")
		}
		return (*mm_results).vp1, (*mm_results).err
	}
	if mmGetVacancy.funcGetVacancy != nil {
		return mmGetVacancy.funcGetVacancy(ctx, vacancyID, ownerUserID, isAdmin)
	}
	mmGetVacancy.t.Fatalf("Unexpected call to VacancyStorageMock.GetVacancy. %v %v %v %v", ctx, vacancyID, ownerUserID, isAdmin)
	return
}

// GetVacancyAfterCounter returns a count of finished VacancyStorageMock.GetVacancy invocations
func (mmGetVacancy *VacancyStorageMock) GetVacancyAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetVacancy.afterGetVacancyCounter)
}

// GetVacancyBeforeCounter returns a count of VacancyStorageMock.GetVacancy invocations
func (mmGetVacancy *VacancyStorageMock) GetVacancyBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetVacancy.beforeGetVacancyCounter)
}

// Calls returns a list of arguments used in each call to VacancyStorageMock.GetVacancy.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetVacancy *mVacancyStorageMockGetVacancy) Calls() []*VacancyStorageMockGetVacancyParams {
	mmGetVacancy.mutex.RLock()

	argCopy := make([]*VacancyStorageMockGetVacancyParams, len(mmGetVacancy.callArgs))
	copy(argCopy, mmGetVacancy.callArgs)

	mmGetVacancy.mutex.RUnlock()

	return argCopy
}

// MinimockGetVacancyDone returns true if the count of the GetVacancy invocations corresponds
// the number of defined expectations
func (m *VacancyStorageMock) MinimockGetVacancyDone() bool {
	if m.GetVacancyMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetVacancyMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetVacancyMock.invocationsDone()
}

// MinimockGetVacancyInspect logs each unmet expectation
func (m *VacancyStorageMock) MinimockGetVacancyInspect() {
	for _, e := range m.GetVacancyMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to VacancyStorageMock.GetVacancy at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetVacancyCounter := mm_atomic.LoadUint64(&m.afterGetVacancyCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetVacancyMock.defaultExpectation != nil && afterGetVacancyCounter < 1 {
		if m.GetVacancyMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to VacancyStorageMock.GetVacancy at\n%s", m.GetVacancyMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to VacancyStorageMock.GetVacancy at\n%s with params: %#v", m.GetVacancyMock.defaultExpectation.expectationOrigins.origin, *m.GetVacancyMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetVacancy != nil && afterGetVacancyCounter < 1 {
		m.t.Errorf("Expected call to VacancyStorageMock.GetVacancy at\n%s", m.funcGetVacancyOrigin)
	}

	if !m.GetVacancyMock.invocationsDone() && afterGetVacancyCounter > 0 {
		m.t.Errorf("Expected %d calls to VacancyStorageMock.GetVacancy at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetVacancyMock.expectedInvocations), m.GetVacancyMock.expectedInvocationsOrigin, afterGetVacancyCounter)
	}
}

type mVacancyStorageMockListVacancies struct {
	optional           bool
	mock               *VacancyStorageMock
	defaultExpectation *VacancyStorageMockListVacanciesExpectation
	expectations       []*VacancyStorageMockListVacanciesExpectation

	callArgs []*VacancyStorageMockListVacanciesParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// VacancyStorageMockListVacanciesExpectation specifies expectation struct of the VacancyStorage.ListVacancies
type VacancyStorageMockListVacanciesExpectation struct {
	mock               *VacancyStorageMock
	params             *VacancyStorageMockListVacanciesParams
	paramPtrs          *VacancyStorageMockListVacanciesParamPtrs
	expectationOrigins VacancyStorageMockListVacanciesExpectationOrigins
	results            *VacancyStorageMockListVacanciesResults
	returnOrigin       string
	Counter            uint64
}

// VacancyStorageMockListVacanciesParams contains parameters of the VacancyStorage.ListVacancies
type VacancyStorageMockListVacanciesParams struct {
	ctx context.Context
	in  domain.ListVacanciesInput
}

// VacancyStorageMockListVacanciesParamPtrs contains pointers to parameters of the VacancyStorage.ListVacancies
type VacancyStorageMockListVacanciesParamPtrs struct {
	ctx *context.Context
	in  *domain.ListVacanciesInput
}

// VacancyStorageMockListVacanciesResults contains results of the VacancyStorage.ListVacancies
type VacancyStorageMockListVacanciesResults struct {
	lp1 *domain.ListVacanciesResult
	err error
}

// VacancyStorageMockListVacanciesOrigins contains origins of expectations of the VacancyStorage.ListVacancies
type VacancyStorageMockListVacanciesExpectationOrigins struct {
	origin    string
	originCtx string
	originIn  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmListVacancies *mVacancyStorageMockListVacancies) Optional() *mVacancyStorageMockListVacancies {
	mmListVacancies.optional = true
	return mmListVacancies
}

// Expect sets up expected params for VacancyStorage.ListVacancies
func (mmListVacancies *mVacancyStorageMockListVacancies) Expect(ctx context.Context, in domain.ListVacanciesInput) *mVacancyStorageMockListVacancies {
	if mmListVacancies.mock.funcListVacancies != nil {
		mmListVacancies.mock.t.Fatalf("VacancyStorageMock.ListVacancies mock is already set by Set")
	}

	if mmListVacancies.defaultExpectation == nil {
		mmListVacancies.defaultExpectation = &VacancyStorageMockListVacanciesExpectation{}
	}

	if mmListVacancies.defaultExpectation.paramPtrs != nil {
		mmListVacancies.mock.t.Fatalf("VacancyStorageMock.ListVacancies mock is already set by ExpectParams functions")
	}

	mmListVacancies.defaultExpectation.params = &VacancyStorageMockListVacanciesParams{ctx, in}
	mmListVacancies.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmListVacancies.expectations {
		if minimock.Equal(e.params, mmListVacancies.defaultExpectation.params) {
			mmListVacancies.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmListVacancies.defaultExpectation.params)
		}
	}

	return mmListVacancies
}

// ExpectCtxParam1 sets up expected param ctx for VacancyStorage.ListVacancies
func (mmListVacancies *mVacancyStorageMockListVacancies) ExpectCtxParam1(ctx context.Context) *mVacancyStorageMockListVacancies {
	if mmListVacancies.mock.funcListVacancies != nil {
		mmListVacancies.mock.t.Fatalf("VacancyStorageMock.ListVacancies mock is already set by Set")
	}

	if mmListVacancies.defaultExpectation == nil {
		mmListVacancies.defaultExpectation = &VacancyStorageMockListVacanciesExpectation{}
	}

	if mmListVacancies.defaultExpectation.params != nil {
		mmListVacancies.mock.t.Fatalf("VacancyStorageMock.ListVacancies mock is already set by Expect")
	}

	if mmListVacancies.defaultExpectation.paramPtrs == nil {
		mmListVacancies.defaultExpectation.paramPtrs = &VacancyStorageMockListVacanciesParamPtrs{}
	}
	mmListVacancies.defaultExpectation.paramPtrs.ctx = &ctx
	mmListVacancies.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmListVacancies
}

// ExpectInParam2 sets up expected param in for VacancyStorage.ListVacancies
func (mmListVacancies *mVacancyStorageMockListVacancies) ExpectInParam2(in domain.ListVacanciesInput) *mVacancyStorageMockListVacancies {
	if mmListVacancies.mock.funcListVacancies != nil {
		mmListVacancies.mock.t.Fatalf("VacancyStorageMock.ListVacancies mock is already set by Set")
	}

	if mmListVacancies.defaultExpectation == nil {
		mmListVacancies.defaultExpectation = &VacancyStorageMockListVacanciesExpectation{}
	}

	if mmListVacancies.defaultExpectation.params != nil {
		mmListVacancies.mock.t.Fatalf("VacancyStorageMock.ListVacancies mock is already set by Expect")
	}

	if mmListVacancies.defaultExpectation.paramPtrs == nil {
		mmListVacancies.defaultExpectation.paramPtrs = &VacancyStorageMockListVacanciesParamPtrs{}
	}
	mmListVacancies.defaultExpectation.paramPtrs.in = &in
	mmListVacancies.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmListVacancies
}

// Inspect accepts an inspector function that has same arguments as the VacancyStorage.ListVacancies
func (mmListVacancies *mVacancyStorageMockListVacancies) Inspect(f func(ctx context.Context, in domain.ListVacanciesInput)) *mVacancyStorageMockListVacancies {
	if mmListVacancies.mock.inspectFuncListVacancies != nil {
		mmListVacancies.mock.t.Fatalf("Inspect function is already set for VacancyStorageMock.ListVacancies")
	}

	mmListVacancies.mock.inspectFuncListVacancies = f

	return mmListVacancies
}

// Return sets up results that will be returned by VacancyStorage.ListVacancies
func (mmListVacancies *mVacancyStorageMockListVacancies) Return(lp1 *domain.ListVacanciesResult, err error) *VacancyStorageMock {
	if mmListVacancies.mock.funcListVacancies != nil {
		mmListVacancies.mock.t.Fatalf("VacancyStorageMock.ListVacancies mock is already set by Set")
	}

	if mmListVacancies.defaultExpectation == nil {
		mmListVacancies.defaultExpectation = &VacancyStorageMockListVacanciesExpectation{mock: mmListVacancies.mock}
	}
	mmListVacancies.defaultExpectation.results = &VacancyStorageMockListVacanciesResults{lp1, err}
	mmListVacancies.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmListVacancies.mock
}

// Set uses given function f to mock the VacancyStorage.ListVacancies method
func (mmListVacancies *mVacancyStorageMockListVacancies) Set(f func(ctx context.Context, in domain.ListVacanciesInput) (lp1 *domain.ListVacanciesResult, err error)) *VacancyStorageMock {
	if mmListVacancies.defaultExpectation != nil {
		mmListVacancies.mock.t.Fatalf("Default expectation is already set for the VacancyStorage.ListVacancies method")
	}

	if len(mmListVacancies.expectations) > 0 {
		mmListVacancies.mock.t.Fatalf("Some expectations are already set for the VacancyStorage.ListVacancies method")
	}

	mmListVacancies.mock.funcListVacancies = f
	mmListVacancies.mock.funcListVacanciesOrigin = minimock.CallerInfo(1)
	return mmListVacancies.mock
}

// When sets expectation for the VacancyStorage.ListVacancies which will trigger the result defined by the following
// Then helper
func (mmListVacancies *mVacancyStorageMockListVacancies) When(ctx context.Context, in domain.ListVacanciesInput) *VacancyStorageMockListVacanciesExpectation {
	if mmListVacancies.mock.funcListVacancies != nil {
		mmListVacancies.mock.t.Fatalf("VacancyStorageMock.ListVacancies mock is already set by Set")
	}

	expectation := &VacancyStorageMockListVacanciesExpectation{
		mock:               mmListVacancies.mock,
		params:             &VacancyStorageMockListVacanciesParams{ctx, in},
		expectationOrigins: VacancyStorageMockListVacanciesExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmListVacancies.expectations = append(mmListVacancies.expectations, expectation)
	return expectation
}

// Then sets up VacancyStorage.ListVacancies return parameters for the expectation previously defined by the When method
func (e *VacancyStorageMockListVacanciesExpectation) Then(lp1 *domain.ListVacanciesResult, err error) *VacancyStorageMock {
	e.results = &VacancyStorageMockListVacanciesResults{lp1, err}
	return e.mock
}

// Times sets number of times VacancyStorage.ListVacancies should be invoked
func (mmListVacancies *mVacancyStorageMockListVacancies) Times(n uint64) *mVacancyStorageMockListVacancies {
	if n == 0 {
		mmListVacancies.mock.t.Fatalf("Times of VacancyStorageMock.ListVacancies mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmListVacancies.expectedInvocations, n)
	mmListVacancies.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmListVacancies
}

func (mmListVacancies *mVacancyStorageMockListVacancies) invocationsDone() bool {
	if len(mmListVacancies.expectations) == 0 && mmListVacancies.defaultExpectation == nil && mmListVacancies.mock.funcListVacancies == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmListVacancies.mock.afterListVacanciesCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmListVacancies.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ListVacancies implements mm_vacancy_service.VacancyStorage
func (mmListVacancies *VacancyStorageMock) ListVacancies(ctx context.Context, in domain.ListVacanciesInput) (lp1 *domain.ListVacanciesResult, err error) {
	mm_atomic.AddUint64(&mmListVacancies.beforeListVacanciesCounter, 1)
	defer mm_atomic.AddUint64(&mmListVacancies.afterListVacanciesCounter, 1)

	mmListVacancies.t.Helper()

	if mmListVacancies.inspectFuncListVacancies != nil {
		mmListVacancies.inspectFuncListVacancies(ctx, in)
	}

	mm_params := VacancyStorageMockListVacanciesParams{ctx, in}

	// Record call args
	mmListVacancies.ListVacanciesMock.mutex.Lock()
	mmListVacancies.ListVacanciesMock.callArgs = append(mmListVacancies.ListVacanciesMock.callArgs, &mm_params)
	mmListVacancies.ListVacanciesMock.mutex.Unlock()

	for _, e := range mmListVacancies.ListVacanciesMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.lp1, e.results.err
		}
	}

	if mmListVacancies.ListVacanciesMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmListVacancies.ListVacanciesMock.defaultExpectation.Counter, 1)
		mm_want := mmListVacancies.ListVacanciesMock.defaultExpectation.params
		mm_want_ptrs := mmListVacancies.ListVacanciesMock.defaultExpectation.paramPtrs

		mm_got := VacancyStorageMockListVacanciesParams{ctx, in}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmListVacancies.t.Errorf("VacancyStorageMock.ListVacancies got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListVacancies.ListVacanciesMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmListVacancies.t.Errorf("VacancyStorageMock.ListVacancies got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListVacancies.ListVacanciesMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmListVacancies.t.Errorf("VacancyStorageMock.ListVacancies got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmListVacancies.ListVacanciesMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmListVacancies.ListVacanciesMock.defaultExpectation.results
		if mm_results == nil {
			mmListVacancies.t.Fatal("No results are set for the VacancyStorageMock.ListVacancies")
		}
		return (*mm_results).lp1, (*mm_results).err
	}
	if mmListVacancies.funcListVacancies != nil {
		return mmListVacancies.funcListVacancies(ctx, in)
	}
	mmListVacancies.t.Fatalf("Unexpected call to VacancyStorageMock.ListVacancies. %v %v", ctx, in)
	return
}

// ListVacanciesAfterCounter returns a count of finished VacancyStorageMock.ListVacancies invocations
func (mmListVacancies *VacancyStorageMock) ListVacanciesAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListVacancies.afterListVacanciesCounter)
}

// ListVacanciesBeforeCounter returns a count of VacancyStorageMock.ListVacancies invocations
func (mmListVacancies *VacancyStorageMock) ListVacanciesBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListVacancies.beforeListVacanciesCounter)
}

// Calls returns a list of arguments used in each call to VacancyStorageMock.ListVacancies.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmListVacancies *mVacancyStorageMockListVacancies) Calls() []*VacancyStorageMockListVacanciesParams {
	mmListVacancies.mutex.RLock()

	argCopy := make([]*VacancyStorageMockListVacanciesParams, len(mmListVacancies.callArgs))
	copy(argCopy, mmListVacancies.callArgs)

	mmListVacancies.mutex.RUnlock()

	return argCopy
}

// MinimockListVacanciesDone returns true if the count of the ListVacancies invocations corresponds
// the number of defined expectations
func (m *VacancyStorageMock) MinimockListVacanciesDone() bool {
	if m.ListVacanciesMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ListVacanciesMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ListVacanciesMock.invocationsDone()
}

// MinimockListVacanciesInspect logs each unmet expectation
func (m *VacancyStorageMock) MinimockListVacanciesInspect() {
	for _, e := range m.ListVacanciesMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to VacancyStorageMock.ListVacancies at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterListVacanciesCounter := mm_atomic.LoadUint64(&m.afterListVacanciesCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ListVacanciesMock.defaultExpectation != nil && afterListVacanciesCounter < 1 {
		if m.ListVacanciesMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to VacancyStorageMock.ListVacancies at\n%s", m.ListVacanciesMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to VacancyStorageMock.ListVacancies at\n%s with params: %#v", m.ListVacanciesMock.defaultExpectation.expectationOrigins.origin, *m.ListVacanciesMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcListVacancies != nil && afterListVacanciesCounter < 1 {
		m.t.Errorf("Expected call to VacancyStorageMock.ListVacancies at\n%s", m.funcListVacanciesOrigin)
	}

	if !m.ListVacanciesMock.invocationsDone() && afterListVacanciesCounter > 0 {
		m.t.Errorf("Expected %d calls to VacancyStorageMock.ListVacancies at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ListVacanciesMock.expectedInvocations), m.ListVacanciesMock.expectedInvocationsOrigin, afterListVacanciesCounter)
	}
}

type mVacancyStorageMockUpdateVacancy struct {
	optional           bool
	mock               *VacancyStorageMock
	defaultExpectation *VacancyStorageMockUpdateVacancyExpectation
	expectations       []*VacancyStorageMockUpdateVacancyExpectation

	callArgs []*VacancyStorageMockUpdateVacancyParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// VacancyStorageMockUpdateVacancyExpectation specifies expectation struct of the VacancyStorage.UpdateVacancy
type VacancyStorageMockUpdateVacancyExpectation struct {
	mock               *VacancyStorageMock
	params             *VacancyStorageMockUpdateVacancyParams
	paramPtrs          *VacancyStorageMockUpdateVacancyParamPtrs
	expectationOrigins VacancyStorageMockUpdateVacancyExpectationOrigins
	results            *VacancyStorageMockUpdateVacancyResults
	returnOrigin       string
	Counter            uint64
}

// VacancyStorageMockUpdateVacancyParams contains parameters of the VacancyStorage.UpdateVacancy
type VacancyStorageMockUpdateVacancyParams struct {
	ctx context.Context
	in  domain.UpdateVacancyInput
}

// VacancyStorageMockUpdateVacancyParamPtrs contains pointers to parameters of the VacancyStorage.UpdateVacancy
type VacancyStorageMockUpdateVacancyParamPtrs struct {
	ctx *context.Context
	in  *domain.UpdateVacancyInput
}

// VacancyStorageMockUpdateVacancyResults contains results of the VacancyStorage.UpdateVacancy
type VacancyStorageMockUpdateVacancyResults struct {
	vp1 *domain.Vacancy
	err error
}

// VacancyStorageMockUpdateVacancyOrigins contains origins of expectations of the VacancyStorage.UpdateVacancy
type VacancyStorageMockUpdateVacancyExpectationOrigins struct {
	origin    string
	originCtx string
	originIn  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdateVacancy *mVacancyStorageMockUpdateVacancy) Optional() *mVacancyStorageMockUpdateVacancy {
	mmUpdateVacancy.optional = true
	return mmUpdateVacancy
}

// Expect sets up expected params for VacancyStorage.UpdateVacancy
func (mmUpdateVacancy *mVacancyStorageMockUpdateVacancy) Expect(ctx context.Context, in domain.UpdateVacancyInput) *mVacancyStorageMockUpdateVacancy {
	if mmUpdateVacancy.mock.funcUpdateVacancy != nil {
		mmUpdateVacancy.mock.t.Fatalf("VacancyStorageMock.UpdateVacancy mock is already set by Set")
	}

	if mmUpdateVacancy.defaultExpectation == nil {
		mmUpdateVacancy.defaultExpectation = &VacancyStorageMockUpdateVacancyExpectation{}
	}

	if mmUpdateVacancy.defaultExpectation.paramPtrs != nil {
		mmUpdateVacancy.mock.t.Fatalf("VacancyStorageMock.UpdateVacancy mock is already set by ExpectParams functions")
	}

	mmUpdateVacancy.defaultExpectation.params = &VacancyStorageMockUpdateVacancyParams{ctx, in}
	mmUpdateVacancy.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUpdateVacancy.expectations {
		if minimock.Equal(e.params, mmUpdateVacancy.defaultExpectation.params) {
			mmUpdateVacancy.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdateVacancy.defaultExpectation.params)
		}
	}

	return mmUpdateVacancy
}

// ExpectCtxParam1 sets up expected param ctx for VacancyStorage.UpdateVacancy
func (mmUpdateVacancy *mVacancyStorageMockUpdateVacancy) ExpectCtxParam1(ctx context.Context) *mVacancyStorageMockUpdateVacancy {
	if mmUpdateVacancy.mock.funcUpdateVacancy != nil {
		mmUpdateVacancy.mock.t.Fatalf("VacancyStorageMock.UpdateVacancy mock is already set by Set")
	}

	if mmUpdateVacancy.defaultExpectation == nil {
		mmUpdateVacancy.defaultExpectation = &VacancyStorageMockUpdateVacancyExpectation{}
	}

	if mmUpdateVacancy.defaultExpectation.params != nil {
		mmUpdateVacancy.mock.t.Fatalf("VacancyStorageMock.UpdateVacancy mock is already set by Expect")
	}

	if mmUpdateVacancy.defaultExpectation.paramPtrs == nil {
		mmUpdateVacancy.defaultExpectation.paramPtrs = &VacancyStorageMockUpdateVacancyParamPtrs{}
	}
	mmUpdateVacancy.defaultExpectation.paramPtrs.ctx = &ctx
	mmUpdateVacancy.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUpdateVacancy
}

// ExpectInParam2 sets up expected param in for VacancyStorage.UpdateVacancy
func (mmUpdateVacancy *mVacancyStorageMockUpdateVacancy) ExpectInParam2(in domain.UpdateVacancyInput) *mVacancyStorageMockUpdateVacancy {
	if mmUpdateVacancy.mock.funcUpdateVacancy != nil {
		mmUpdateVacancy.mock.t.Fatalf("VacancyStorageMock.UpdateVacancy mock is already set by Set")
	}

	if mmUpdateVacancy.defaultExpectation == nil {
		mmUpdateVacancy.defaultExpectation = &VacancyStorageMockUpdateVacancyExpectation{}
	}

	if mmUpdateVacancy.defaultExpectation.params != nil {
		mmUpdateVacancy.mock.t.Fatalf("VacancyStorageMock.UpdateVacancy mock is already set by Expect")
	}

	if mmUpdateVacancy.defaultExpectation.paramPtrs == nil {
		mmUpdateVacancy.defaultExpectation.paramPtrs = &VacancyStorageMockUpdateVacancyParamPtrs{}
	}
	mmUpdateVacancy.defaultExpectation.paramPtrs.in = &in
	mmUpdateVacancy.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmUpdateVacancy
}

// Inspect accepts an inspector function that has same arguments as the VacancyStorage.UpdateVacancy
func (mmUpdateVacancy *mVacancyStorageMockUpdateVacancy) Inspect(f func(ctx context.Context, in domain.UpdateVacancyInput)) *mVacancyStorageMockUpdateVacancy {
	if mmUpdateVacancy.mock.inspectFuncUpdateVacancy != nil {
		mmUpdateVacancy.mock.t.Fatalf("Inspect function is already set for VacancyStorageMock.UpdateVacancy")
	}

	mmUpdateVacancy.mock.inspectFuncUpdateVacancy = f

	return mmUpdateVacancy
}

// Return sets up results that will be returned by VacancyStorage.UpdateVacancy
func (mmUpdateVacancy *mVacancyStorageMockUpdateVacancy) Return(vp1 *domain.Vacancy, err error) *VacancyStorageMock {
	if mmUpdateVacancy.mock.funcUpdateVacancy != nil {
		mmUpdateVacancy.mock.t.Fatalf("VacancyStorageMock.UpdateVacancy mock is already set by Set")
	}

	if mmUpdateVacancy.defaultExpectation == nil {
		mmUpdateVacancy.defaultExpectation = &VacancyStorageMockUpdateVacancyExpectation{mock: mmUpdateVacancy.mock}
	}
	mmUpdateVacancy.defaultExpectation.results = &VacancyStorageMockUpdateVacancyResults{vp1, err}
	mmUpdateVacancy.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpdateVacancy.mock
}

// Set uses given function f to mock the VacancyStorage.UpdateVacancy method
func (mmUpdateVacancy *mVacancyStorageMockUpdateVacancy) Set(f func(ctx context.Context, in domain.UpdateVacancyInput) (vp1 *domain.Vacancy, err error)) *VacancyStorageMock {
	if mmUpdateVacancy.defaultExpectation != nil {
		mmUpdateVacancy.mock.t.Fatalf("Default expectation is already set for the VacancyStorage.UpdateVacancy method")
	}

	if len(mmUpdateVacancy.expectations) > 0 {
		mmUpdateVacancy.mock.t.Fatalf("Some expectations are already set for the VacancyStorage.UpdateVacancy method")
	}

	mmUpdateVacancy.mock.funcUpdateVacancy = f
	mmUpdateVacancy.mock.funcUpdateVacancyOrigin = minimock.CallerInfo(1)
	return mmUpdateVacancy.mock
}

// When sets expectation for the VacancyStorage.UpdateVacancy which will trigger the result defined by the following
// Then helper
func (mmUpdateVacancy *mVacancyStorageMockUpdateVacancy) When(ctx context.Context, in domain.UpdateVacancyInput) *VacancyStorageMockUpdateVacancyExpectation {
	if mmUpdateVacancy.mock.funcUpdateVacancy != nil {
		mmUpdateVacancy.mock.t.Fatalf("VacancyStorageMock.UpdateVacancy mock is already set by Set")
	}

	expectation := &VacancyStorageMockUpdateVacancyExpectation{
		mock:               mmUpdateVacancy.mock,
		params:             &VacancyStorageMockUpdateVacancyParams{ctx, in},
		expectationOrigins: VacancyStorageMockUpdateVacancyExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUpdateVacancy.expectations = append(mmUpdateVacancy.expectations, expectation)
	return expectation
}

// Then sets up VacancyStorage.UpdateVacancy return parameters for the expectation previously defined by the When method
func (e *VacancyStorageMockUpdateVacancyExpectation) Then(vp1 *domain.Vacancy, err error) *VacancyStorageMock {
	e.results = &VacancyStorageMockUpdateVacancyResults{vp1, err}
	return e.mock
}

// Times sets number of times VacancyStorage.UpdateVacancy should be invoked
func (mmUpdateVacancy *mVacancyStorageMockUpdateVacancy) Times(n uint64) *mVacancyStorageMockUpdateVacancy {
	if n == 0 {
		mmUpdateVacancy.mock.t.Fatalf("Times of VacancyStorageMock.UpdateVacancy mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdateVacancy.expectedInvocations, n)
	mmUpdateVacancy.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpdateVacancy
}

func (mmUpdateVacancy *mVacancyStorageMockUpdateVacancy) invocationsDone() bool {
	if len(mmUpdateVacancy.expectations) == 0 && mmUpdateVacancy.defaultExpectation == nil && mmUpdateVacancy.mock.funcUpdateVacancy == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdateVacancy.mock.afterUpdateVacancyCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdateVacancy.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// UpdateVacancy implements mm_vacancy_service.VacancyStorage
func (mmUpdateVacancy *VacancyStorageMock) UpdateVacancy(ctx context.Context, in domain.UpdateVacancyInput) (vp1 *domain.Vacancy, err error) {
	mm_atomic.AddUint64(&mmUpdateVacancy.beforeUpdateVacancyCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdateVacancy.afterUpdateVacancyCounter, 1)

	mmUpdateVacancy.t.Helper()

	if mmUpdateVacancy.inspectFuncUpdateVacancy != nil {
		mmUpdateVacancy.inspectFuncUpdateVacancy(ctx, in)
	}

	mm_params := VacancyStorageMockUpdateVacancyParams{ctx, in}

	// Record call args
	mmUpdateVacancy.UpdateVacancyMock.mutex.Lock()
	mmUpdateVacancy.UpdateVacancyMock.callArgs = append(mmUpdateVacancy.UpdateVacancyMock.callArgs, &mm_params)
	mmUpdateVacancy.UpdateVacancyMock.mutex.Unlock()

	for _, e := range mmUpdateVacancy.UpdateVacancyMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.vp1, e.results.err
		}
	}

	if mmUpdateVacancy.UpdateVacancyMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdateVacancy.UpdateVacancyMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdateVacancy.UpdateVacancyMock.defaultExpectation.params
		mm_want_ptrs := mmUpdateVacancy.UpdateVacancyMock.defaultExpectation.paramPtrs

		mm_got := VacancyStorageMockUpdateVacancyParams{ctx, in}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUpdateVacancy.t.Errorf("VacancyStorageMock.UpdateVacancy got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateVacancy.UpdateVacancyMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmUpdateVacancy.t.Errorf("VacancyStorageMock.UpdateVacancy got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateVacancy.UpdateVacancyMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdateVacancy.t.Errorf("VacancyStorageMock.UpdateVacancy got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUpdateVacancy.UpdateVacancyMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdateVacancy.UpdateVacancyMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdateVacancy.t.Fatal("No results are set for the VacancyStorageMock.UpdateVacancy")
		}
		return (*mm_results).vp1, (*mm_results).err
	}
	if mmUpdateVacancy.funcUpdateVacancy != nil {
		return mmUpdateVacancy.funcUpdateVacancy(ctx, in)
	}
	mmUpdateVacancy.t.Fatalf("Unexpected call to VacancyStorageMock.UpdateVacancy. %v %v", ctx, in)
	return
}

// UpdateVacancyAfterCounter returns a count of finished VacancyStorageMock.UpdateVacancy invocations
func (mmUpdateVacancy *VacancyStorageMock) UpdateVacancyAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateVacancy.afterUpdateVacancyCounter)
}

// UpdateVacancyBeforeCounter returns a count of VacancyStorageMock.UpdateVacancy invocations
func (mmUpdateVacancy *VacancyStorageMock) UpdateVacancyBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateVacancy.beforeUpdateVacancyCounter)
}

// Calls returns a list of arguments used in each call to VacancyStorageMock.UpdateVacancy.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdateVacancy *mVacancyStorageMockUpdateVacancy) Calls() []*VacancyStorageMockUpdateVacancyParams {
	mmUpdateVacancy.mutex.RLock()

	argCopy := make([]*VacancyStorageMockUpdateVacancyParams, len(mmUpdateVacancy.callArgs))
	copy(argCopy, mmUpdateVacancy.callArgs)

	mmUpdateVacancy.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateVacancyDone returns true if the count of the UpdateVacancy invocations corresponds
// the number of defined expectations
func (m *VacancyStorageMock) MinimockUpdateVacancyDone() bool {
	if m.UpdateVacancyMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdateVacancyMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdateVacancyMock.invocationsDone()
}

// MinimockUpdateVacancyInspect logs each unmet expectation
func (m *VacancyStorageMock) MinimockUpdateVacancyInspect() {
	for _, e := range m.UpdateVacancyMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to VacancyStorageMock.UpdateVacancy at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUpdateVacancyCounter := mm_atomic.LoadUint64(&m.afterUpdateVacancyCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateVacancyMock.defaultExpectation != nil && afterUpdateVacancyCounter < 1 {
		if m.UpdateVacancyMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to VacancyStorageMock.UpdateVacancy at\n%s", m.UpdateVacancyMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to VacancyStorageMock.UpdateVacancy at\n%s with params: %#v", m.UpdateVacancyMock.defaultExpectation.expectationOrigins.origin, *m.UpdateVacancyMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdateVacancy != nil && afterUpdateVacancyCounter < 1 {
		m.t.Errorf("Expected call to VacancyStorageMock.UpdateVacancy at\n%s", m.funcUpdateVacancyOrigin)
	}

	if !m.UpdateVacancyMock.invocationsDone() && afterUpdateVacancyCounter > 0 {
		m.t.Errorf("Expected %d calls to VacancyStorageMock.UpdateVacancy at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpdateVacancyMock.expectedInvocations), m.UpdateVacancyMock.expectedInvocationsOrigin, afterUpdateVacancyCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *VacancyStorageMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockArchiveVacancyInspect()

			m.MinimockCreateVacancyInspect()

			m.MinimockGetVacancyInspect()

			m.MinimockListVacanciesInspect()

			m.MinimockUpdateVacancyInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *VacancyStorageMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *VacancyStorageMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockArchiveVacancyDone() &&
		m.MinimockCreateVacancyDone() &&
		m.MinimockGetVacancyDone() &&
		m.MinimockListVacanciesDone() &&
		m.MinimockUpdateVacancyDone()
}
