// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: models/analysis_model.proto

package models

import (
	common "github.com/artem13815/hr/analysis/internal/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalysisStatus int32

const (
	AnalysisStatus_ANALYSIS_STATUS_UNSPECIFIED AnalysisStatus = 0
	AnalysisStatus_ANALYSIS_STATUS_QUEUED      AnalysisStatus = 1
	AnalysisStatus_ANALYSIS_STATUS_RUNNING     AnalysisStatus = 2
	AnalysisStatus_ANALYSIS_STATUS_DONE        AnalysisStatus = 3
	AnalysisStatus_ANALYSIS_STATUS_FAILED      AnalysisStatus = 4
)

// Enum value maps for AnalysisStatus.
var (
	AnalysisStatus_name = map[int32]string{
		0: "ANALYSIS_STATUS_UNSPECIFIED",
		1: "ANALYSIS_STATUS_QUEUED",
		2: "ANALYSIS_STATUS_RUNNING",
		3: "ANALYSIS_STATUS_DONE",
		4: "ANALYSIS_STATUS_FAILED",
	}
	AnalysisStatus_value = map[string]int32{
		"ANALYSIS_STATUS_UNSPECIFIED": 0,
		"ANALYSIS_STATUS_QUEUED":      1,
		"ANALYSIS_STATUS_RUNNING":     2,
		"ANALYSIS_STATUS_DONE":        3,
		"ANALYSIS_STATUS_FAILED":      4,
	}
)

func (x AnalysisStatus) Enum() *AnalysisStatus {
	p := new(AnalysisStatus)
	*p = x
	return p
}

func (x AnalysisStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnalysisStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_models_analysis_model_proto_enumTypes[0].Descriptor()
}

func (AnalysisStatus) Type() protoreflect.EnumType {
	return &file_models_analysis_model_proto_enumTypes[0]
}

func (x AnalysisStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnalysisStatus.Descriptor instead.
func (AnalysisStatus) EnumDescriptor() ([]byte, []int) {
	return file_models_analysis_model_proto_rawDescGZIP(), []int{0}
}

type CandidateProfile struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Skills          []string               `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	YearsExperience float32                `protobuf:"fixed32,2,opt,name=years_experience,json=yearsExperience,proto3" json:"years_experience,omitempty"`
	Positions       []string               `protobuf:"bytes,3,rep,name=positions,proto3" json:"positions,omitempty"`
	Technologies    []string               `protobuf:"bytes,4,rep,name=technologies,proto3" json:"technologies,omitempty"`
	Education       []string               `protobuf:"bytes,5,rep,name=education,proto3" json:"education,omitempty"`
	Summary         string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CandidateProfile) Reset() {
	*x = CandidateProfile{}
	mi := &file_models_analysis_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateProfile) ProtoMessage() {}

func (x *CandidateProfile) ProtoReflect() protoreflect.Message {
	mi := &file_models_analysis_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateProfile.ProtoReflect.Descriptor instead.
func (*CandidateProfile) Descriptor() ([]byte, []int) {
	return file_models_analysis_model_proto_rawDescGZIP(), []int{0}
}

func (x *CandidateProfile) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *CandidateProfile) GetYearsExperience() float32 {
	if x != nil {
		return x.YearsExperience
	}
	return 0
}

func (x *CandidateProfile) GetPositions() []string {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *CandidateProfile) GetTechnologies() []string {
	if x != nil {
		return x.Technologies
	}
	return nil
}

func (x *CandidateProfile) GetEducation() []string {
	if x != nil {
		return x.Education
	}
	return nil
}

func (x *CandidateProfile) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ScoreBreakdown struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MatchedSkills   []string               `protobuf:"bytes,1,rep,name=matched_skills,json=matchedSkills,proto3" json:"matched_skills,omitempty"`
	MissingSkills   []string               `protobuf:"bytes,2,rep,name=missing_skills,json=missingSkills,proto3" json:"missing_skills,omitempty"`
	ExtraSkills     []string               `protobuf:"bytes,3,rep,name=extra_skills,json=extraSkills,proto3" json:"extra_skills,omitempty"`
	BaseScore       float32                `protobuf:"fixed32,4,opt,name=base_score,json=baseScore,proto3" json:"base_score,omitempty"`
	MustHavePenalty float32                `protobuf:"fixed32,5,opt,name=must_have_penalty,json=mustHavePenalty,proto3" json:"must_have_penalty,omitempty"`
	NiceToHaveBonus float32                `protobuf:"fixed32,6,opt,name=nice_to_have_bonus,json=niceToHaveBonus,proto3" json:"nice_to_have_bonus,omitempty"`
	Explanation     string                 `protobuf:"bytes,7,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScoreBreakdown) Reset() {
	*x = ScoreBreakdown{}
	mi := &file_models_analysis_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreBreakdown) ProtoMessage() {}

func (x *ScoreBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_models_analysis_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreBreakdown.ProtoReflect.Descriptor instead.
func (*ScoreBreakdown) Descriptor() ([]byte, []int) {
	return file_models_analysis_model_proto_rawDescGZIP(), []int{1}
}

func (x *ScoreBreakdown) GetMatchedSkills() []string {
	if x != nil {
		return x.MatchedSkills
	}
	return nil
}

func (x *ScoreBreakdown) GetMissingSkills() []string {
	if x != nil {
		return x.MissingSkills
	}
	return nil
}

func (x *ScoreBreakdown) GetExtraSkills() []string {
	if x != nil {
		return x.ExtraSkills
	}
	return nil
}

func (x *ScoreBreakdown) GetBaseScore() float32 {
	if x != nil {
		return x.BaseScore
	}
	return 0
}

func (x *ScoreBreakdown) GetMustHavePenalty() float32 {
	if x != nil {
		return x.MustHavePenalty
	}
	return 0
}

func (x *ScoreBreakdown) GetNiceToHaveBonus() float32 {
	if x != nil {
		return x.NiceToHaveBonus
	}
	return 0
}

func (x *ScoreBreakdown) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

type AgentResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentName      string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Summary        string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	StructuredJson string                 `protobuf:"bytes,3,opt,name=structured_json,json=structuredJson,proto3" json:"structured_json,omitempty"`
	Confidence     float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentResult) Reset() {
	*x = AgentResult{}
	mi := &file_models_analysis_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResult) ProtoMessage() {}

func (x *AgentResult) ProtoReflect() protoreflect.Message {
	mi := &file_models_analysis_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResult.ProtoReflect.Descriptor instead.
func (*AgentResult) Descriptor() ([]byte, []int) {
	return file_models_analysis_model_proto_rawDescGZIP(), []int{2}
}

func (x *AgentResult) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentResult) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AgentResult) GetStructuredJson() string {
	if x != nil {
		return x.StructuredJson
	}
	return ""
}

func (x *AgentResult) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type AIDecision struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HrRecommendation  string                 `protobuf:"bytes,1,opt,name=hr_recommendation,json=hrRecommendation,proto3" json:"hr_recommendation,omitempty"`
	Confidence        float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	HrRationale       string                 `protobuf:"bytes,3,opt,name=hr_rationale,json=hrRationale,proto3" json:"hr_rationale,omitempty"`
	CandidateFeedback string                 `protobuf:"bytes,4,opt,name=candidate_feedback,json=candidateFeedback,proto3" json:"candidate_feedback,omitempty"`
	SoftSkillsNotes   string                 `protobuf:"bytes,5,opt,name=soft_skills_notes,json=softSkillsNotes,proto3" json:"soft_skills_notes,omitempty"`
	AgentResults      []*AgentResult         `protobuf:"bytes,6,rep,name=agent_results,json=agentResults,proto3" json:"agent_results,omitempty"`
	RawTrace          string                 `protobuf:"bytes,7,opt,name=raw_trace,json=rawTrace,proto3" json:"raw_trace,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AIDecision) Reset() {
	*x = AIDecision{}
	mi := &file_models_analysis_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIDecision) ProtoMessage() {}

func (x *AIDecision) ProtoReflect() protoreflect.Message {
	mi := &file_models_analysis_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIDecision.ProtoReflect.Descriptor instead.
func (*AIDecision) Descriptor() ([]byte, []int) {
	return file_models_analysis_model_proto_rawDescGZIP(), []int{3}
}

func (x *AIDecision) GetHrRecommendation() string {
	if x != nil {
		return x.HrRecommendation
	}
	return ""
}

func (x *AIDecision) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AIDecision) GetHrRationale() string {
	if x != nil {
		return x.HrRationale
	}
	return ""
}

func (x *AIDecision) GetCandidateFeedback() string {
	if x != nil {
		return x.CandidateFeedback
	}
	return ""
}

func (x *AIDecision) GetSoftSkillsNotes() string {
	if x != nil {
		return x.SoftSkillsNotes
	}
	return ""
}

func (x *AIDecision) GetAgentResults() []*AgentResult {
	if x != nil {
		return x.AgentResults
	}
	return nil
}

func (x *AIDecision) GetRawTrace() string {
	if x != nil {
		return x.RawTrace
	}
	return ""
}

type Analysis struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VacancyId      string                 `protobuf:"bytes,2,opt,name=vacancy_id,json=vacancyId,proto3" json:"vacancy_id,omitempty"`
	CandidateId    string                 `protobuf:"bytes,3,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	ResumeId       string                 `protobuf:"bytes,4,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	VacancyVersion uint32                 `protobuf:"varint,5,opt,name=vacancy_version,json=vacancyVersion,proto3" json:"vacancy_version,omitempty"`
	Status         AnalysisStatus         `protobuf:"varint,6,opt,name=status,proto3,enum=analysis.models.v1.AnalysisStatus" json:"status,omitempty"`
	MatchScore     float32                `protobuf:"fixed32,7,opt,name=match_score,json=matchScore,proto3" json:"match_score,omitempty"`
	Profile        *CandidateProfile      `protobuf:"bytes,8,opt,name=profile,proto3" json:"profile,omitempty"`
	Breakdown      *ScoreBreakdown        `protobuf:"bytes,9,opt,name=breakdown,proto3" json:"breakdown,omitempty"`
	Ai             *AIDecision            `protobuf:"bytes,10,opt,name=ai,proto3" json:"ai,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,11,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Analysis) Reset() {
	*x = Analysis{}
	mi := &file_models_analysis_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Analysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Analysis) ProtoMessage() {}

func (x *Analysis) ProtoReflect() protoreflect.Message {
	mi := &file_models_analysis_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Analysis.ProtoReflect.Descriptor instead.
func (*Analysis) Descriptor() ([]byte, []int) {
	return file_models_analysis_model_proto_rawDescGZIP(), []int{4}
}

func (x *Analysis) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Analysis) GetVacancyId() string {
	if x != nil {
		return x.VacancyId
	}
	return ""
}

func (x *Analysis) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *Analysis) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

func (x *Analysis) GetVacancyVersion() uint32 {
	if x != nil {
		return x.VacancyVersion
	}
	return 0
}

func (x *Analysis) GetStatus() AnalysisStatus {
	if x != nil {
		return x.Status
	}
	return AnalysisStatus_ANALYSIS_STATUS_UNSPECIFIED
}

func (x *Analysis) GetMatchScore() float32 {
	if x != nil {
		return x.MatchScore
	}
	return 0
}

func (x *Analysis) GetProfile() *CandidateProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *Analysis) GetBreakdown() *ScoreBreakdown {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

func (x *Analysis) GetAi() *AIDecision {
	if x != nil {
		return x.Ai
	}
	return nil
}

func (x *Analysis) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Analysis) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Analysis) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type StartAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResumeId      string                 `protobuf:"bytes,1,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	VacancyId     string                 `protobuf:"bytes,2,opt,name=vacancy_id,json=vacancyId,proto3" json:"vacancy_id,omitempty"`
	UseLlm        bool                   `protobuf:"varint,3,opt,name=use_llm,json=useLlm,proto3" json:"use_llm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAnalysisRequest) Reset() {
	*x = StartAnalysisRequest{}
	mi := &file_models_analysis_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAnalysisRequest) ProtoMessage() {}

func (x *StartAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_analysis_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAnalysisRequest.ProtoReflect.Descriptor instead.
func (*StartAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_models_analysis_model_proto_rawDescGZIP(), []int{5}
}

func (x *StartAnalysisRequest) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

func (x *StartAnalysisRequest) GetVacancyId() string {
	if x != nil {
		return x.VacancyId
	}
	return ""
}

func (x *StartAnalysisRequest) GetUseLlm() bool {
	if x != nil {
		return x.UseLlm
	}
	return false
}

type StartAnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnalysisId    string                 `protobuf:"bytes,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	Status        AnalysisStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=analysis.models.v1.AnalysisStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAnalysisResponse) Reset() {
	*x = StartAnalysisResponse{}
	mi := &file_models_analysis_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAnalysisResponse) ProtoMessage() {}

func (x *StartAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_analysis_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAnalysisResponse.ProtoReflect.Descriptor instead.
func (*StartAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_models_analysis_model_proto_rawDescGZIP(), []int{6}
}

func (x *StartAnalysisResponse) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *StartAnalysisResponse) GetStatus() AnalysisStatus {
	if x != nil {
		return x.Status
	}
	return AnalysisStatus_ANALYSIS_STATUS_UNSPECIFIED
}

type GetAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnalysisId    string                 `protobuf:"bytes,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalysisRequest) Reset() {
	*x = GetAnalysisRequest{}
	mi := &file_models_analysis_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisRequest) ProtoMessage() {}

func (x *GetAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_analysis_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisRequest.ProtoReflect.Descriptor instead.
func (*GetAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_models_analysis_model_proto_rawDescGZIP(), []int{7}
}

func (x *GetAnalysisRequest) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

type AnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analysis      *Analysis              `protobuf:"bytes,1,opt,name=analysis,proto3" json:"analysis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisResponse) Reset() {
	*x = AnalysisResponse{}
	mi := &file_models_analysis_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResponse) ProtoMessage() {}

func (x *AnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_analysis_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResponse.ProtoReflect.Descriptor instead.
func (*AnalysisResponse) Descriptor() ([]byte, []int) {
	return file_models_analysis_model_proto_rawDescGZIP(), []int{8}
}

func (x *AnalysisResponse) GetAnalysis() *Analysis {
	if x != nil {
		return x.Analysis
	}
	return nil
}

type ListCandidatesByVacancyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VacancyId     string                 `protobuf:"bytes,1,opt,name=vacancy_id,json=vacancyId,proto3" json:"vacancy_id,omitempty"`
	Page          *common.PageRequest    `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	MinScore      float32                `protobuf:"fixed32,3,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	RequiredSkill string                 `protobuf:"bytes,4,opt,name=required_skill,json=requiredSkill,proto3" json:"required_skill,omitempty"`
	ScoreOrder    common.SortOrder       `protobuf:"varint,5,opt,name=score_order,json=scoreOrder,proto3,enum=common.v1.SortOrder" json:"score_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCandidatesByVacancyRequest) Reset() {
	*x = ListCandidatesByVacancyRequest{}
	mi := &file_models_analysis_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCandidatesByVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCandidatesByVacancyRequest) ProtoMessage() {}

func (x *ListCandidatesByVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_analysis_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCandidatesByVacancyRequest.ProtoReflect.Descriptor instead.
func (*ListCandidatesByVacancyRequest) Descriptor() ([]byte, []int) {
	return file_models_analysis_model_proto_rawDescGZIP(), []int{9}
}

func (x *ListCandidatesByVacancyRequest) GetVacancyId() string {
	if x != nil {
		return x.VacancyId
	}
	return ""
}

func (x *ListCandidatesByVacancyRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListCandidatesByVacancyRequest) GetMinScore() float32 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

func (x *ListCandidatesByVacancyRequest) GetRequiredSkill() string {
	if x != nil {
		return x.RequiredSkill
	}
	return ""
}

func (x *ListCandidatesByVacancyRequest) GetScoreOrder() common.SortOrder {
	if x != nil {
		return x.ScoreOrder
	}
	return common.SortOrder(0)
}

type CandidateWithAnalysis struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CandidateId    string                 `protobuf:"bytes,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	FullName       string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email          string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone          string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	MatchScore     float32                `protobuf:"fixed32,5,opt,name=match_score,json=matchScore,proto3" json:"match_score,omitempty"`
	AnalysisId     string                 `protobuf:"bytes,6,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	AnalysisStatus AnalysisStatus         `protobuf:"varint,7,opt,name=analysis_status,json=analysisStatus,proto3,enum=analysis.models.v1.AnalysisStatus" json:"analysis_status,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CandidateWithAnalysis) Reset() {
	*x = CandidateWithAnalysis{}
	mi := &file_models_analysis_model_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateWithAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateWithAnalysis) ProtoMessage() {}

func (x *CandidateWithAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_models_analysis_model_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateWithAnalysis.ProtoReflect.Descriptor instead.
func (*CandidateWithAnalysis) Descriptor() ([]byte, []int) {
	return file_models_analysis_model_proto_rawDescGZIP(), []int{10}
}

func (x *CandidateWithAnalysis) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *CandidateWithAnalysis) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CandidateWithAnalysis) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CandidateWithAnalysis) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CandidateWithAnalysis) GetMatchScore() float32 {
	if x != nil {
		return x.MatchScore
	}
	return 0
}

func (x *CandidateWithAnalysis) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *CandidateWithAnalysis) GetAnalysisStatus() AnalysisStatus {
	if x != nil {
		return x.AnalysisStatus
	}
	return AnalysisStatus_ANALYSIS_STATUS_UNSPECIFIED
}

func (x *CandidateWithAnalysis) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListCandidatesByVacancyResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Candidates    []*CandidateWithAnalysis `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	Page          *common.PageResponse     `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCandidatesByVacancyResponse) Reset() {
	*x = ListCandidatesByVacancyResponse{}
	mi := &file_models_analysis_model_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCandidatesByVacancyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCandidatesByVacancyResponse) ProtoMessage() {}

func (x *ListCandidatesByVacancyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_analysis_model_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCandidatesByVacancyResponse.ProtoReflect.Descriptor instead.
func (*ListCandidatesByVacancyResponse) Descriptor() ([]byte, []int) {
	return file_models_analysis_model_proto_rawDescGZIP(), []int{11}
}

func (x *ListCandidatesByVacancyResponse) GetCandidates() []*CandidateWithAnalysis {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *ListCandidatesByVacancyResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_models_analysis_model_proto protoreflect.FileDescriptor

const file_models_analysis_model_proto_rawDesc = "" +
	"\n" +
	"\x1bmodels/analysis_model.proto\x12\x12analysis.models.v1\x1a\x13common/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x01\n" +
	"\x10CandidateProfile\x12\x16\n" +
	"\x06skills\x18\x01 \x03(\tR\x06skills\x12)\n" +
	"\x10years_experience\x18\x02 \x01(\x02R\x0fyearsExperience\x12\x1c\n" +
	"\tpositions\x18\x03 \x03(\tR\tpositions\x12\"\n" +
	"\ftechnologies\x18\x04 \x03(\tR\ftechnologies\x12\x1c\n" +
	"\teducation\x18\x05 \x03(\tR\teducation\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\"\x9b\x02\n" +
	"\x0eScoreBreakdown\x12%\n" +
	"\x0ematched_skills\x18\x01 \x03(\tR\rmatchedSkills\x12%\n" +
	"\x0emissing_skills\x18\x02 \x03(\tR\rmissingSkills\x12!\n" +
	"\fextra_skills\x18\x03 \x03(\tR\vextraSkills\x12\x1d\n" +
	"\n" +
	"base_score\x18\x04 \x01(\x02R\tbaseScore\x12*\n" +
	"\x11must_have_penalty\x18\x05 \x01(\x02R\x0fmustHavePenalty\x12+\n" +
	"\x12nice_to_have_bonus\x18\x06 \x01(\x02R\x0fniceToHaveBonus\x12 \n" +
	"\vexplanation\x18\a \x01(\tR\vexplanation\"\x8f\x01\n" +
	"\vAgentResult\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12'\n" +
	"\x0fstructured_json\x18\x03 \x01(\tR\x0estructuredJson\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\"\xba\x02\n" +
	"\n" +
	"AIDecision\x12+\n" +
	"\x11hr_recommendation\x18\x01 \x01(\tR\x10hrRecommendation\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12!\n" +
	"\fhr_rationale\x18\x03 \x01(\tR\vhrRationale\x12-\n" +
	"\x12candidate_feedback\x18\x04 \x01(\tR\x11candidateFeedback\x12*\n" +
	"\x11soft_skills_notes\x18\x05 \x01(\tR\x0fsoftSkillsNotes\x12D\n" +
	"\ragent_results\x18\x06 \x03(\v2\x1f.analysis.models.v1.AgentResultR\fagentResults\x12\x1b\n" +
	"\traw_trace\x18\a \x01(\tR\brawTrace\"\xcc\x04\n" +
	"\bAnalysis\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"vacancy_id\x18\x02 \x01(\tR\tvacancyId\x12!\n" +
	"\fcandidate_id\x18\x03 \x01(\tR\vcandidateId\x12\x1b\n" +
	"\tresume_id\x18\x04 \x01(\tR\bresumeId\x12'\n" +
	"\x0fvacancy_version\x18\x05 \x01(\rR\x0evacancyVersion\x12:\n" +
	"\x06status\x18\x06 \x01(\x0e2\".analysis.models.v1.AnalysisStatusR\x06status\x12\x1f\n" +
	"\vmatch_score\x18\a \x01(\x02R\n" +
	"matchScore\x12>\n" +
	"\aprofile\x18\b \x01(\v2$.analysis.models.v1.CandidateProfileR\aprofile\x12@\n" +
	"\tbreakdown\x18\t \x01(\v2\".analysis.models.v1.ScoreBreakdownR\tbreakdown\x12.\n" +
	"\x02ai\x18\n" +
	" \x01(\v2\x1e.analysis.models.v1.AIDecisionR\x02ai\x12#\n" +
	"\rerror_message\x18\v \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"k\n" +
	"\x14StartAnalysisRequest\x12\x1b\n" +
	"\tresume_id\x18\x01 \x01(\tR\bresumeId\x12\x1d\n" +
	"\n" +
	"vacancy_id\x18\x02 \x01(\tR\tvacancyId\x12\x17\n" +
	"\ause_llm\x18\x03 \x01(\bR\x06useLlm\"t\n" +
	"\x15StartAnalysisResponse\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\tR\n" +
	"analysisId\x12:\n" +
	"\x06status\x18\x02 \x01(\x0e2\".analysis.models.v1.AnalysisStatusR\x06status\"5\n" +
	"\x12GetAnalysisRequest\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\tR\n" +
	"analysisId\"L\n" +
	"\x10AnalysisResponse\x128\n" +
	"\banalysis\x18\x01 \x01(\v2\x1c.analysis.models.v1.AnalysisR\banalysis\"\xe6\x01\n" +
	"\x1eListCandidatesByVacancyRequest\x12\x1d\n" +
	"\n" +
	"vacancy_id\x18\x01 \x01(\tR\tvacancyId\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.common.v1.PageRequestR\x04page\x12\x1b\n" +
	"\tmin_score\x18\x03 \x01(\x02R\bminScore\x12%\n" +
	"\x0erequired_skill\x18\x04 \x01(\tR\rrequiredSkill\x125\n" +
	"\vscore_order\x18\x05 \x01(\x0e2\x14.common.v1.SortOrderR\n" +
	"scoreOrder\"\xcd\x02\n" +
	"\x15CandidateWithAnalysis\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\tR\vcandidateId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1f\n" +
	"\vmatch_score\x18\x05 \x01(\x02R\n" +
	"matchScore\x12\x1f\n" +
	"\vanalysis_id\x18\x06 \x01(\tR\n" +
	"analysisId\x12K\n" +
	"\x0fanalysis_status\x18\a \x01(\x0e2\".analysis.models.v1.AnalysisStatusR\x0eanalysisStatus\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x99\x01\n" +
	"\x1fListCandidatesByVacancyResponse\x12I\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2).analysis.models.v1.CandidateWithAnalysisR\n" +
	"candidates\x12+\n" +
	"\x04page\x18\x02 \x01(\v2\x17.common.v1.PageResponseR\x04page*\xa0\x01\n" +
	"\x0eAnalysisStatus\x12\x1f\n" +
	"\x1bANALYSIS_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ANALYSIS_STATUS_QUEUED\x10\x01\x12\x1b\n" +
	"\x17ANALYSIS_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14ANALYSIS_STATUS_DONE\x10\x03\x12\x1a\n" +
	"\x16ANALYSIS_STATUS_FAILED\x10\x04B6Z4github.com/artem13815/hr/analysis/internal/pb/modelsb\x06proto3"

var (
	file_models_analysis_model_proto_rawDescOnce sync.Once
	file_models_analysis_model_proto_rawDescData []byte
)

func file_models_analysis_model_proto_rawDescGZIP() []byte {
	file_models_analysis_model_proto_rawDescOnce.Do(func() {
		file_models_analysis_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_analysis_model_proto_rawDesc), len(file_models_analysis_model_proto_rawDesc)))
	})
	return file_models_analysis_model_proto_rawDescData
}

var file_models_analysis_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_models_analysis_model_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_models_analysis_model_proto_goTypes = []any{
	(AnalysisStatus)(0),                     // 0: analysis.models.v1.AnalysisStatus
	(*CandidateProfile)(nil),                // 1: analysis.models.v1.CandidateProfile
	(*ScoreBreakdown)(nil),                  // 2: analysis.models.v1.ScoreBreakdown
	(*AgentResult)(nil),                     // 3: analysis.models.v1.AgentResult
	(*AIDecision)(nil),                      // 4: analysis.models.v1.AIDecision
	(*Analysis)(nil),                        // 5: analysis.models.v1.Analysis
	(*StartAnalysisRequest)(nil),            // 6: analysis.models.v1.StartAnalysisRequest
	(*StartAnalysisResponse)(nil),           // 7: analysis.models.v1.StartAnalysisResponse
	(*GetAnalysisRequest)(nil),              // 8: analysis.models.v1.GetAnalysisRequest
	(*AnalysisResponse)(nil),                // 9: analysis.models.v1.AnalysisResponse
	(*ListCandidatesByVacancyRequest)(nil),  // 10: analysis.models.v1.ListCandidatesByVacancyRequest
	(*CandidateWithAnalysis)(nil),           // 11: analysis.models.v1.CandidateWithAnalysis
	(*ListCandidatesByVacancyResponse)(nil), // 12: analysis.models.v1.ListCandidatesByVacancyResponse
	(*timestamppb.Timestamp)(nil),           // 13: google.protobuf.Timestamp
	(*common.PageRequest)(nil),              // 14: common.v1.PageRequest
	(common.SortOrder)(0),                   // 15: common.v1.SortOrder
	(*common.PageResponse)(nil),             // 16: common.v1.PageResponse
}
var file_models_analysis_model_proto_depIdxs = []int32{
	3,  // 0: analysis.models.v1.AIDecision.agent_results:type_name -> analysis.models.v1.AgentResult
	0,  // 1: analysis.models.v1.Analysis.status:type_name -> analysis.models.v1.AnalysisStatus
	1,  // 2: analysis.models.v1.Analysis.profile:type_name -> analysis.models.v1.CandidateProfile
	2,  // 3: analysis.models.v1.Analysis.breakdown:type_name -> analysis.models.v1.ScoreBreakdown
	4,  // 4: analysis.models.v1.Analysis.ai:type_name -> analysis.models.v1.AIDecision
	13, // 5: analysis.models.v1.Analysis.created_at:type_name -> google.protobuf.Timestamp
	13, // 6: analysis.models.v1.Analysis.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 7: analysis.models.v1.StartAnalysisResponse.status:type_name -> analysis.models.v1.AnalysisStatus
	5,  // 8: analysis.models.v1.AnalysisResponse.analysis:type_name -> analysis.models.v1.Analysis
	14, // 9: analysis.models.v1.ListCandidatesByVacancyRequest.page:type_name -> common.v1.PageRequest
	15, // 10: analysis.models.v1.ListCandidatesByVacancyRequest.score_order:type_name -> common.v1.SortOrder
	0,  // 11: analysis.models.v1.CandidateWithAnalysis.analysis_status:type_name -> analysis.models.v1.AnalysisStatus
	13, // 12: analysis.models.v1.CandidateWithAnalysis.created_at:type_name -> google.protobuf.Timestamp
	11, // 13: analysis.models.v1.ListCandidatesByVacancyResponse.candidates:type_name -> analysis.models.v1.CandidateWithAnalysis
	16, // 14: analysis.models.v1.ListCandidatesByVacancyResponse.page:type_name -> common.v1.PageResponse
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_models_analysis_model_proto_init() }
func file_models_analysis_model_proto_init() {
	if File_models_analysis_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_analysis_model_proto_rawDesc), len(file_models_analysis_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_analysis_model_proto_goTypes,
		DependencyIndexes: file_models_analysis_model_proto_depIdxs,
		EnumInfos:         file_models_analysis_model_proto_enumTypes,
		MessageInfos:      file_models_analysis_model_proto_msgTypes,
	}.Build()
	File_models_analysis_model_proto = out.File
	file_models_analysis_model_proto_goTypes = nil
	file_models_analysis_model_proto_depIdxs = nil
}
