// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: resume_api/resume.proto

package resume_api

import (
	models "github.com/artem13815/hr/gateway/internal/pb/models"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_resume_api_resume_proto protoreflect.FileDescriptor

const file_resume_api_resume_proto_rawDesc = "" +
	"\n" +
	"\x17resume_api/resume.proto\x12\x11resume.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19models/resume_model.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xdb\v\n" +
	"\rResumeService\x12\xab\x01\n" +
	"\x0fCreateCandidate\x12(.resume.models.v1.CreateCandidateRequest\x1a#.resume.models.v1.CandidateResponse\"I\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02.:\x01*\")/api/v1/vacancies/{vacancy_id}/candidates\x12\x9a\x01\n" +
	"\fGetCandidate\x12%.resume.models.v1.GetCandidateRequest\x1a#.resume.models.v1.CandidateResponse\">\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02#\x12!/api/v1/candidates/{candidate_id}\x12\xd1\x01\n" +
	"\x19CreateCandidateFromResume\x122.resume.models.v1.CreateCandidateFromResumeRequest\x1a).resume.models.v1.CandidateResumeResponse\"U\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02::\x01*\"5/api/v1/vacancies/{vacancy_id}/candidates/from-resume\x12\xa5\x01\n" +
	"\fIngestResume\x122.resume.models.v1.CreateCandidateFromResumeRequest\x1a).resume.models.v1.CandidateResumeResponse\"6\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/resumes/intake\x12\xaa\x01\n" +
	"\x11IngestResumeBatch\x12*.resume.models.v1.BatchIngestResumeRequest\x1a+.resume.models.v1.BatchIngestResumeResponse\"<\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/resumes/intake/batch\x12v\n" +
	"\fUploadResume\x12%.resume.models.v1.UploadResumeRequest\x1a&.resume.models.v1.UploadResumeResponse\"\x15\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00(\x01\x12\x8b\x01\n" +
	"\tGetResume\x12\".resume.models.v1.GetResumeRequest\x1a .resume.models.v1.ResumeResponse\"8\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/resumes/{resume_id}\x12\xa6\x01\n" +
	"\x0eDownloadResume\x12'.resume.models.v1.DownloadResumeRequest\x1a(.resume.models.v1.DownloadResumeResponse\"A\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02&\x12$/api/v1/resumes/{resume_id}/download\x12\xa6\x01\n" +
	"\x0fDeleteCandidate\x12(.resume.models.v1.DeleteCandidateRequest\x1a).resume.models.v1.DeleteCandidateResponse\">\x92A\x12b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02#*!/api/v1/candidates/{candidate_id}B\xd2\x01\x92A\x95\x01\x12D\n" +
	"\x12Resume Service API\x12'Candidate and resume management service2\x051.0.0ZM\n" +
	"K\n" +
	"\n" +
	"BearerAuth\x12=\b\x02\x12(JWT Bearer token. Format: Bearer <token>\x1a\rAuthorization \x02Z7github.com/artem13815/hr/gateway/internal/pb/resume_apib\x06proto3"

var file_resume_api_resume_proto_goTypes = []any{
	(*models.CreateCandidateRequest)(nil),           // 0: resume.models.v1.CreateCandidateRequest
	(*models.GetCandidateRequest)(nil),              // 1: resume.models.v1.GetCandidateRequest
	(*models.CreateCandidateFromResumeRequest)(nil), // 2: resume.models.v1.CreateCandidateFromResumeRequest
	(*models.BatchIngestResumeRequest)(nil),         // 3: resume.models.v1.BatchIngestResumeRequest
	(*models.UploadResumeRequest)(nil),              // 4: resume.models.v1.UploadResumeRequest
	(*models.GetResumeRequest)(nil),                 // 5: resume.models.v1.GetResumeRequest
	(*models.DownloadResumeRequest)(nil),            // 6: resume.models.v1.DownloadResumeRequest
	(*models.DeleteCandidateRequest)(nil),           // 7: resume.models.v1.DeleteCandidateRequest
	(*models.CandidateResponse)(nil),                // 8: resume.models.v1.CandidateResponse
	(*models.CandidateResumeResponse)(nil),          // 9: resume.models.v1.CandidateResumeResponse
	(*models.BatchIngestResumeResponse)(nil),        // 10: resume.models.v1.BatchIngestResumeResponse
	(*models.UploadResumeResponse)(nil),             // 11: resume.models.v1.UploadResumeResponse
	(*models.ResumeResponse)(nil),                   // 12: resume.models.v1.ResumeResponse
	(*models.DownloadResumeResponse)(nil),           // 13: resume.models.v1.DownloadResumeResponse
	(*models.DeleteCandidateResponse)(nil),          // 14: resume.models.v1.DeleteCandidateResponse
}
var file_resume_api_resume_proto_depIdxs = []int32{
	0,  // 0: resume.service.v1.ResumeService.CreateCandidate:input_type -> resume.models.v1.CreateCandidateRequest
	1,  // 1: resume.service.v1.ResumeService.GetCandidate:input_type -> resume.models.v1.GetCandidateRequest
	2,  // 2: resume.service.v1.ResumeService.CreateCandidateFromResume:input_type -> resume.models.v1.CreateCandidateFromResumeRequest
	2,  // 3: resume.service.v1.ResumeService.IngestResume:input_type -> resume.models.v1.CreateCandidateFromResumeRequest
	3,  // 4: resume.service.v1.ResumeService.IngestResumeBatch:input_type -> resume.models.v1.BatchIngestResumeRequest
	4,  // 5: resume.service.v1.ResumeService.UploadResume:input_type -> resume.models.v1.UploadResumeRequest
	5,  // 6: resume.service.v1.ResumeService.GetResume:input_type -> resume.models.v1.GetResumeRequest
	6,  // 7: resume.service.v1.ResumeService.DownloadResume:input_type -> resume.models.v1.DownloadResumeRequest
	7,  // 8: resume.service.v1.ResumeService.DeleteCandidate:input_type -> resume.models.v1.DeleteCandidateRequest
	8,  // 9: resume.service.v1.ResumeService.CreateCandidate:output_type -> resume.models.v1.CandidateResponse
	8,  // 10: resume.service.v1.ResumeService.GetCandidate:output_type -> resume.models.v1.CandidateResponse
	9,  // 11: resume.service.v1.ResumeService.CreateCandidateFromResume:output_type -> resume.models.v1.CandidateResumeResponse
	9,  // 12: resume.service.v1.ResumeService.IngestResume:output_type -> resume.models.v1.CandidateResumeResponse
	10, // 13: resume.service.v1.ResumeService.IngestResumeBatch:output_type -> resume.models.v1.BatchIngestResumeResponse
	11, // 14: resume.service.v1.ResumeService.UploadResume:output_type -> resume.models.v1.UploadResumeResponse
	12, // 15: resume.service.v1.ResumeService.GetResume:output_type -> resume.models.v1.ResumeResponse
	13, // 16: resume.service.v1.ResumeService.DownloadResume:output_type -> resume.models.v1.DownloadResumeResponse
	14, // 17: resume.service.v1.ResumeService.DeleteCandidate:output_type -> resume.models.v1.DeleteCandidateResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_resume_api_resume_proto_init() }
func file_resume_api_resume_proto_init() {
	if File_resume_api_resume_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resume_api_resume_proto_rawDesc), len(file_resume_api_resume_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resume_api_resume_proto_goTypes,
		DependencyIndexes: file_resume_api_resume_proto_depIdxs,
	}.Build()
	File_resume_api_resume_proto = out.File
	file_resume_api_resume_proto_goTypes = nil
	file_resume_api_resume_proto_depIdxs = nil
}
