// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/artem13815/hr/resume/internal/domain"
	"github.com/gojuno/minimock/v3"
)

// ProfileExtractorMock implements mm_usecase.ProfileExtractor
type ProfileExtractorMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcExtractCandidateProfile          func(text string, fileName string) (c1 domain.CandidateProfile)
	funcExtractCandidateProfileOrigin    string
	inspectFuncExtractCandidateProfile   func(text string, fileName string)
	afterExtractCandidateProfileCounter  uint64
	beforeExtractCandidateProfileCounter uint64
	ExtractCandidateProfileMock          mProfileExtractorMockExtractCandidateProfile
}

// NewProfileExtractorMock returns a mock for mm_usecase.ProfileExtractor
func NewProfileExtractorMock(t minimock.Tester) *ProfileExtractorMock {
	m := &ProfileExtractorMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ExtractCandidateProfileMock = mProfileExtractorMockExtractCandidateProfile{mock: m}
	m.ExtractCandidateProfileMock.callArgs = []*ProfileExtractorMockExtractCandidateProfileParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mProfileExtractorMockExtractCandidateProfile struct {
	optional           bool
	mock               *ProfileExtractorMock
	defaultExpectation *ProfileExtractorMockExtractCandidateProfileExpectation
	expectations       []*ProfileExtractorMockExtractCandidateProfileExpectation

	callArgs []*ProfileExtractorMockExtractCandidateProfileParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ProfileExtractorMockExtractCandidateProfileExpectation specifies expectation struct of the ProfileExtractor.ExtractCandidateProfile
type ProfileExtractorMockExtractCandidateProfileExpectation struct {
	mock               *ProfileExtractorMock
	params             *ProfileExtractorMockExtractCandidateProfileParams
	paramPtrs          *ProfileExtractorMockExtractCandidateProfileParamPtrs
	expectationOrigins ProfileExtractorMockExtractCandidateProfileExpectationOrigins
	results            *ProfileExtractorMockExtractCandidateProfileResults
	returnOrigin       string
	Counter            uint64
}

// ProfileExtractorMockExtractCandidateProfileParams contains parameters of the ProfileExtractor.ExtractCandidateProfile
type ProfileExtractorMockExtractCandidateProfileParams struct {
	text     string
	fileName string
}

// ProfileExtractorMockExtractCandidateProfileParamPtrs contains pointers to parameters of the ProfileExtractor.ExtractCandidateProfile
type ProfileExtractorMockExtractCandidateProfileParamPtrs struct {
	text     *string
	fileName *string
}

// ProfileExtractorMockExtractCandidateProfileResults contains results of the ProfileExtractor.ExtractCandidateProfile
type ProfileExtractorMockExtractCandidateProfileResults struct {
	c1 domain.CandidateProfile
}

// ProfileExtractorMockExtractCandidateProfileOrigins contains origins of expectations of the ProfileExtractor.ExtractCandidateProfile
type ProfileExtractorMockExtractCandidateProfileExpectationOrigins struct {
	origin         string
	originText     string
	originFileName string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmExtractCandidateProfile *mProfileExtractorMockExtractCandidateProfile) Optional() *mProfileExtractorMockExtractCandidateProfile {
	mmExtractCandidateProfile.optional = true
	return mmExtractCandidateProfile
}

// Expect sets up expected params for ProfileExtractor.ExtractCandidateProfile
func (mmExtractCandidateProfile *mProfileExtractorMockExtractCandidateProfile) Expect(text string, fileName string) *mProfileExtractorMockExtractCandidateProfile {
	if mmExtractCandidateProfile.mock.funcExtractCandidateProfile != nil {
		mmExtractCandidateProfile.mock.t.Fatalf("ProfileExtractorMock.ExtractCandidateProfile mock is already set by Set")
	}

	if mmExtractCandidateProfile.defaultExpectation == nil {
		mmExtractCandidateProfile.defaultExpectation = &ProfileExtractorMockExtractCandidateProfileExpectation{}
	}

	if mmExtractCandidateProfile.defaultExpectation.paramPtrs != nil {
		mmExtractCandidateProfile.mock.t.Fatalf("ProfileExtractorMock.ExtractCandidateProfile mock is already set by ExpectParams functions")
	}

	mmExtractCandidateProfile.defaultExpectation.params = &ProfileExtractorMockExtractCandidateProfileParams{text, fileName}
	mmExtractCandidateProfile.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmExtractCandidateProfile.expectations {
		if minimock.Equal(e.params, mmExtractCandidateProfile.defaultExpectation.params) {
			mmExtractCandidateProfile.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmExtractCandidateProfile.defaultExpectation.params)
		}
	}

	return mmExtractCandidateProfile
}

// ExpectTextParam1 sets up expected param text for ProfileExtractor.ExtractCandidateProfile
func (mmExtractCandidateProfile *mProfileExtractorMockExtractCandidateProfile) ExpectTextParam1(text string) *mProfileExtractorMockExtractCandidateProfile {
	if mmExtractCandidateProfile.mock.funcExtractCandidateProfile != nil {
		mmExtractCandidateProfile.mock.t.Fatalf("ProfileExtractorMock.ExtractCandidateProfile mock is already set by Set")
	}

	if mmExtractCandidateProfile.defaultExpectation == nil {
		mmExtractCandidateProfile.defaultExpectation = &ProfileExtractorMockExtractCandidateProfileExpectation{}
	}

	if mmExtractCandidateProfile.defaultExpectation.params != nil {
		mmExtractCandidateProfile.mock.t.Fatalf("ProfileExtractorMock.ExtractCandidateProfile mock is already set by Expect")
	}

	if mmExtractCandidateProfile.defaultExpectation.paramPtrs == nil {
		mmExtractCandidateProfile.defaultExpectation.paramPtrs = &ProfileExtractorMockExtractCandidateProfileParamPtrs{}
	}
	mmExtractCandidateProfile.defaultExpectation.paramPtrs.text = &text
	mmExtractCandidateProfile.defaultExpectation.expectationOrigins.originText = minimock.CallerInfo(1)

	return mmExtractCandidateProfile
}

// ExpectFileNameParam2 sets up expected param fileName for ProfileExtractor.ExtractCandidateProfile
func (mmExtractCandidateProfile *mProfileExtractorMockExtractCandidateProfile) ExpectFileNameParam2(fileName string) *mProfileExtractorMockExtractCandidateProfile {
	if mmExtractCandidateProfile.mock.funcExtractCandidateProfile != nil {
		mmExtractCandidateProfile.mock.t.Fatalf("ProfileExtractorMock.ExtractCandidateProfile mock is already set by Set")
	}

	if mmExtractCandidateProfile.defaultExpectation == nil {
		mmExtractCandidateProfile.defaultExpectation = &ProfileExtractorMockExtractCandidateProfileExpectation{}
	}

	if mmExtractCandidateProfile.defaultExpectation.params != nil {
		mmExtractCandidateProfile.mock.t.Fatalf("ProfileExtractorMock.ExtractCandidateProfile mock is already set by Expect")
	}

	if mmExtractCandidateProfile.defaultExpectation.paramPtrs == nil {
		mmExtractCandidateProfile.defaultExpectation.paramPtrs = &ProfileExtractorMockExtractCandidateProfileParamPtrs{}
	}
	mmExtractCandidateProfile.defaultExpectation.paramPtrs.fileName = &fileName
	mmExtractCandidateProfile.defaultExpectation.expectationOrigins.originFileName = minimock.CallerInfo(1)

	return mmExtractCandidateProfile
}

// Inspect accepts an inspector function that has same arguments as the ProfileExtractor.ExtractCandidateProfile
func (mmExtractCandidateProfile *mProfileExtractorMockExtractCandidateProfile) Inspect(f func(text string, fileName string)) *mProfileExtractorMockExtractCandidateProfile {
	if mmExtractCandidateProfile.mock.inspectFuncExtractCandidateProfile != nil {
		mmExtractCandidateProfile.mock.t.Fatalf("Inspect function is already set for ProfileExtractorMock.ExtractCandidateProfile")
	}

	mmExtractCandidateProfile.mock.inspectFuncExtractCandidateProfile = f

	return mmExtractCandidateProfile
}

// Return sets up results that will be returned by ProfileExtractor.ExtractCandidateProfile
func (mmExtractCandidateProfile *mProfileExtractorMockExtractCandidateProfile) Return(c1 domain.CandidateProfile) *ProfileExtractorMock {
	if mmExtractCandidateProfile.mock.funcExtractCandidateProfile != nil {
		mmExtractCandidateProfile.mock.t.Fatalf("ProfileExtractorMock.ExtractCandidateProfile mock is already set by Set")
	}

	if mmExtractCandidateProfile.defaultExpectation == nil {
		mmExtractCandidateProfile.defaultExpectation = &ProfileExtractorMockExtractCandidateProfileExpectation{mock: mmExtractCandidateProfile.mock}
	}
	mmExtractCandidateProfile.defaultExpectation.results = &ProfileExtractorMockExtractCandidateProfileResults{c1}
	mmExtractCandidateProfile.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmExtractCandidateProfile.mock
}

// Set uses given function f to mock the ProfileExtractor.ExtractCandidateProfile method
func (mmExtractCandidateProfile *mProfileExtractorMockExtractCandidateProfile) Set(f func(text string, fileName string) (c1 domain.CandidateProfile)) *ProfileExtractorMock {
	if mmExtractCandidateProfile.defaultExpectation != nil {
		mmExtractCandidateProfile.mock.t.Fatalf("Default expectation is already set for the ProfileExtractor.ExtractCandidateProfile method")
	}

	if len(mmExtractCandidateProfile.expectations) > 0 {
		mmExtractCandidateProfile.mock.t.Fatalf("Some expectations are already set for the ProfileExtractor.ExtractCandidateProfile method")
	}

	mmExtractCandidateProfile.mock.funcExtractCandidateProfile = f
	mmExtractCandidateProfile.mock.funcExtractCandidateProfileOrigin = minimock.CallerInfo(1)
	return mmExtractCandidateProfile.mock
}

// When sets expectation for the ProfileExtractor.ExtractCandidateProfile which will trigger the result defined by the following
// Then helper
func (mmExtractCandidateProfile *mProfileExtractorMockExtractCandidateProfile) When(text string, fileName string) *ProfileExtractorMockExtractCandidateProfileExpectation {
	if mmExtractCandidateProfile.mock.funcExtractCandidateProfile != nil {
		mmExtractCandidateProfile.mock.t.Fatalf("ProfileExtractorMock.ExtractCandidateProfile mock is already set by Set")
	}

	expectation := &ProfileExtractorMockExtractCandidateProfileExpectation{
		mock:               mmExtractCandidateProfile.mock,
		params:             &ProfileExtractorMockExtractCandidateProfileParams{text, fileName},
		expectationOrigins: ProfileExtractorMockExtractCandidateProfileExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmExtractCandidateProfile.expectations = append(mmExtractCandidateProfile.expectations, expectation)
	return expectation
}

// Then sets up ProfileExtractor.ExtractCandidateProfile return parameters for the expectation previously defined by the When method
func (e *ProfileExtractorMockExtractCandidateProfileExpectation) Then(c1 domain.CandidateProfile) *ProfileExtractorMock {
	e.results = &ProfileExtractorMockExtractCandidateProfileResults{c1}
	return e.mock
}

// Times sets number of times ProfileExtractor.ExtractCandidateProfile should be invoked
func (mmExtractCandidateProfile *mProfileExtractorMockExtractCandidateProfile) Times(n uint64) *mProfileExtractorMockExtractCandidateProfile {
	if n == 0 {
		mmExtractCandidateProfile.mock.t.Fatalf("Times of ProfileExtractorMock.ExtractCandidateProfile mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmExtractCandidateProfile.expectedInvocations, n)
	mmExtractCandidateProfile.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmExtractCandidateProfile
}

func (mmExtractCandidateProfile *mProfileExtractorMockExtractCandidateProfile) invocationsDone() bool {
	if len(mmExtractCandidateProfile.expectations) == 0 && mmExtractCandidateProfile.defaultExpectation == nil && mmExtractCandidateProfile.mock.funcExtractCandidateProfile == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmExtractCandidateProfile.mock.afterExtractCandidateProfileCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmExtractCandidateProfile.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ExtractCandidateProfile implements mm_usecase.ProfileExtractor
func (mmExtractCandidateProfile *ProfileExtractorMock) ExtractCandidateProfile(text string, fileName string) (c1 domain.CandidateProfile) {
	mm_atomic.AddUint64(&mmExtractCandidateProfile.beforeExtractCandidateProfileCounter, 1)
	defer mm_atomic.AddUint64(&mmExtractCandidateProfile.afterExtractCandidateProfileCounter, 1)

	mmExtractCandidateProfile.t.Helper()

	if mmExtractCandidateProfile.inspectFuncExtractCandidateProfile != nil {
		mmExtractCandidateProfile.inspectFuncExtractCandidateProfile(text, fileName)
	}

	mm_params := ProfileExtractorMockExtractCandidateProfileParams{text, fileName}

	// Record call args
	mmExtractCandidateProfile.ExtractCandidateProfileMock.mutex.Lock()
	mmExtractCandidateProfile.ExtractCandidateProfileMock.callArgs = append(mmExtractCandidateProfile.ExtractCandidateProfileMock.callArgs, &mm_params)
	mmExtractCandidateProfile.ExtractCandidateProfileMock.mutex.Unlock()

	for _, e := range mmExtractCandidateProfile.ExtractCandidateProfileMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.c1
		}
	}

	if mmExtractCandidateProfile.ExtractCandidateProfileMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmExtractCandidateProfile.ExtractCandidateProfileMock.defaultExpectation.Counter, 1)
		mm_want := mmExtractCandidateProfile.ExtractCandidateProfileMock.defaultExpectation.params
		mm_want_ptrs := mmExtractCandidateProfile.ExtractCandidateProfileMock.defaultExpectation.paramPtrs

		mm_got := ProfileExtractorMockExtractCandidateProfileParams{text, fileName}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.text != nil && !minimock.Equal(*mm_want_ptrs.text, mm_got.text) {
				mmExtractCandidateProfile.t.Errorf("ProfileExtractorMock.ExtractCandidateProfile got unexpected parameter text, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmExtractCandidateProfile.ExtractCandidateProfileMock.defaultExpectation.expectationOrigins.originText, *mm_want_ptrs.text, mm_got.text, minimock.Diff(*mm_want_ptrs.text, mm_got.text))
			}

			if mm_want_ptrs.fileName != nil && !minimock.Equal(*mm_want_ptrs.fileName, mm_got.fileName) {
				mmExtractCandidateProfile.t.Errorf("ProfileExtractorMock.ExtractCandidateProfile got unexpected parameter fileName, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmExtractCandidateProfile.ExtractCandidateProfileMock.defaultExpectation.expectationOrigins.originFileName, *mm_want_ptrs.fileName, mm_got.fileName, minimock.Diff(*mm_want_ptrs.fileName, mm_got.fileName))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmExtractCandidateProfile.t.Errorf("ProfileExtractorMock.ExtractCandidateProfile got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmExtractCandidateProfile.ExtractCandidateProfileMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmExtractCandidateProfile.ExtractCandidateProfileMock.defaultExpectation.results
		if mm_results == nil {
			mmExtractCandidateProfile.t.Fatal("No results are set for the ProfileExtractorMock.ExtractCandidateProfile")
		}
		return (*mm_results).c1
	}
	if mmExtractCandidateProfile.funcExtractCandidateProfile != nil {
		return mmExtractCandidateProfile.funcExtractCandidateProfile(text, fileName)
	}
	mmExtractCandidateProfile.t.Fatalf("Unexpected call to ProfileExtractorMock.ExtractCandidateProfile. %v %v", text, fileName)
	return
}

// ExtractCandidateProfileAfterCounter returns a count of finished ProfileExtractorMock.ExtractCandidateProfile invocations
func (mmExtractCandidateProfile *ProfileExtractorMock) ExtractCandidateProfileAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmExtractCandidateProfile.afterExtractCandidateProfileCounter)
}

// ExtractCandidateProfileBeforeCounter returns a count of ProfileExtractorMock.ExtractCandidateProfile invocations
func (mmExtractCandidateProfile *ProfileExtractorMock) ExtractCandidateProfileBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmExtractCandidateProfile.beforeExtractCandidateProfileCounter)
}

// Calls returns a list of arguments used in each call to ProfileExtractorMock.ExtractCandidateProfile.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmExtractCandidateProfile *mProfileExtractorMockExtractCandidateProfile) Calls() []*ProfileExtractorMockExtractCandidateProfileParams {
	mmExtractCandidateProfile.mutex.RLock()

	argCopy := make([]*ProfileExtractorMockExtractCandidateProfileParams, len(mmExtractCandidateProfile.callArgs))
	copy(argCopy, mmExtractCandidateProfile.callArgs)

	mmExtractCandidateProfile.mutex.RUnlock()

	return argCopy
}

// MinimockExtractCandidateProfileDone returns true if the count of the ExtractCandidateProfile invocations corresponds
// the number of defined expectations
func (m *ProfileExtractorMock) MinimockExtractCandidateProfileDone() bool {
	if m.ExtractCandidateProfileMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ExtractCandidateProfileMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ExtractCandidateProfileMock.invocationsDone()
}

// MinimockExtractCandidateProfileInspect logs each unmet expectation
func (m *ProfileExtractorMock) MinimockExtractCandidateProfileInspect() {
	for _, e := range m.ExtractCandidateProfileMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ProfileExtractorMock.ExtractCandidateProfile at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterExtractCandidateProfileCounter := mm_atomic.LoadUint64(&m.afterExtractCandidateProfileCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ExtractCandidateProfileMock.defaultExpectation != nil && afterExtractCandidateProfileCounter < 1 {
		if m.ExtractCandidateProfileMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ProfileExtractorMock.ExtractCandidateProfile at\n%s", m.ExtractCandidateProfileMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ProfileExtractorMock.ExtractCandidateProfile at\n%s with params: %#v", m.ExtractCandidateProfileMock.defaultExpectation.expectationOrigins.origin, *m.ExtractCandidateProfileMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcExtractCandidateProfile != nil && afterExtractCandidateProfileCounter < 1 {
		m.t.Errorf("Expected call to ProfileExtractorMock.ExtractCandidateProfile at\n%s", m.funcExtractCandidateProfileOrigin)
	}

	if !m.ExtractCandidateProfileMock.invocationsDone() && afterExtractCandidateProfileCounter > 0 {
		m.t.Errorf("Expected %d calls to ProfileExtractorMock.ExtractCandidateProfile at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ExtractCandidateProfileMock.expectedInvocations), m.ExtractCandidateProfileMock.expectedInvocationsOrigin, afterExtractCandidateProfileCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ProfileExtractorMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockExtractCandidateProfileInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ProfileExtractorMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ProfileExtractorMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockExtractCandidateProfileDone()
}
