// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// TextExtractorMock implements mm_usecase.TextExtractor
type TextExtractorMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcBuildFileName          func(fileName string, fileType string) (s1 string)
	funcBuildFileNameOrigin    string
	inspectFuncBuildFileName   func(fileName string, fileType string)
	afterBuildFileNameCounter  uint64
	beforeBuildFileNameCounter uint64
	BuildFileNameMock          mTextExtractorMockBuildFileName

	funcDetectFileType          func(fileName string, data []byte) (s1 string, err error)
	funcDetectFileTypeOrigin    string
	inspectFuncDetectFileType   func(fileName string, data []byte)
	afterDetectFileTypeCounter  uint64
	beforeDetectFileTypeCounter uint64
	DetectFileTypeMock          mTextExtractorMockDetectFileType

	funcExtractText          func(fileType string, data []byte) (s1 string, err error)
	funcExtractTextOrigin    string
	inspectFuncExtractText   func(fileType string, data []byte)
	afterExtractTextCounter  uint64
	beforeExtractTextCounter uint64
	ExtractTextMock          mTextExtractorMockExtractText
}

// NewTextExtractorMock returns a mock for mm_usecase.TextExtractor
func NewTextExtractorMock(t minimock.Tester) *TextExtractorMock {
	m := &TextExtractorMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.BuildFileNameMock = mTextExtractorMockBuildFileName{mock: m}
	m.BuildFileNameMock.callArgs = []*TextExtractorMockBuildFileNameParams{}

	m.DetectFileTypeMock = mTextExtractorMockDetectFileType{mock: m}
	m.DetectFileTypeMock.callArgs = []*TextExtractorMockDetectFileTypeParams{}

	m.ExtractTextMock = mTextExtractorMockExtractText{mock: m}
	m.ExtractTextMock.callArgs = []*TextExtractorMockExtractTextParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mTextExtractorMockBuildFileName struct {
	optional           bool
	mock               *TextExtractorMock
	defaultExpectation *TextExtractorMockBuildFileNameExpectation
	expectations       []*TextExtractorMockBuildFileNameExpectation

	callArgs []*TextExtractorMockBuildFileNameParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// TextExtractorMockBuildFileNameExpectation specifies expectation struct of the TextExtractor.BuildFileName
type TextExtractorMockBuildFileNameExpectation struct {
	mock               *TextExtractorMock
	params             *TextExtractorMockBuildFileNameParams
	paramPtrs          *TextExtractorMockBuildFileNameParamPtrs
	expectationOrigins TextExtractorMockBuildFileNameExpectationOrigins
	results            *TextExtractorMockBuildFileNameResults
	returnOrigin       string
	Counter            uint64
}

// TextExtractorMockBuildFileNameParams contains parameters of the TextExtractor.BuildFileName
type TextExtractorMockBuildFileNameParams struct {
	fileName string
	fileType string
}

// TextExtractorMockBuildFileNameParamPtrs contains pointers to parameters of the TextExtractor.BuildFileName
type TextExtractorMockBuildFileNameParamPtrs struct {
	fileName *string
	fileType *string
}

// TextExtractorMockBuildFileNameResults contains results of the TextExtractor.BuildFileName
type TextExtractorMockBuildFileNameResults struct {
	s1 string
}

// TextExtractorMockBuildFileNameOrigins contains origins of expectations of the TextExtractor.BuildFileName
type TextExtractorMockBuildFileNameExpectationOrigins struct {
	origin         string
	originFileName string
	originFileType string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmBuildFileName *mTextExtractorMockBuildFileName) Optional() *mTextExtractorMockBuildFileName {
	mmBuildFileName.optional = true
	return mmBuildFileName
}

// Expect sets up expected params for TextExtractor.BuildFileName
func (mmBuildFileName *mTextExtractorMockBuildFileName) Expect(fileName string, fileType string) *mTextExtractorMockBuildFileName {
	if mmBuildFileName.mock.funcBuildFileName != nil {
		mmBuildFileName.mock.t.Fatalf("TextExtractorMock.BuildFileName mock is already set by Set")
	}

	if mmBuildFileName.defaultExpectation == nil {
		mmBuildFileName.defaultExpectation = &TextExtractorMockBuildFileNameExpectation{}
	}

	if mmBuildFileName.defaultExpectation.paramPtrs != nil {
		mmBuildFileName.mock.t.Fatalf("TextExtractorMock.BuildFileName mock is already set by ExpectParams functions")
	}

	mmBuildFileName.defaultExpectation.params = &TextExtractorMockBuildFileNameParams{fileName, fileType}
	mmBuildFileName.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmBuildFileName.expectations {
		if minimock.Equal(e.params, mmBuildFileName.defaultExpectation.params) {
			mmBuildFileName.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmBuildFileName.defaultExpectation.params)
		}
	}

	return mmBuildFileName
}

// ExpectFileNameParam1 sets up expected param fileName for TextExtractor.BuildFileName
func (mmBuildFileName *mTextExtractorMockBuildFileName) ExpectFileNameParam1(fileName string) *mTextExtractorMockBuildFileName {
	if mmBuildFileName.mock.funcBuildFileName != nil {
		mmBuildFileName.mock.t.Fatalf("TextExtractorMock.BuildFileName mock is already set by Set")
	}

	if mmBuildFileName.defaultExpectation == nil {
		mmBuildFileName.defaultExpectation = &TextExtractorMockBuildFileNameExpectation{}
	}

	if mmBuildFileName.defaultExpectation.params != nil {
		mmBuildFileName.mock.t.Fatalf("TextExtractorMock.BuildFileName mock is already set by Expect")
	}

	if mmBuildFileName.defaultExpectation.paramPtrs == nil {
		mmBuildFileName.defaultExpectation.paramPtrs = &TextExtractorMockBuildFileNameParamPtrs{}
	}
	mmBuildFileName.defaultExpectation.paramPtrs.fileName = &fileName
	mmBuildFileName.defaultExpectation.expectationOrigins.originFileName = minimock.CallerInfo(1)

	return mmBuildFileName
}

// ExpectFileTypeParam2 sets up expected param fileType for TextExtractor.BuildFileName
func (mmBuildFileName *mTextExtractorMockBuildFileName) ExpectFileTypeParam2(fileType string) *mTextExtractorMockBuildFileName {
	if mmBuildFileName.mock.funcBuildFileName != nil {
		mmBuildFileName.mock.t.Fatalf("TextExtractorMock.BuildFileName mock is already set by Set")
	}

	if mmBuildFileName.defaultExpectation == nil {
		mmBuildFileName.defaultExpectation = &TextExtractorMockBuildFileNameExpectation{}
	}

	if mmBuildFileName.defaultExpectation.params != nil {
		mmBuildFileName.mock.t.Fatalf("TextExtractorMock.BuildFileName mock is already set by Expect")
	}

	if mmBuildFileName.defaultExpectation.paramPtrs == nil {
		mmBuildFileName.defaultExpectation.paramPtrs = &TextExtractorMockBuildFileNameParamPtrs{}
	}
	mmBuildFileName.defaultExpectation.paramPtrs.fileType = &fileType
	mmBuildFileName.defaultExpectation.expectationOrigins.originFileType = minimock.CallerInfo(1)

	return mmBuildFileName
}

// Inspect accepts an inspector function that has same arguments as the TextExtractor.BuildFileName
func (mmBuildFileName *mTextExtractorMockBuildFileName) Inspect(f func(fileName string, fileType string)) *mTextExtractorMockBuildFileName {
	if mmBuildFileName.mock.inspectFuncBuildFileName != nil {
		mmBuildFileName.mock.t.Fatalf("Inspect function is already set for TextExtractorMock.BuildFileName")
	}

	mmBuildFileName.mock.inspectFuncBuildFileName = f

	return mmBuildFileName
}

// Return sets up results that will be returned by TextExtractor.BuildFileName
func (mmBuildFileName *mTextExtractorMockBuildFileName) Return(s1 string) *TextExtractorMock {
	if mmBuildFileName.mock.funcBuildFileName != nil {
		mmBuildFileName.mock.t.Fatalf("TextExtractorMock.BuildFileName mock is already set by Set")
	}

	if mmBuildFileName.defaultExpectation == nil {
		mmBuildFileName.defaultExpectation = &TextExtractorMockBuildFileNameExpectation{mock: mmBuildFileName.mock}
	}
	mmBuildFileName.defaultExpectation.results = &TextExtractorMockBuildFileNameResults{s1}
	mmBuildFileName.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmBuildFileName.mock
}

// Set uses given function f to mock the TextExtractor.BuildFileName method
func (mmBuildFileName *mTextExtractorMockBuildFileName) Set(f func(fileName string, fileType string) (s1 string)) *TextExtractorMock {
	if mmBuildFileName.defaultExpectation != nil {
		mmBuildFileName.mock.t.Fatalf("Default expectation is already set for the TextExtractor.BuildFileName method")
	}

	if len(mmBuildFileName.expectations) > 0 {
		mmBuildFileName.mock.t.Fatalf("Some expectations are already set for the TextExtractor.BuildFileName method")
	}

	mmBuildFileName.mock.funcBuildFileName = f
	mmBuildFileName.mock.funcBuildFileNameOrigin = minimock.CallerInfo(1)
	return mmBuildFileName.mock
}

// When sets expectation for the TextExtractor.BuildFileName which will trigger the result defined by the following
// Then helper
func (mmBuildFileName *mTextExtractorMockBuildFileName) When(fileName string, fileType string) *TextExtractorMockBuildFileNameExpectation {
	if mmBuildFileName.mock.funcBuildFileName != nil {
		mmBuildFileName.mock.t.Fatalf("TextExtractorMock.BuildFileName mock is already set by Set")
	}

	expectation := &TextExtractorMockBuildFileNameExpectation{
		mock:               mmBuildFileName.mock,
		params:             &TextExtractorMockBuildFileNameParams{fileName, fileType},
		expectationOrigins: TextExtractorMockBuildFileNameExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmBuildFileName.expectations = append(mmBuildFileName.expectations, expectation)
	return expectation
}

// Then sets up TextExtractor.BuildFileName return parameters for the expectation previously defined by the When method
func (e *TextExtractorMockBuildFileNameExpectation) Then(s1 string) *TextExtractorMock {
	e.results = &TextExtractorMockBuildFileNameResults{s1}
	return e.mock
}

// Times sets number of times TextExtractor.BuildFileName should be invoked
func (mmBuildFileName *mTextExtractorMockBuildFileName) Times(n uint64) *mTextExtractorMockBuildFileName {
	if n == 0 {
		mmBuildFileName.mock.t.Fatalf("Times of TextExtractorMock.BuildFileName mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmBuildFileName.expectedInvocations, n)
	mmBuildFileName.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmBuildFileName
}

func (mmBuildFileName *mTextExtractorMockBuildFileName) invocationsDone() bool {
	if len(mmBuildFileName.expectations) == 0 && mmBuildFileName.defaultExpectation == nil && mmBuildFileName.mock.funcBuildFileName == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmBuildFileName.mock.afterBuildFileNameCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmBuildFileName.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// BuildFileName implements mm_usecase.TextExtractor
func (mmBuildFileName *TextExtractorMock) BuildFileName(fileName string, fileType string) (s1 string) {
	mm_atomic.AddUint64(&mmBuildFileName.beforeBuildFileNameCounter, 1)
	defer mm_atomic.AddUint64(&mmBuildFileName.afterBuildFileNameCounter, 1)

	mmBuildFileName.t.Helper()

	if mmBuildFileName.inspectFuncBuildFileName != nil {
		mmBuildFileName.inspectFuncBuildFileName(fileName, fileType)
	}

	mm_params := TextExtractorMockBuildFileNameParams{fileName, fileType}

	// Record call args
	mmBuildFileName.BuildFileNameMock.mutex.Lock()
	mmBuildFileName.BuildFileNameMock.callArgs = append(mmBuildFileName.BuildFileNameMock.callArgs, &mm_params)
	mmBuildFileName.BuildFileNameMock.mutex.Unlock()

	for _, e := range mmBuildFileName.BuildFileNameMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1
		}
	}

	if mmBuildFileName.BuildFileNameMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmBuildFileName.BuildFileNameMock.defaultExpectation.Counter, 1)
		mm_want := mmBuildFileName.BuildFileNameMock.defaultExpectation.params
		mm_want_ptrs := mmBuildFileName.BuildFileNameMock.defaultExpectation.paramPtrs

		mm_got := TextExtractorMockBuildFileNameParams{fileName, fileType}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.fileName != nil && !minimock.Equal(*mm_want_ptrs.fileName, mm_got.fileName) {
				mmBuildFileName.t.Errorf("TextExtractorMock.BuildFileName got unexpected parameter fileName, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmBuildFileName.BuildFileNameMock.defaultExpectation.expectationOrigins.originFileName, *mm_want_ptrs.fileName, mm_got.fileName, minimock.Diff(*mm_want_ptrs.fileName, mm_got.fileName))
			}

			if mm_want_ptrs.fileType != nil && !minimock.Equal(*mm_want_ptrs.fileType, mm_got.fileType) {
				mmBuildFileName.t.Errorf("TextExtractorMock.BuildFileName got unexpected parameter fileType, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmBuildFileName.BuildFileNameMock.defaultExpectation.expectationOrigins.originFileType, *mm_want_ptrs.fileType, mm_got.fileType, minimock.Diff(*mm_want_ptrs.fileType, mm_got.fileType))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmBuildFileName.t.Errorf("TextExtractorMock.BuildFileName got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmBuildFileName.BuildFileNameMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmBuildFileName.BuildFileNameMock.defaultExpectation.results
		if mm_results == nil {
			mmBuildFileName.t.Fatal("No results are set for the TextExtractorMock.BuildFileName")
		}
		return (*mm_results).s1
	}
	if mmBuildFileName.funcBuildFileName != nil {
		return mmBuildFileName.funcBuildFileName(fileName, fileType)
	}
	mmBuildFileName.t.Fatalf("Unexpected call to TextExtractorMock.BuildFileName. %v %v", fileName, fileType)
	return
}

// BuildFileNameAfterCounter returns a count of finished TextExtractorMock.BuildFileName invocations
func (mmBuildFileName *TextExtractorMock) BuildFileNameAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmBuildFileName.afterBuildFileNameCounter)
}

// BuildFileNameBeforeCounter returns a count of TextExtractorMock.BuildFileName invocations
func (mmBuildFileName *TextExtractorMock) BuildFileNameBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmBuildFileName.beforeBuildFileNameCounter)
}

// Calls returns a list of arguments used in each call to TextExtractorMock.BuildFileName.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmBuildFileName *mTextExtractorMockBuildFileName) Calls() []*TextExtractorMockBuildFileNameParams {
	mmBuildFileName.mutex.RLock()

	argCopy := make([]*TextExtractorMockBuildFileNameParams, len(mmBuildFileName.callArgs))
	copy(argCopy, mmBuildFileName.callArgs)

	mmBuildFileName.mutex.RUnlock()

	return argCopy
}

// MinimockBuildFileNameDone returns true if the count of the BuildFileName invocations corresponds
// the number of defined expectations
func (m *TextExtractorMock) MinimockBuildFileNameDone() bool {
	if m.BuildFileNameMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.BuildFileNameMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.BuildFileNameMock.invocationsDone()
}

// MinimockBuildFileNameInspect logs each unmet expectation
func (m *TextExtractorMock) MinimockBuildFileNameInspect() {
	for _, e := range m.BuildFileNameMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TextExtractorMock.BuildFileName at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterBuildFileNameCounter := mm_atomic.LoadUint64(&m.afterBuildFileNameCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.BuildFileNameMock.defaultExpectation != nil && afterBuildFileNameCounter < 1 {
		if m.BuildFileNameMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to TextExtractorMock.BuildFileName at\n%s", m.BuildFileNameMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to TextExtractorMock.BuildFileName at\n%s with params: %#v", m.BuildFileNameMock.defaultExpectation.expectationOrigins.origin, *m.BuildFileNameMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcBuildFileName != nil && afterBuildFileNameCounter < 1 {
		m.t.Errorf("Expected call to TextExtractorMock.BuildFileName at\n%s", m.funcBuildFileNameOrigin)
	}

	if !m.BuildFileNameMock.invocationsDone() && afterBuildFileNameCounter > 0 {
		m.t.Errorf("Expected %d calls to TextExtractorMock.BuildFileName at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.BuildFileNameMock.expectedInvocations), m.BuildFileNameMock.expectedInvocationsOrigin, afterBuildFileNameCounter)
	}
}

type mTextExtractorMockDetectFileType struct {
	optional           bool
	mock               *TextExtractorMock
	defaultExpectation *TextExtractorMockDetectFileTypeExpectation
	expectations       []*TextExtractorMockDetectFileTypeExpectation

	callArgs []*TextExtractorMockDetectFileTypeParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// TextExtractorMockDetectFileTypeExpectation specifies expectation struct of the TextExtractor.DetectFileType
type TextExtractorMockDetectFileTypeExpectation struct {
	mock               *TextExtractorMock
	params             *TextExtractorMockDetectFileTypeParams
	paramPtrs          *TextExtractorMockDetectFileTypeParamPtrs
	expectationOrigins TextExtractorMockDetectFileTypeExpectationOrigins
	results            *TextExtractorMockDetectFileTypeResults
	returnOrigin       string
	Counter            uint64
}

// TextExtractorMockDetectFileTypeParams contains parameters of the TextExtractor.DetectFileType
type TextExtractorMockDetectFileTypeParams struct {
	fileName string
	data     []byte
}

// TextExtractorMockDetectFileTypeParamPtrs contains pointers to parameters of the TextExtractor.DetectFileType
type TextExtractorMockDetectFileTypeParamPtrs struct {
	fileName *string
	data     *[]byte
}

// TextExtractorMockDetectFileTypeResults contains results of the TextExtractor.DetectFileType
type TextExtractorMockDetectFileTypeResults struct {
	s1  string
	err error
}

// TextExtractorMockDetectFileTypeOrigins contains origins of expectations of the TextExtractor.DetectFileType
type TextExtractorMockDetectFileTypeExpectationOrigins struct {
	origin         string
	originFileName string
	originData     string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDetectFileType *mTextExtractorMockDetectFileType) Optional() *mTextExtractorMockDetectFileType {
	mmDetectFileType.optional = true
	return mmDetectFileType
}

// Expect sets up expected params for TextExtractor.DetectFileType
func (mmDetectFileType *mTextExtractorMockDetectFileType) Expect(fileName string, data []byte) *mTextExtractorMockDetectFileType {
	if mmDetectFileType.mock.funcDetectFileType != nil {
		mmDetectFileType.mock.t.Fatalf("TextExtractorMock.DetectFileType mock is already set by Set")
	}

	if mmDetectFileType.defaultExpectation == nil {
		mmDetectFileType.defaultExpectation = &TextExtractorMockDetectFileTypeExpectation{}
	}

	if mmDetectFileType.defaultExpectation.paramPtrs != nil {
		mmDetectFileType.mock.t.Fatalf("TextExtractorMock.DetectFileType mock is already set by ExpectParams functions")
	}

	mmDetectFileType.defaultExpectation.params = &TextExtractorMockDetectFileTypeParams{fileName, data}
	mmDetectFileType.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDetectFileType.expectations {
		if minimock.Equal(e.params, mmDetectFileType.defaultExpectation.params) {
			mmDetectFileType.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDetectFileType.defaultExpectation.params)
		}
	}

	return mmDetectFileType
}

// ExpectFileNameParam1 sets up expected param fileName for TextExtractor.DetectFileType
func (mmDetectFileType *mTextExtractorMockDetectFileType) ExpectFileNameParam1(fileName string) *mTextExtractorMockDetectFileType {
	if mmDetectFileType.mock.funcDetectFileType != nil {
		mmDetectFileType.mock.t.Fatalf("TextExtractorMock.DetectFileType mock is already set by Set")
	}

	if mmDetectFileType.defaultExpectation == nil {
		mmDetectFileType.defaultExpectation = &TextExtractorMockDetectFileTypeExpectation{}
	}

	if mmDetectFileType.defaultExpectation.params != nil {
		mmDetectFileType.mock.t.Fatalf("TextExtractorMock.DetectFileType mock is already set by Expect")
	}

	if mmDetectFileType.defaultExpectation.paramPtrs == nil {
		mmDetectFileType.defaultExpectation.paramPtrs = &TextExtractorMockDetectFileTypeParamPtrs{}
	}
	mmDetectFileType.defaultExpectation.paramPtrs.fileName = &fileName
	mmDetectFileType.defaultExpectation.expectationOrigins.originFileName = minimock.CallerInfo(1)

	return mmDetectFileType
}

// ExpectDataParam2 sets up expected param data for TextExtractor.DetectFileType
func (mmDetectFileType *mTextExtractorMockDetectFileType) ExpectDataParam2(data []byte) *mTextExtractorMockDetectFileType {
	if mmDetectFileType.mock.funcDetectFileType != nil {
		mmDetectFileType.mock.t.Fatalf("TextExtractorMock.DetectFileType mock is already set by Set")
	}

	if mmDetectFileType.defaultExpectation == nil {
		mmDetectFileType.defaultExpectation = &TextExtractorMockDetectFileTypeExpectation{}
	}

	if mmDetectFileType.defaultExpectation.params != nil {
		mmDetectFileType.mock.t.Fatalf("TextExtractorMock.DetectFileType mock is already set by Expect")
	}

	if mmDetectFileType.defaultExpectation.paramPtrs == nil {
		mmDetectFileType.defaultExpectation.paramPtrs = &TextExtractorMockDetectFileTypeParamPtrs{}
	}
	mmDetectFileType.defaultExpectation.paramPtrs.data = &data
	mmDetectFileType.defaultExpectation.expectationOrigins.originData = minimock.CallerInfo(1)

	return mmDetectFileType
}

// Inspect accepts an inspector function that has same arguments as the TextExtractor.DetectFileType
func (mmDetectFileType *mTextExtractorMockDetectFileType) Inspect(f func(fileName string, data []byte)) *mTextExtractorMockDetectFileType {
	if mmDetectFileType.mock.inspectFuncDetectFileType != nil {
		mmDetectFileType.mock.t.Fatalf("Inspect function is already set for TextExtractorMock.DetectFileType")
	}

	mmDetectFileType.mock.inspectFuncDetectFileType = f

	return mmDetectFileType
}

// Return sets up results that will be returned by TextExtractor.DetectFileType
func (mmDetectFileType *mTextExtractorMockDetectFileType) Return(s1 string, err error) *TextExtractorMock {
	if mmDetectFileType.mock.funcDetectFileType != nil {
		mmDetectFileType.mock.t.Fatalf("TextExtractorMock.DetectFileType mock is already set by Set")
	}

	if mmDetectFileType.defaultExpectation == nil {
		mmDetectFileType.defaultExpectation = &TextExtractorMockDetectFileTypeExpectation{mock: mmDetectFileType.mock}
	}
	mmDetectFileType.defaultExpectation.results = &TextExtractorMockDetectFileTypeResults{s1, err}
	mmDetectFileType.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDetectFileType.mock
}

// Set uses given function f to mock the TextExtractor.DetectFileType method
func (mmDetectFileType *mTextExtractorMockDetectFileType) Set(f func(fileName string, data []byte) (s1 string, err error)) *TextExtractorMock {
	if mmDetectFileType.defaultExpectation != nil {
		mmDetectFileType.mock.t.Fatalf("Default expectation is already set for the TextExtractor.DetectFileType method")
	}

	if len(mmDetectFileType.expectations) > 0 {
		mmDetectFileType.mock.t.Fatalf("Some expectations are already set for the TextExtractor.DetectFileType method")
	}

	mmDetectFileType.mock.funcDetectFileType = f
	mmDetectFileType.mock.funcDetectFileTypeOrigin = minimock.CallerInfo(1)
	return mmDetectFileType.mock
}

// When sets expectation for the TextExtractor.DetectFileType which will trigger the result defined by the following
// Then helper
func (mmDetectFileType *mTextExtractorMockDetectFileType) When(fileName string, data []byte) *TextExtractorMockDetectFileTypeExpectation {
	if mmDetectFileType.mock.funcDetectFileType != nil {
		mmDetectFileType.mock.t.Fatalf("TextExtractorMock.DetectFileType mock is already set by Set")
	}

	expectation := &TextExtractorMockDetectFileTypeExpectation{
		mock:               mmDetectFileType.mock,
		params:             &TextExtractorMockDetectFileTypeParams{fileName, data},
		expectationOrigins: TextExtractorMockDetectFileTypeExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDetectFileType.expectations = append(mmDetectFileType.expectations, expectation)
	return expectation
}

// Then sets up TextExtractor.DetectFileType return parameters for the expectation previously defined by the When method
func (e *TextExtractorMockDetectFileTypeExpectation) Then(s1 string, err error) *TextExtractorMock {
	e.results = &TextExtractorMockDetectFileTypeResults{s1, err}
	return e.mock
}

// Times sets number of times TextExtractor.DetectFileType should be invoked
func (mmDetectFileType *mTextExtractorMockDetectFileType) Times(n uint64) *mTextExtractorMockDetectFileType {
	if n == 0 {
		mmDetectFileType.mock.t.Fatalf("Times of TextExtractorMock.DetectFileType mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDetectFileType.expectedInvocations, n)
	mmDetectFileType.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDetectFileType
}

func (mmDetectFileType *mTextExtractorMockDetectFileType) invocationsDone() bool {
	if len(mmDetectFileType.expectations) == 0 && mmDetectFileType.defaultExpectation == nil && mmDetectFileType.mock.funcDetectFileType == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDetectFileType.mock.afterDetectFileTypeCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDetectFileType.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DetectFileType implements mm_usecase.TextExtractor
func (mmDetectFileType *TextExtractorMock) DetectFileType(fileName string, data []byte) (s1 string, err error) {
	mm_atomic.AddUint64(&mmDetectFileType.beforeDetectFileTypeCounter, 1)
	defer mm_atomic.AddUint64(&mmDetectFileType.afterDetectFileTypeCounter, 1)

	mmDetectFileType.t.Helper()

	if mmDetectFileType.inspectFuncDetectFileType != nil {
		mmDetectFileType.inspectFuncDetectFileType(fileName, data)
	}

	mm_params := TextExtractorMockDetectFileTypeParams{fileName, data}

	// Record call args
	mmDetectFileType.DetectFileTypeMock.mutex.Lock()
	mmDetectFileType.DetectFileTypeMock.callArgs = append(mmDetectFileType.DetectFileTypeMock.callArgs, &mm_params)
	mmDetectFileType.DetectFileTypeMock.mutex.Unlock()

	for _, e := range mmDetectFileType.DetectFileTypeMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmDetectFileType.DetectFileTypeMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDetectFileType.DetectFileTypeMock.defaultExpectation.Counter, 1)
		mm_want := mmDetectFileType.DetectFileTypeMock.defaultExpectation.params
		mm_want_ptrs := mmDetectFileType.DetectFileTypeMock.defaultExpectation.paramPtrs

		mm_got := TextExtractorMockDetectFileTypeParams{fileName, data}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.fileName != nil && !minimock.Equal(*mm_want_ptrs.fileName, mm_got.fileName) {
				mmDetectFileType.t.Errorf("TextExtractorMock.DetectFileType got unexpected parameter fileName, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDetectFileType.DetectFileTypeMock.defaultExpectation.expectationOrigins.originFileName, *mm_want_ptrs.fileName, mm_got.fileName, minimock.Diff(*mm_want_ptrs.fileName, mm_got.fileName))
			}

			if mm_want_ptrs.data != nil && !minimock.Equal(*mm_want_ptrs.data, mm_got.data) {
				mmDetectFileType.t.Errorf("TextExtractorMock.DetectFileType got unexpected parameter data, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDetectFileType.DetectFileTypeMock.defaultExpectation.expectationOrigins.originData, *mm_want_ptrs.data, mm_got.data, minimock.Diff(*mm_want_ptrs.data, mm_got.data))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDetectFileType.t.Errorf("TextExtractorMock.DetectFileType got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDetectFileType.DetectFileTypeMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDetectFileType.DetectFileTypeMock.defaultExpectation.results
		if mm_results == nil {
			mmDetectFileType.t.Fatal("No results are set for the TextExtractorMock.DetectFileType")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmDetectFileType.funcDetectFileType != nil {
		return mmDetectFileType.funcDetectFileType(fileName, data)
	}
	mmDetectFileType.t.Fatalf("Unexpected call to TextExtractorMock.DetectFileType. %v %v", fileName, data)
	return
}

// DetectFileTypeAfterCounter returns a count of finished TextExtractorMock.DetectFileType invocations
func (mmDetectFileType *TextExtractorMock) DetectFileTypeAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDetectFileType.afterDetectFileTypeCounter)
}

// DetectFileTypeBeforeCounter returns a count of TextExtractorMock.DetectFileType invocations
func (mmDetectFileType *TextExtractorMock) DetectFileTypeBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDetectFileType.beforeDetectFileTypeCounter)
}

// Calls returns a list of arguments used in each call to TextExtractorMock.DetectFileType.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDetectFileType *mTextExtractorMockDetectFileType) Calls() []*TextExtractorMockDetectFileTypeParams {
	mmDetectFileType.mutex.RLock()

	argCopy := make([]*TextExtractorMockDetectFileTypeParams, len(mmDetectFileType.callArgs))
	copy(argCopy, mmDetectFileType.callArgs)

	mmDetectFileType.mutex.RUnlock()

	return argCopy
}

// MinimockDetectFileTypeDone returns true if the count of the DetectFileType invocations corresponds
// the number of defined expectations
func (m *TextExtractorMock) MinimockDetectFileTypeDone() bool {
	if m.DetectFileTypeMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DetectFileTypeMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DetectFileTypeMock.invocationsDone()
}

// MinimockDetectFileTypeInspect logs each unmet expectation
func (m *TextExtractorMock) MinimockDetectFileTypeInspect() {
	for _, e := range m.DetectFileTypeMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TextExtractorMock.DetectFileType at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDetectFileTypeCounter := mm_atomic.LoadUint64(&m.afterDetectFileTypeCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DetectFileTypeMock.defaultExpectation != nil && afterDetectFileTypeCounter < 1 {
		if m.DetectFileTypeMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to TextExtractorMock.DetectFileType at\n%s", m.DetectFileTypeMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to TextExtractorMock.DetectFileType at\n%s with params: %#v", m.DetectFileTypeMock.defaultExpectation.expectationOrigins.origin, *m.DetectFileTypeMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDetectFileType != nil && afterDetectFileTypeCounter < 1 {
		m.t.Errorf("Expected call to TextExtractorMock.DetectFileType at\n%s", m.funcDetectFileTypeOrigin)
	}

	if !m.DetectFileTypeMock.invocationsDone() && afterDetectFileTypeCounter > 0 {
		m.t.Errorf("Expected %d calls to TextExtractorMock.DetectFileType at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DetectFileTypeMock.expectedInvocations), m.DetectFileTypeMock.expectedInvocationsOrigin, afterDetectFileTypeCounter)
	}
}

type mTextExtractorMockExtractText struct {
	optional           bool
	mock               *TextExtractorMock
	defaultExpectation *TextExtractorMockExtractTextExpectation
	expectations       []*TextExtractorMockExtractTextExpectation

	callArgs []*TextExtractorMockExtractTextParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// TextExtractorMockExtractTextExpectation specifies expectation struct of the TextExtractor.ExtractText
type TextExtractorMockExtractTextExpectation struct {
	mock               *TextExtractorMock
	params             *TextExtractorMockExtractTextParams
	paramPtrs          *TextExtractorMockExtractTextParamPtrs
	expectationOrigins TextExtractorMockExtractTextExpectationOrigins
	results            *TextExtractorMockExtractTextResults
	returnOrigin       string
	Counter            uint64
}

// TextExtractorMockExtractTextParams contains parameters of the TextExtractor.ExtractText
type TextExtractorMockExtractTextParams struct {
	fileType string
	data     []byte
}

// TextExtractorMockExtractTextParamPtrs contains pointers to parameters of the TextExtractor.ExtractText
type TextExtractorMockExtractTextParamPtrs struct {
	fileType *string
	data     *[]byte
}

// TextExtractorMockExtractTextResults contains results of the TextExtractor.ExtractText
type TextExtractorMockExtractTextResults struct {
	s1  string
	err error
}

// TextExtractorMockExtractTextOrigins contains origins of expectations of the TextExtractor.ExtractText
type TextExtractorMockExtractTextExpectationOrigins struct {
	origin         string
	originFileType string
	originData     string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmExtractText *mTextExtractorMockExtractText) Optional() *mTextExtractorMockExtractText {
	mmExtractText.optional = true
	return mmExtractText
}

// Expect sets up expected params for TextExtractor.ExtractText
func (mmExtractText *mTextExtractorMockExtractText) Expect(fileType string, data []byte) *mTextExtractorMockExtractText {
	if mmExtractText.mock.funcExtractText != nil {
		mmExtractText.mock.t.Fatalf("TextExtractorMock.ExtractText mock is already set by Set")
	}

	if mmExtractText.defaultExpectation == nil {
		mmExtractText.defaultExpectation = &TextExtractorMockExtractTextExpectation{}
	}

	if mmExtractText.defaultExpectation.paramPtrs != nil {
		mmExtractText.mock.t.Fatalf("TextExtractorMock.ExtractText mock is already set by ExpectParams functions")
	}

	mmExtractText.defaultExpectation.params = &TextExtractorMockExtractTextParams{fileType, data}
	mmExtractText.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmExtractText.expectations {
		if minimock.Equal(e.params, mmExtractText.defaultExpectation.params) {
			mmExtractText.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmExtractText.defaultExpectation.params)
		}
	}

	return mmExtractText
}

// ExpectFileTypeParam1 sets up expected param fileType for TextExtractor.ExtractText
func (mmExtractText *mTextExtractorMockExtractText) ExpectFileTypeParam1(fileType string) *mTextExtractorMockExtractText {
	if mmExtractText.mock.funcExtractText != nil {
		mmExtractText.mock.t.Fatalf("TextExtractorMock.ExtractText mock is already set by Set")
	}

	if mmExtractText.defaultExpectation == nil {
		mmExtractText.defaultExpectation = &TextExtractorMockExtractTextExpectation{}
	}

	if mmExtractText.defaultExpectation.params != nil {
		mmExtractText.mock.t.Fatalf("TextExtractorMock.ExtractText mock is already set by Expect")
	}

	if mmExtractText.defaultExpectation.paramPtrs == nil {
		mmExtractText.defaultExpectation.paramPtrs = &TextExtractorMockExtractTextParamPtrs{}
	}
	mmExtractText.defaultExpectation.paramPtrs.fileType = &fileType
	mmExtractText.defaultExpectation.expectationOrigins.originFileType = minimock.CallerInfo(1)

	return mmExtractText
}

// ExpectDataParam2 sets up expected param data for TextExtractor.ExtractText
func (mmExtractText *mTextExtractorMockExtractText) ExpectDataParam2(data []byte) *mTextExtractorMockExtractText {
	if mmExtractText.mock.funcExtractText != nil {
		mmExtractText.mock.t.Fatalf("TextExtractorMock.ExtractText mock is already set by Set")
	}

	if mmExtractText.defaultExpectation == nil {
		mmExtractText.defaultExpectation = &TextExtractorMockExtractTextExpectation{}
	}

	if mmExtractText.defaultExpectation.params != nil {
		mmExtractText.mock.t.Fatalf("TextExtractorMock.ExtractText mock is already set by Expect")
	}

	if mmExtractText.defaultExpectation.paramPtrs == nil {
		mmExtractText.defaultExpectation.paramPtrs = &TextExtractorMockExtractTextParamPtrs{}
	}
	mmExtractText.defaultExpectation.paramPtrs.data = &data
	mmExtractText.defaultExpectation.expectationOrigins.originData = minimock.CallerInfo(1)

	return mmExtractText
}

// Inspect accepts an inspector function that has same arguments as the TextExtractor.ExtractText
func (mmExtractText *mTextExtractorMockExtractText) Inspect(f func(fileType string, data []byte)) *mTextExtractorMockExtractText {
	if mmExtractText.mock.inspectFuncExtractText != nil {
		mmExtractText.mock.t.Fatalf("Inspect function is already set for TextExtractorMock.ExtractText")
	}

	mmExtractText.mock.inspectFuncExtractText = f

	return mmExtractText
}

// Return sets up results that will be returned by TextExtractor.ExtractText
func (mmExtractText *mTextExtractorMockExtractText) Return(s1 string, err error) *TextExtractorMock {
	if mmExtractText.mock.funcExtractText != nil {
		mmExtractText.mock.t.Fatalf("TextExtractorMock.ExtractText mock is already set by Set")
	}

	if mmExtractText.defaultExpectation == nil {
		mmExtractText.defaultExpectation = &TextExtractorMockExtractTextExpectation{mock: mmExtractText.mock}
	}
	mmExtractText.defaultExpectation.results = &TextExtractorMockExtractTextResults{s1, err}
	mmExtractText.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmExtractText.mock
}

// Set uses given function f to mock the TextExtractor.ExtractText method
func (mmExtractText *mTextExtractorMockExtractText) Set(f func(fileType string, data []byte) (s1 string, err error)) *TextExtractorMock {
	if mmExtractText.defaultExpectation != nil {
		mmExtractText.mock.t.Fatalf("Default expectation is already set for the TextExtractor.ExtractText method")
	}

	if len(mmExtractText.expectations) > 0 {
		mmExtractText.mock.t.Fatalf("Some expectations are already set for the TextExtractor.ExtractText method")
	}

	mmExtractText.mock.funcExtractText = f
	mmExtractText.mock.funcExtractTextOrigin = minimock.CallerInfo(1)
	return mmExtractText.mock
}

// When sets expectation for the TextExtractor.ExtractText which will trigger the result defined by the following
// Then helper
func (mmExtractText *mTextExtractorMockExtractText) When(fileType string, data []byte) *TextExtractorMockExtractTextExpectation {
	if mmExtractText.mock.funcExtractText != nil {
		mmExtractText.mock.t.Fatalf("TextExtractorMock.ExtractText mock is already set by Set")
	}

	expectation := &TextExtractorMockExtractTextExpectation{
		mock:               mmExtractText.mock,
		params:             &TextExtractorMockExtractTextParams{fileType, data},
		expectationOrigins: TextExtractorMockExtractTextExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmExtractText.expectations = append(mmExtractText.expectations, expectation)
	return expectation
}

// Then sets up TextExtractor.ExtractText return parameters for the expectation previously defined by the When method
func (e *TextExtractorMockExtractTextExpectation) Then(s1 string, err error) *TextExtractorMock {
	e.results = &TextExtractorMockExtractTextResults{s1, err}
	return e.mock
}

// Times sets number of times TextExtractor.ExtractText should be invoked
func (mmExtractText *mTextExtractorMockExtractText) Times(n uint64) *mTextExtractorMockExtractText {
	if n == 0 {
		mmExtractText.mock.t.Fatalf("Times of TextExtractorMock.ExtractText mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmExtractText.expectedInvocations, n)
	mmExtractText.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmExtractText
}

func (mmExtractText *mTextExtractorMockExtractText) invocationsDone() bool {
	if len(mmExtractText.expectations) == 0 && mmExtractText.defaultExpectation == nil && mmExtractText.mock.funcExtractText == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmExtractText.mock.afterExtractTextCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmExtractText.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ExtractText implements mm_usecase.TextExtractor
func (mmExtractText *TextExtractorMock) ExtractText(fileType string, data []byte) (s1 string, err error) {
	mm_atomic.AddUint64(&mmExtractText.beforeExtractTextCounter, 1)
	defer mm_atomic.AddUint64(&mmExtractText.afterExtractTextCounter, 1)

	mmExtractText.t.Helper()

	if mmExtractText.inspectFuncExtractText != nil {
		mmExtractText.inspectFuncExtractText(fileType, data)
	}

	mm_params := TextExtractorMockExtractTextParams{fileType, data}

	// Record call args
	mmExtractText.ExtractTextMock.mutex.Lock()
	mmExtractText.ExtractTextMock.callArgs = append(mmExtractText.ExtractTextMock.callArgs, &mm_params)
	mmExtractText.ExtractTextMock.mutex.Unlock()

	for _, e := range mmExtractText.ExtractTextMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmExtractText.ExtractTextMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmExtractText.ExtractTextMock.defaultExpectation.Counter, 1)
		mm_want := mmExtractText.ExtractTextMock.defaultExpectation.params
		mm_want_ptrs := mmExtractText.ExtractTextMock.defaultExpectation.paramPtrs

		mm_got := TextExtractorMockExtractTextParams{fileType, data}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.fileType != nil && !minimock.Equal(*mm_want_ptrs.fileType, mm_got.fileType) {
				mmExtractText.t.Errorf("TextExtractorMock.ExtractText got unexpected parameter fileType, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmExtractText.ExtractTextMock.defaultExpectation.expectationOrigins.originFileType, *mm_want_ptrs.fileType, mm_got.fileType, minimock.Diff(*mm_want_ptrs.fileType, mm_got.fileType))
			}

			if mm_want_ptrs.data != nil && !minimock.Equal(*mm_want_ptrs.data, mm_got.data) {
				mmExtractText.t.Errorf("TextExtractorMock.ExtractText got unexpected parameter data, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmExtractText.ExtractTextMock.defaultExpectation.expectationOrigins.originData, *mm_want_ptrs.data, mm_got.data, minimock.Diff(*mm_want_ptrs.data, mm_got.data))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmExtractText.t.Errorf("TextExtractorMock.ExtractText got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmExtractText.ExtractTextMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmExtractText.ExtractTextMock.defaultExpectation.results
		if mm_results == nil {
			mmExtractText.t.Fatal("No results are set for the TextExtractorMock.ExtractText")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmExtractText.funcExtractText != nil {
		return mmExtractText.funcExtractText(fileType, data)
	}
	mmExtractText.t.Fatalf("Unexpected call to TextExtractorMock.ExtractText. %v %v", fileType, data)
	return
}

// ExtractTextAfterCounter returns a count of finished TextExtractorMock.ExtractText invocations
func (mmExtractText *TextExtractorMock) ExtractTextAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmExtractText.afterExtractTextCounter)
}

// ExtractTextBeforeCounter returns a count of TextExtractorMock.ExtractText invocations
func (mmExtractText *TextExtractorMock) ExtractTextBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmExtractText.beforeExtractTextCounter)
}

// Calls returns a list of arguments used in each call to TextExtractorMock.ExtractText.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmExtractText *mTextExtractorMockExtractText) Calls() []*TextExtractorMockExtractTextParams {
	mmExtractText.mutex.RLock()

	argCopy := make([]*TextExtractorMockExtractTextParams, len(mmExtractText.callArgs))
	copy(argCopy, mmExtractText.callArgs)

	mmExtractText.mutex.RUnlock()

	return argCopy
}

// MinimockExtractTextDone returns true if the count of the ExtractText invocations corresponds
// the number of defined expectations
func (m *TextExtractorMock) MinimockExtractTextDone() bool {
	if m.ExtractTextMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ExtractTextMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ExtractTextMock.invocationsDone()
}

// MinimockExtractTextInspect logs each unmet expectation
func (m *TextExtractorMock) MinimockExtractTextInspect() {
	for _, e := range m.ExtractTextMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TextExtractorMock.ExtractText at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterExtractTextCounter := mm_atomic.LoadUint64(&m.afterExtractTextCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ExtractTextMock.defaultExpectation != nil && afterExtractTextCounter < 1 {
		if m.ExtractTextMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to TextExtractorMock.ExtractText at\n%s", m.ExtractTextMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to TextExtractorMock.ExtractText at\n%s with params: %#v", m.ExtractTextMock.defaultExpectation.expectationOrigins.origin, *m.ExtractTextMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcExtractText != nil && afterExtractTextCounter < 1 {
		m.t.Errorf("Expected call to TextExtractorMock.ExtractText at\n%s", m.funcExtractTextOrigin)
	}

	if !m.ExtractTextMock.invocationsDone() && afterExtractTextCounter > 0 {
		m.t.Errorf("Expected %d calls to TextExtractorMock.ExtractText at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ExtractTextMock.expectedInvocations), m.ExtractTextMock.expectedInvocationsOrigin, afterExtractTextCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *TextExtractorMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockBuildFileNameInspect()

			m.MinimockDetectFileTypeInspect()

			m.MinimockExtractTextInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *TextExtractorMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *TextExtractorMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockBuildFileNameDone() &&
		m.MinimockDetectFileTypeDone() &&
		m.MinimockExtractTextDone()
}
