// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.1
// source: multiagent_api/multiagent.proto

package multiagent_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MultiAgentService_GenerateDecision_FullMethodName = "/multiagent.service.v1.MultiAgentService/GenerateDecision"
	MultiAgentService_ClassifyRole_FullMethodName     = "/multiagent.service.v1.MultiAgentService/ClassifyRole"
)

// MultiAgentServiceClient is the client API for MultiAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MultiAgentServiceClient interface {
	GenerateDecision(ctx context.Context, in *GenerateDecisionRequest, opts ...grpc.CallOption) (*GenerateDecisionResponse, error)
	// ClassifyRole asks the LLM to map a vacancy title+description onto one of
	// the prompt-template roles multiagent already serves (programmer, manager,
	// accountant, …) plus the catch-all "default". The vacancy service calls
	// this on Create/Update so the role downstream HR decisions key off is
	// chosen by the same model that writes them, instead of a keyword table.
	ClassifyRole(ctx context.Context, in *ClassifyRoleRequest, opts ...grpc.CallOption) (*ClassifyRoleResponse, error)
}

type multiAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiAgentServiceClient(cc grpc.ClientConnInterface) MultiAgentServiceClient {
	return &multiAgentServiceClient{cc}
}

func (c *multiAgentServiceClient) GenerateDecision(ctx context.Context, in *GenerateDecisionRequest, opts ...grpc.CallOption) (*GenerateDecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateDecisionResponse)
	err := c.cc.Invoke(ctx, MultiAgentService_GenerateDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiAgentServiceClient) ClassifyRole(ctx context.Context, in *ClassifyRoleRequest, opts ...grpc.CallOption) (*ClassifyRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyRoleResponse)
	err := c.cc.Invoke(ctx, MultiAgentService_ClassifyRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MultiAgentServiceServer is the server API for MultiAgentService service.
// All implementations must embed UnimplementedMultiAgentServiceServer
// for forward compatibility.
type MultiAgentServiceServer interface {
	GenerateDecision(context.Context, *GenerateDecisionRequest) (*GenerateDecisionResponse, error)
	// ClassifyRole asks the LLM to map a vacancy title+description onto one of
	// the prompt-template roles multiagent already serves (programmer, manager,
	// accountant, …) plus the catch-all "default". The vacancy service calls
	// this on Create/Update so the role downstream HR decisions key off is
	// chosen by the same model that writes them, instead of a keyword table.
	ClassifyRole(context.Context, *ClassifyRoleRequest) (*ClassifyRoleResponse, error)
	mustEmbedUnimplementedMultiAgentServiceServer()
}

// UnimplementedMultiAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMultiAgentServiceServer struct{}

func (UnimplementedMultiAgentServiceServer) GenerateDecision(context.Context, *GenerateDecisionRequest) (*GenerateDecisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateDecision not implemented")
}
func (UnimplementedMultiAgentServiceServer) ClassifyRole(context.Context, *ClassifyRoleRequest) (*ClassifyRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClassifyRole not implemented")
}
func (UnimplementedMultiAgentServiceServer) mustEmbedUnimplementedMultiAgentServiceServer() {}
func (UnimplementedMultiAgentServiceServer) testEmbeddedByValue()                           {}

// UnsafeMultiAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultiAgentServiceServer will
// result in compilation errors.
type UnsafeMultiAgentServiceServer interface {
	mustEmbedUnimplementedMultiAgentServiceServer()
}

func RegisterMultiAgentServiceServer(s grpc.ServiceRegistrar, srv MultiAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedMultiAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MultiAgentService_ServiceDesc, srv)
}

func _MultiAgentService_GenerateDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiAgentServiceServer).GenerateDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiAgentService_GenerateDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiAgentServiceServer).GenerateDecision(ctx, req.(*GenerateDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiAgentService_ClassifyRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiAgentServiceServer).ClassifyRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiAgentService_ClassifyRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiAgentServiceServer).ClassifyRole(ctx, req.(*ClassifyRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MultiAgentService_ServiceDesc is the grpc.ServiceDesc for MultiAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MultiAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "multiagent.service.v1.MultiAgentService",
	HandlerType: (*MultiAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateDecision",
			Handler:    _MultiAgentService_GenerateDecision_Handler,
		},
		{
			MethodName: "ClassifyRole",
			Handler:    _MultiAgentService_ClassifyRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "multiagent_api/multiagent.proto",
}
