// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.1
// source: resume_api/resume.proto

package resume_api

import (
	context "context"
	models "github.com/artem13815/hr/resume/internal/pb/models"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResumeService_CreateCandidate_FullMethodName           = "/resume.service.v1.ResumeService/CreateCandidate"
	ResumeService_GetCandidate_FullMethodName              = "/resume.service.v1.ResumeService/GetCandidate"
	ResumeService_CreateCandidateFromResume_FullMethodName = "/resume.service.v1.ResumeService/CreateCandidateFromResume"
	ResumeService_IngestResume_FullMethodName              = "/resume.service.v1.ResumeService/IngestResume"
	ResumeService_IngestResumeBatch_FullMethodName         = "/resume.service.v1.ResumeService/IngestResumeBatch"
	ResumeService_UploadResume_FullMethodName              = "/resume.service.v1.ResumeService/UploadResume"
	ResumeService_GetResume_FullMethodName                 = "/resume.service.v1.ResumeService/GetResume"
	ResumeService_DownloadResume_FullMethodName            = "/resume.service.v1.ResumeService/DownloadResume"
	ResumeService_DeleteCandidate_FullMethodName           = "/resume.service.v1.ResumeService/DeleteCandidate"
)

// ResumeServiceClient is the client API for ResumeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResumeServiceClient interface {
	CreateCandidate(ctx context.Context, in *models.CreateCandidateRequest, opts ...grpc.CallOption) (*models.CandidateResponse, error)
	GetCandidate(ctx context.Context, in *models.GetCandidateRequest, opts ...grpc.CallOption) (*models.CandidateResponse, error)
	CreateCandidateFromResume(ctx context.Context, in *models.CreateCandidateFromResumeRequest, opts ...grpc.CallOption) (*models.CandidateResumeResponse, error)
	IngestResume(ctx context.Context, in *models.CreateCandidateFromResumeRequest, opts ...grpc.CallOption) (*models.CandidateResumeResponse, error)
	IngestResumeBatch(ctx context.Context, in *models.BatchIngestResumeRequest, opts ...grpc.CallOption) (*models.BatchIngestResumeResponse, error)
	UploadResume(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[models.UploadResumeRequest, models.UploadResumeResponse], error)
	GetResume(ctx context.Context, in *models.GetResumeRequest, opts ...grpc.CallOption) (*models.ResumeResponse, error)
	DownloadResume(ctx context.Context, in *models.DownloadResumeRequest, opts ...grpc.CallOption) (*models.DownloadResumeResponse, error)
	DeleteCandidate(ctx context.Context, in *models.DeleteCandidateRequest, opts ...grpc.CallOption) (*models.DeleteCandidateResponse, error)
}

type resumeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResumeServiceClient(cc grpc.ClientConnInterface) ResumeServiceClient {
	return &resumeServiceClient{cc}
}

func (c *resumeServiceClient) CreateCandidate(ctx context.Context, in *models.CreateCandidateRequest, opts ...grpc.CallOption) (*models.CandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.CandidateResponse)
	err := c.cc.Invoke(ctx, ResumeService_CreateCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resumeServiceClient) GetCandidate(ctx context.Context, in *models.GetCandidateRequest, opts ...grpc.CallOption) (*models.CandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.CandidateResponse)
	err := c.cc.Invoke(ctx, ResumeService_GetCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resumeServiceClient) CreateCandidateFromResume(ctx context.Context, in *models.CreateCandidateFromResumeRequest, opts ...grpc.CallOption) (*models.CandidateResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.CandidateResumeResponse)
	err := c.cc.Invoke(ctx, ResumeService_CreateCandidateFromResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resumeServiceClient) IngestResume(ctx context.Context, in *models.CreateCandidateFromResumeRequest, opts ...grpc.CallOption) (*models.CandidateResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.CandidateResumeResponse)
	err := c.cc.Invoke(ctx, ResumeService_IngestResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resumeServiceClient) IngestResumeBatch(ctx context.Context, in *models.BatchIngestResumeRequest, opts ...grpc.CallOption) (*models.BatchIngestResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.BatchIngestResumeResponse)
	err := c.cc.Invoke(ctx, ResumeService_IngestResumeBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resumeServiceClient) UploadResume(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[models.UploadResumeRequest, models.UploadResumeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResumeService_ServiceDesc.Streams[0], ResumeService_UploadResume_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[models.UploadResumeRequest, models.UploadResumeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResumeService_UploadResumeClient = grpc.ClientStreamingClient[models.UploadResumeRequest, models.UploadResumeResponse]

func (c *resumeServiceClient) GetResume(ctx context.Context, in *models.GetResumeRequest, opts ...grpc.CallOption) (*models.ResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.ResumeResponse)
	err := c.cc.Invoke(ctx, ResumeService_GetResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resumeServiceClient) DownloadResume(ctx context.Context, in *models.DownloadResumeRequest, opts ...grpc.CallOption) (*models.DownloadResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.DownloadResumeResponse)
	err := c.cc.Invoke(ctx, ResumeService_DownloadResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resumeServiceClient) DeleteCandidate(ctx context.Context, in *models.DeleteCandidateRequest, opts ...grpc.CallOption) (*models.DeleteCandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.DeleteCandidateResponse)
	err := c.cc.Invoke(ctx, ResumeService_DeleteCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResumeServiceServer is the server API for ResumeService service.
// All implementations must embed UnimplementedResumeServiceServer
// for forward compatibility.
type ResumeServiceServer interface {
	CreateCandidate(context.Context, *models.CreateCandidateRequest) (*models.CandidateResponse, error)
	GetCandidate(context.Context, *models.GetCandidateRequest) (*models.CandidateResponse, error)
	CreateCandidateFromResume(context.Context, *models.CreateCandidateFromResumeRequest) (*models.CandidateResumeResponse, error)
	IngestResume(context.Context, *models.CreateCandidateFromResumeRequest) (*models.CandidateResumeResponse, error)
	IngestResumeBatch(context.Context, *models.BatchIngestResumeRequest) (*models.BatchIngestResumeResponse, error)
	UploadResume(grpc.ClientStreamingServer[models.UploadResumeRequest, models.UploadResumeResponse]) error
	GetResume(context.Context, *models.GetResumeRequest) (*models.ResumeResponse, error)
	DownloadResume(context.Context, *models.DownloadResumeRequest) (*models.DownloadResumeResponse, error)
	DeleteCandidate(context.Context, *models.DeleteCandidateRequest) (*models.DeleteCandidateResponse, error)
	mustEmbedUnimplementedResumeServiceServer()
}

// UnimplementedResumeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResumeServiceServer struct{}

func (UnimplementedResumeServiceServer) CreateCandidate(context.Context, *models.CreateCandidateRequest) (*models.CandidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCandidate not implemented")
}
func (UnimplementedResumeServiceServer) GetCandidate(context.Context, *models.GetCandidateRequest) (*models.CandidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCandidate not implemented")
}
func (UnimplementedResumeServiceServer) CreateCandidateFromResume(context.Context, *models.CreateCandidateFromResumeRequest) (*models.CandidateResumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCandidateFromResume not implemented")
}
func (UnimplementedResumeServiceServer) IngestResume(context.Context, *models.CreateCandidateFromResumeRequest) (*models.CandidateResumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestResume not implemented")
}
func (UnimplementedResumeServiceServer) IngestResumeBatch(context.Context, *models.BatchIngestResumeRequest) (*models.BatchIngestResumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestResumeBatch not implemented")
}
func (UnimplementedResumeServiceServer) UploadResume(grpc.ClientStreamingServer[models.UploadResumeRequest, models.UploadResumeResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadResume not implemented")
}
func (UnimplementedResumeServiceServer) GetResume(context.Context, *models.GetResumeRequest) (*models.ResumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResume not implemented")
}
func (UnimplementedResumeServiceServer) DownloadResume(context.Context, *models.DownloadResumeRequest) (*models.DownloadResumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadResume not implemented")
}
func (UnimplementedResumeServiceServer) DeleteCandidate(context.Context, *models.DeleteCandidateRequest) (*models.DeleteCandidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCandidate not implemented")
}
func (UnimplementedResumeServiceServer) mustEmbedUnimplementedResumeServiceServer() {}
func (UnimplementedResumeServiceServer) testEmbeddedByValue()                       {}

// UnsafeResumeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResumeServiceServer will
// result in compilation errors.
type UnsafeResumeServiceServer interface {
	mustEmbedUnimplementedResumeServiceServer()
}

func RegisterResumeServiceServer(s grpc.ServiceRegistrar, srv ResumeServiceServer) {
	// If the following call panics, it indicates UnimplementedResumeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResumeService_ServiceDesc, srv)
}

func _ResumeService_CreateCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.CreateCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeServiceServer).CreateCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResumeService_CreateCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeServiceServer).CreateCandidate(ctx, req.(*models.CreateCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResumeService_GetCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.GetCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeServiceServer).GetCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResumeService_GetCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeServiceServer).GetCandidate(ctx, req.(*models.GetCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResumeService_CreateCandidateFromResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.CreateCandidateFromResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeServiceServer).CreateCandidateFromResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResumeService_CreateCandidateFromResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeServiceServer).CreateCandidateFromResume(ctx, req.(*models.CreateCandidateFromResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResumeService_IngestResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.CreateCandidateFromResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeServiceServer).IngestResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResumeService_IngestResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeServiceServer).IngestResume(ctx, req.(*models.CreateCandidateFromResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResumeService_IngestResumeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.BatchIngestResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeServiceServer).IngestResumeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResumeService_IngestResumeBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeServiceServer).IngestResumeBatch(ctx, req.(*models.BatchIngestResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResumeService_UploadResume_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ResumeServiceServer).UploadResume(&grpc.GenericServerStream[models.UploadResumeRequest, models.UploadResumeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResumeService_UploadResumeServer = grpc.ClientStreamingServer[models.UploadResumeRequest, models.UploadResumeResponse]

func _ResumeService_GetResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.GetResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeServiceServer).GetResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResumeService_GetResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeServiceServer).GetResume(ctx, req.(*models.GetResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResumeService_DownloadResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.DownloadResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeServiceServer).DownloadResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResumeService_DownloadResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeServiceServer).DownloadResume(ctx, req.(*models.DownloadResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResumeService_DeleteCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.DeleteCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeServiceServer).DeleteCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResumeService_DeleteCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeServiceServer).DeleteCandidate(ctx, req.(*models.DeleteCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResumeService_ServiceDesc is the grpc.ServiceDesc for ResumeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResumeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resume.service.v1.ResumeService",
	HandlerType: (*ResumeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCandidate",
			Handler:    _ResumeService_CreateCandidate_Handler,
		},
		{
			MethodName: "GetCandidate",
			Handler:    _ResumeService_GetCandidate_Handler,
		},
		{
			MethodName: "CreateCandidateFromResume",
			Handler:    _ResumeService_CreateCandidateFromResume_Handler,
		},
		{
			MethodName: "IngestResume",
			Handler:    _ResumeService_IngestResume_Handler,
		},
		{
			MethodName: "IngestResumeBatch",
			Handler:    _ResumeService_IngestResumeBatch_Handler,
		},
		{
			MethodName: "GetResume",
			Handler:    _ResumeService_GetResume_Handler,
		},
		{
			MethodName: "DownloadResume",
			Handler:    _ResumeService_DownloadResume_Handler,
		},
		{
			MethodName: "DeleteCandidate",
			Handler:    _ResumeService_DeleteCandidate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadResume",
			Handler:       _ResumeService_UploadResume_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "resume_api/resume.proto",
}
